### ISSUE TITLE
Colaboração

### ISSUE THREAD

**Issue by tiagorbf** [dssg-pt/covid19pt-data#10]
Ola. Neste momento eu estou a importar estes dados para um datastudio e a por os dados publicos em https://coronaplots.com/plots/portugal.html

Gostava de saber que outros projectos existem e se existe alguma forma de podermos colaborar?

Obrigado

**Comment by ishouldbedany** [comment]
@tiagorbf Uma possível ideia: à medida que vais desenvolvendo a tua dashboard, dá-nos feedbacka acerca de que dados seriam úteis e nós avaliamos como conseguimos completar.

O nosso objectivo é mesmo esse: suportar toda a gente que esteja a fazer este tipo de análises e iniciativas.

**Comment by tiagorbf** [comment]
Será possível disponibilizar as areas mais frequentadas nos últimos 15 dias de pessoas COVID19 positivas? Totalmente anonimizado claro. 
Mas podia ajudar a alertar pessoas que possivelmente tenham estado na mesma area e desta forma conter um pouco o contagio.

**Comment by ishouldbedany** [comment]
@tiagorbf Creio que não existe nenhuma fonte oficial para esse tipo de dados. A DGS informa acerca do número de cadeias de contágio, mas não as descreve mais. 

Provavelmente determinados fontes conseguirão juntar estes dados mas, como bem notas, não sem significativas quebras na privacidade dos pacientes afectados.
