### ISSUE TITLE
Vacinas_Detalhe com dados vazios

### ISSUE THREAD

**Issue by emanuelmarques** [dssg-pt/covid19pt-data#1031]
Viva,

A ultima linha do Vacinas_detalhe nao tem dados à exceção dos 3 primeiros campos.

https://github.com/dssg-pt/covid19pt-data/blob/master/vacinas_detalhe.csv

Já havia sido identificado?

Thanks :)

**Comment by davipt** [comment]
Sim. O dataset 23 não foi publicado. https://covid19.min-saude.pt/relatorio-de-vacinacao/ tem o PDF 23 mas manteve o Dataset 22 anterior.

Esperemos que amanhã à noite não repitam a situação.

Preenchi alguns valores à mão a partir do PDF, os suficientes para os cálculos do vacinas.csv, mas não todos que daria demasiado trabalho. E tive esperança que se apercebessem do ficheiro em falta.

O relatório costuma sair terça à noite. A semana passada atrasou e só saiu na quarta. Vamos ver como corre esta semana. O dataset tem os dados históricos portanto se publicarem o próximo, trará também os valores em falta desta semana. 

Falamos outra vez na quarta ok? 🤞

**Comment by davipt** [comment]
Relatório vacinação #24 publicado terça 27 à noite incluindo o Dataset.csv 👍 

https://github.com/dssg-pt/covid19pt-data/pull/1035

Temos novamente dados no vacinas_detalhes, incluindo os valores em falta da semana passada, embora pela segunda vez tenha os valores de `recebidas` e `distribuidas` em falta, mas esses dados são conhecidos pelos datasets anteriores e pelos PDFs, portanto adicionei mais um hack para os popular correctamente. 

Confirma se está tudo ok e se houver algo a melhorar, reabre esta issue ou uma nova.

Obrigado
