### ISSUE TITLE
"buracos" nos dados de vacinação?

### ISSUE THREAD

**Issue by ghomem** [dssg-pt/covid19pt-data#1040]
Apercebi-me que os dados das vacinas têm alguns buracos. Podem confirmar se é verdade ou sou eu que estou a fazer algo de errado?

Aqui vai uma imagem referente às colunas  'inoculados' e 'pessoas_vacinadas_completamente'.

![127363309-5085ae78-c367-4f46-af23-163096945d0f](https://user-images.githubusercontent.com/3352900/127370273-234f1aea-73ff-46c6-b037-29081d28c8f3.png)

Obrigado

**Comment by davipt** [comment]
https://github.com/dssg-pt/covid19pt-data/issues/967

Foi upstream.
Basicamente as plataformas das ilhas foram integradas na plataforma VACINAS e os registos históricos foram sincronizados durante vários dias, o que inflacionou nesses dias os valores diários.

Os três primeiros valores de "doses" são os dados diários conforme publicados oficialmente. "doses", não "pessoas", e apenas o continente.
Os valores de pessoas e vacinas são calculados a partir do relatório semanal, incluindo as ilhas e as Janssen correctamente nas "totalmente vacinadas", e nos seis dias seguintes incrementa com os valores diários disponíveis.

A 28 ajustou-se com o relatório. De 29 a 4-7 os valores diários foram irrealistas por causa do carregamento dos dados das ilhas. Foram retirados para não distorcerem as linhas por exemplo do OWID e FT, e prevenir o ruído por exemplo no tweeter dos dias de "record de 280 mil por dia" ou até o próprio governo a publicar um gráfico do OWID que nos dava com crescimento de 1,51 pessoas por 100 mil por dia. :| 
A 5 Jul voltou-se a ajustar com o relatório semanal, e dia 6 e 7 manteve-se os valores pois correspondem aos valores diários reportados pelo Almirante, mais alguns milhares para as ilhas. O valor de dia 8 já não fez sentido pois era muito maior que o valor do Almirante de dia 9.
No dia 9 finalmente aperceberam-se da situação com os valores diários, e como era sexta feira, desligaram o serviço, e só voltou a haver dados diários na segunda dia 12, após adicionarem o equivalente a um "… WHERE … AND region not (madeira, açores)" :D 

Portanto os buracos nas doses são nos dias em que os valores não são publicados e não conseguimos obter por outras formas. (Como a API da dashboard não tem histórico, é procurar outro site de vacinas que tenha ficado com cópia)
Os buracos nas pessoas/vacinas são quando não há dados para os calcular, ou quando os valores não fazem sentido e até se sabe porquê, mas não o suficiente para tentar recalcular e salvar esses dias.

E é isto 🤷‍♂️ No código da OWID eles têm um método no Pandas para recriar os pontos em falta mantendo a linha consistente, mas não me lembro agora qual era nem onde exactamente está.

Obrigado

**Comment by ghomem** [comment]
Olá @davipt 

Obrigado por esta resposta com os detalhes.

Por curiosidade, pareceu-me da tua resposta que este repositório é o fornecedor de dados do OWID. Percebi bem?

> Os buracos nas pessoas/vacinas são quando não há dados para os calcular, ou quando os valores não fazem sentido e 
>até se sabe porquê, mas não o suficiente para tentar recalcular e salvar esses dias

OK está esclarecido.

>No código da OWID eles têm um método no Pandas para recriar os pontos em falta mantendo a linha consistente, mas não me >lembro agora qual era nem onde exactamente está.

Penso que não teria dificuldade em executar isso mas tenho alguns problemas de consciência em relação a interpolar as linhas só para ficarem bonitas, especialmente se estamos a falar de muitos dias seguidos - tenho uma interpolação para buracos de um dia, que não me parece grave mas mais do que isso causa-me dúvidas.

Acho que o fornecedor de dados sabe sempre mais dos dados que o visualizador. Se o fornecedor acha que não se justifica interpolar ou não tem forma de o fazer, talvez não deva ser a camada de visualização a fazê-lo :-)

Que achas?

Pelo menos com esta explicação já fico a perceber melhor o que se passa.

**Comment by davipt** [comment]
Concordo que não se deve interpolar os dados.

O meu comentário é que o OWID mantêm a linha desde o ultimo ponto conhecido até ao próximo.  Como os dias com dados reais têm bolinha e são "mouse-over", os dias em falta são claros, e a linha entre eles não confunde: [OWID](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2021-04-26..latest&pickerSort=asc&pickerMetric=location&Metric=Vaccine+doses&Interval=Cumulative&Relative+to+Population=true&Align+outbreaks=false&country=ESP~PRT~GBR~USA)

É apenas uma questão de visualização, quiçá até apenas se a biblioteca dos gráficos faz isso por omissão ou não.

**Comment by ghomem** [comment]
Vejo com alguma frequência e OWID e só me apercebi após este teu comentário que os buracos do OWID são linhas rectas sem "bolinhas". O comportamente é exactamente como tu dizes e tem alguma lógica mão estou completamente convencido que não seja misleading. E visto que o bokeh parece não suportar este tipo de autofill (https://github.com/bokeh/bokeh/issues/737) acho que vou mesmo viver com os buracos, pelo menos para já.

Obrigado.

**Comment by davipt** [comment]
A linha sem bolinhas é a media desse período. "o caminho mais curto entre dois pontos é uma linha recta" :)
A alternativa era pior - subia brutalmente e depois descia para valores negativos no dia 5. Daí termos de retirar os valores desses dias.
Na pratica nessa semana não houve nada de excepcional - nem falta de vacinas, nem o cancelamento temporário da Janssen quando o pessoal desmaiou com o calor em Mafra, nem os fins de semana têm sido muito diferentes dos dias normais, portanto a linha real não pode diferir muito da linha recta, portanto não havendo dados correctos para esses dias, seguiu-se em frente.

**Comment by ghomem** [comment]
Eu estou de acordo com retirarem os pontos. Não estou é 100% convencido de ser eu desenhar a reta :-) Quando abri este issue pensava que fosse algum artefacto ou imperfeições de dados passadas que entretanto podiam ser corrigidas. Em face da explicação, estou OK com os buracos.
