### ISSUE TITLE
Dados Equivocados 25/04/2020 - 30/04/2020

### ISSUE THREAD

**Issue by EDKLINDEMANN** [dssg-pt/covid19pt-data#109]
data | Confirmados | Diff - MT (MS) | Zona Norte -   Confirmados |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
30/04/2020 | 24987 | 203 | 14867 | 84 | Aferido pelo total da diferença de   todas as outras regiões.
01/05/2020 | 25190 |   | 14951 |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |

**Comment by filipafcastro** [comment]
Olá @EDKLINDEMANN, obrigada pelo aviso! Vamos corrigir, assim que publiquem oficialmente os relatórios com as correções.

**Comment by fbatista72** [comment]
Bom dia
No https://www.worldometers.info/coronavirus/country/portugal/ os dados já estão corrigidos.
Não percebo as contas que fizeram para estas correcções.

**Comment by paulomaia20** [comment]
Olá a todos,

Os relatórios publicados continham ainda muitas inconsistências, vamos aguardar que façam as correções de forma adequada!

**Comment by fbatista72** [comment]
Bom dia
Os pdf dos relatórios alterados pela DGS tem nomes diferentes, os script que vocês fizeram para ler os pdf estão assim a ler ficheiros errados.

**Comment by EDKLINDEMANN** [comment]
Boa tarde Colegas. Vejam abaixo valores verificados manualmente para V/validação:

Dia | Casos Confirmados | Suspeitos | Hospitalizados | UCI | Em Vigilância | Casos Não Confirmados | Óbitos | Recuperados | Norte - Confirmados | Norte - Óbitos | Centro - Confirmados | Centro - Óbitos | Sul - Confirmados | Sul - Óbitos | Alentejo Confirmados | Alentejo - Óbitos | Algarve - Confirmados | Algarve - Óbitso | Madeira - Confirmados | Madeira - Óbitos | Açores - Confirmados | Açores - Óbitos |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
25/04/2020 | 22797 | 227393 | 1068 | 188 | 29621 | 200219 | 854 | 1228 | 13707 | 491 | 3116 | 183 | 5277 | 160 | 183 | 1 | 320 | 11 | 85 | 0 |   | 109 | 8
26/04/2020 | 23392 | 231737 | 1040 | 186 | 29932 | 203562 | 880 | 1277 | 14072 | 502 | 3183 | 188 | 5435 | 170 | 185 | 1 | 320 | 11 | 86 | 0 |   | 111 | 8
27/04/2020 | 23683 | 236229 | 1005 | 182 | 30453 | 207873 | 903 | 1329 | 14205 | 519 | 3232 | 188 | 5531 | 175 | 187 | 1 | 322 | 12 | 86 | 0 |   | 120 | 8
28/04/2020 | 23846 | 237390 | 995 | 176 | 30703 | 208453 | 928 | 1357 | 14315 | 536 | 3252 | 191 | 5556 | 179 | 189 | 1 | 328 | 12 | 86 | 0 |   | 120 | 9
29/04/2020 | 24144 | 238887 | 936 | 172 | 29559 | 211180 | 948 | 1369 | 14524 | 546 | 3289 | 194 | 5593 | 185 | 201 | 1 | 330 | 12 | 86 | 0 |   | 121 | 10
30/04/2020 | 24505 | 243655 | 980 | 169 | 29568 | 215325 | 973 | 1470 | 14715 | 556 | 3340 | 196 | 5695 | 195 | 214 | 1 | 330 | 13 | 86 | 0 |   | 125 | 12
01/05/2020 | 24987 | 250905 | 892 | 154 | 29756 | 222090 | 1007 | 1647 | 14726 | 566 | 3389 | 198 | 5815 | 199 | 218 | 1 | 331 | 13 | 86 | 0 |   | 127 | 12
02/05/2020 | 25190 | 252728 | 855 | 150 | 27895 | 223777 | 1043 | 1671 | 14867 | 578 | 3426 | 206 | 6047 | 205 | 218 | 1 | 331 | 13 | 86 | 0 |   | 131 | 13
03/05/2020 | 25282 | 252889 | 856 | 144 | 25324 | 223916 | 1043 | 1689 | 15021 | 597 | 3447 | 209 | 6047 | 210 | 218 | 1 | 331 | 13 | 86 | 0 |   | 131 | 13
04/05/2020 | 25524 | 254510 | 813 | 143 | 25081 | 226226 | 1063 | 1712 | 15141 | 609 | 3478 | 209 | 6136 | 218 | 218 | 1 | 333 | 13 | 86 | 0 |   | 132 | 13
