### ISSUE TITLE
dados estratificados: casos vs vacinação

### ISSUE THREAD

**Issue by ghomem** [dssg-pt/covid19pt-data#1093]
Estou a tentar aferir a eficácia de vacinação nos contágios por via um conjunto de gráficos em que no eixos dos YY está o número de casos no grupo etário em questão e no eixo dos XX está a percentagem de pessoas completamente vacinadas no grupo estário em questão.

Mas pelo que vejo os grupos etários no reporte dos casos são:

0-9
10-19
20-29
30-39
40-49
50-59
60-69
70-79
80+

enquanto no caso das vacinas temos:

0-17
18-24
25-49
50-64
65-79
80+

Há alguma forma de obter os dados com os grupos etários expressos de forma consistente?

Obrigado.

**Comment by davipt** [comment]
Que conheça, não.

Os dados de COVID19 estão segmentados por M+F e grupos de 10 anos (com 80+ para o restante), para casos confirmados e óbitos.

Os dados de vacinação, quer no relatório semanal da DGS https://covid19.min-saude.pt/relatorio-de-vacinacao/ quer no site da ECDC https://qap.ecdc.europa.eu/public/extensions/COVID-19/vaccine-tracker.html#age-group-tab
via https://opendata.ecdc.europa.eu/covid19/vaccine_tracker/csv/data.csv estão com esses segmentos diferentes, provavelmente propositado para alinhar com o resto da europa.

**Comment by ghomem** [comment]
Bom, não havendo solução, resta-me então fazer a análise incidir sobre os 3 grupos comuns que se podem obter:

0-49
50-79
80+

Não é ideal em termos de granularidade mas já dará para alguma coisa.Obrigado.
