### ISSUE TITLE
Criar site do projecto para recolher dados

### ISSUE THREAD

**Issue by jruipinto** [dssg-pt/covid19pt-data#11]
Seria interessante criar um site para o projecto onde as pessoas comuns podem consultar os dados que são aqui disponibilizados (dashboard como outras que já existem por exemplo no Reddit)e talvez até ter um formulário no mesmo site onde podíamos recolher ainda mais dados do público geral.

Dado que não parece ser possível testar toda a gente e o vírus tem características muito particulares como a de poder ser transmitido mesmo antes de os portadores apresentarem sintomas, talvez fosse possível com recurso aos dados mencionados criarmos uma ferramenta que nos indicasse a probabilidade de aparecerem novos casos em determinada zona geográfica de modo a que as autoridades de saúde possam utilizar os testes disponíveis com mais eficiência.

Se concordarem, eu disponibilizo-me a participar no desenvolvimento do site proposto (e penso que não será necessário nada muito complexo, caso outros queiram contribuir também).

**Comment by paulomaia20** [comment]
Já estão a avançar algumas iniciativas semelhantes, mas gosto bastante da ideia. No projeto Tech4Covid2019 há um sub-projeto "TrackCovid19" com uma ideia semelhante, de crowdsourcing para determinação de redes de contágio. Se queres ajudar, dá uma olhadela no proojeto deles :)

O que lhes sugeri foi usar os nossos dados, e à medida que forem adquirindo mais dados, passarem-nos também para nós, para os colocarmos aqui no repositório.

**Comment by ruicalheno133** [comment]
No entretanto desenvolvi uma simples dashboard com algumas informações presentes no dataset deste repo. https://ruicalheno133.github.io/covid-19-dashboard/

**Comment by ishouldbedany** [comment]
@ruicalheno133 Boa! Podes adicionar aqui -> #20 ?
