### ISSUE TITLE
Dados desactualizados

### ISSUE THREAD

**Issue by diasjoaocarlos** [dssg-pt/covid19pt-data#1101]
Os dados do ficheiro correspondentes ao dia N são de facto os dados dados pela Direcção-Geral de Saúde referentes ao dia N-1!

**Comment by davipt** [comment]
Correcto. Todas as entradas para dia N correspondem aos dados até às 23:59 do dia N-1.
É este o formato de datas usado pela DGS em todos os relatórios - diário covid (PDF), vacinação (quando publicavam a imagem nas redes sociais), dashboard, e os semanais de vacinação (PDF/CSV) e quinzenais incidência (PDF).

**Comment by diasjoaocarlos** [comment]
Embora o relatório seja emitido e datado de uma determinada data, isso não quer dizer que os dados sejam dessa data. No entanto está indicado no relatório, se bem que em letras pequeninas a data a que se referem os dados.
Penso que o relatório da DGS não segue boas práticas de apresentação de dados, e que é muita pena que o atraso nos dados exista. Assim os "malucos" dos dados não tem dados verdadeiros (há atraso). E cada vez há mais "malucos" dos dados...

**Comment by davipt** [comment]
A forma coerente de reportar dados "até à data N às 23:59:59" é user o dia seguinte N+1 (e omitindo o "meia noite" para simplicidade).
Nem todos os dados correspondem a um dia específico. Por exemplo os dados semanais de vacinação correspondem ao agregado dos 7 dias anteriores à data no registo, e os dados de incidência correspondem aos 14 dias anteriores.
É assim que tem funcionado consistentemente há 18 meses. O mesmo acontece com outras fontes que lidam com dados mais complexos que apenas "contagens do dia".

**Comment by diasjoaocarlos** [comment]
A forma coerente de reportar os dados referentes às 24 horas do dia N é reportá-los ao dia N!
O V/. ficheiro diz dia N n casos. A DGS dia dia N m casos, n diferente de m!!!!! Ou seja picos nos números de casos nos dados da DGS são omitidos nos V/. dados no dia em que acontecem. Portugal entrou na CEE a 1 de janeiro de 1986 e não a 2 de janeiro de 1986!!!

**Comment by davipt** [comment]
A DGS reporta dados acumulados contabilizados até às 23:59 do dia anterior à data no relatório. 

Por exemplo no [registo da DGS de dia 31-08-2021](https://covid19.min-saude.pt/wp-content/uploads/2021/08/547_DGS_boletim_20210831.pdf) (portanto até 30-08-2021 23:59:59) houve 1 037 927 casos confirmados, o mesmo valor na [dashboard da DGS](https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/). (ainda não foi actualizada com os dados de ontem). 30-08-2021 23:59:59 é equivalente a 31-08-2021 quando a hora é omitida.

Portugal deixou de estar fora da CEE à meia noite de dia 1 de janeiro de 1986.

**Comment by davipt** [comment]
For reference, the original issue reported at [OWID](https://github.com/owid/covid-19-data/issues/1920) because their charts do report correctly day N for the data "up to day N", no matter if it's the previous 14, 7, or single day.

OWID is correct, and so is the data sources from DGS. It's the narrow perception of "daily numbers" that can be confusing.
