### ISSUE TITLE
Dados das vacinas - 6 de Setembro

### ISSUE THREAD

**Issue by alicescfernandes** [dssg-pt/covid19pt-data#1104]
Olá!

Parece-me que houve uma correção nos dados de vacinação referentes ao dia 6 de Setembro. Hoje, a API mostra estes dados,

```json
{
   "Data":1630972800000,
   "Inoculacao1":8382528,
   "Inoculacao1_Ac":8382528,
   "Inoculacao2":6056287,
   "Inoculacao2_Ac":6056287,
   "Vacinados":14438815,
   "Vacinados_Ac":14438815,
   "Column7":null,
   "Column8":null,
   "Column9":null,
   "Column10":null,
   "Column11":null,
   "Column12":null,
   "Column13":null,
   "Column14":null,
   "Column15":null,
   "Column16":null,
   "Column17":null,
   "Column18":null,
   "FID":1
}
```

e no dasbhoard aparece o seguinte
![image](https://user-images.githubusercontent.com/15971182/132317357-de08fe35-fb51-401b-ac81-c7c596ab7d11.png)
 
Conseguem perceber se estes dados são para dia 7 ou dia 6? É que os numeros são menores do que aqueles que vocês (e também eu temos para dia 6)

**Comment by alicescfernandes** [comment]
Desculpem pela confusão, mas os numeros não costumam ser atualizados assim tão cedo. Afinal parece estar tudo em ordem.

**Comment by davipt** [comment]
Desde que deixaram de publicar as imagens nas redes sociais e portanto o potencial embargo de não meter os números na APi da dashboard até que fossem anunciados pela própria DGS, tem havido meia dúzia de dias em que os números aparecem bem cedo. Hoje foi perto das 9h15.

Até os dados de COVID já foram publicados cedo, bem antes do PDF sair, umas duas ou três vezes.
