### ISSUE TITLE
Dados - 21/09/2021

### ISSUE THREAD

**Issue by alicescfernandes** [dssg-pt/covid19pt-data#1110]
Aparentemente já temos dados para hoje
![image](https://user-images.githubusercontent.com/15971182/134177833-2eaf3602-df62-4fe6-89d1-cb982b2305bc.png)

**Comment by davipt** [comment]
Fantástico. Mas ainda não há relatório semanal (14h30). Já corrigi o workflow (faltava o dia de ontem, vazio) e já fez update e mandou o tweet. Obrigado Alice 👍

**Comment by alicescfernandes** [comment]
De nada :) Obrigado eu!
