### ISSUE TITLE
Terceiras doses?

### ISSUE THREAD

**Issue by martimlobao** [dssg-pt/covid19pt-data#1119]
Já existe alguma fonte regular sobre terceiras doses/boosters de vacinas contra o Covid? Algumas publicações já começaram a reportar números, mas não encontrei números oficiais na página da DGS. Seria interessante adicionar estes valores à tabela de vacinas. 

https://www.publico.pt/2021/10/24/sociedade/noticia/covid19-123-mil-pessoas-ja-tomaram-terceira-dose-portugal-1982295

**Comment by tiago32rodriguez** [comment]
Existe esta fonte oficial. Não são números concretos mas dá pra remediar. 
https://www.sns.gov.pt/noticias/2021/11/24/plano-de-vacinacao-4/

**Comment by tiago32rodriguez** [comment]
No site do ECDC tbm já está disponível alguma informação:
![image](https://user-images.githubusercontent.com/75172821/143623659-12eda5c9-e398-4e83-a4f8-fa92203fb3b9.png)

**Comment by trapko91** [comment]
Foi lançado hoje um novo relatório diário com informação das 3as doses

https://covid19.min-saude.pt/wp-content/uploads/2021/11/Relatorio-Vacinacao-Diario-n.o-1.pdf

No entanto retiraram os dados referentes a quem só tem a 1ª dose. Agora só dizem quantas pessoas têm a vacinação completa e as 3as doses.

**Comment by davipt** [comment]
Actualizei o `vacinas.csv` com esses dados do PDF diário. Vou tentar manter os dados actualizados. Obrigado pelo aviso!
