### ISSUE TITLE
Vacinados/Casos Activos

### ISSUE THREAD

**Issue by rpdorm** [dssg-pt/covid19pt-data#1123]
Carece saber o número de vacinados com casos activos.

**Comment by davipt** [comment]
Recomendo a leitura dos "Relatórios de monitorização das linhas vermelhas para a COVID-19” em https://covid19.min-saude.pt/relatorio-linhas-vermelhas/ 

O relatório inclui uma secção com o risco de hospitalização por estado vacinal (apenas 50+) e uma tabela com a efectividade da vacina para infeção sintomática, hospitalização, e óbito, para 30+.

Como esses documentos são PDFs practicamente impossíveis de serem processados automaticamente, e como este projecto é composto por voluntários nos seus tempos livres, não há CSV com os dados em formato computável. 

Ainda. Por curiosidade pessoal, talvez ainda pegue nisso. Se acontecer, a discussão será em https://github.com/dssg-pt/covid19pt-data/issues/1132 

Obrigado.
