### ISSUE TITLE
População com pelo menos uma dose

### ISSUE THREAD

**Issue by tiago32rodriguez** [dssg-pt/covid19pt-data#1138]
Acho que os dados da crianças dos 5-11 que iniciaram a vacinação deveriam ser considerados na população com pelo menos uma dose.

**Comment by davipt** [comment]
Os dados da população com pelo menos uma dose não são conhecidos em detalhe desde o último relatório semanal de 14 de novembro [https://covid19.min-saude.pt/relatorio-de-vacinacao/](https://covid19.min-saude.pt/relatorio-de-vacinacao)

O `vacinas.csv` mantêm o último valor conhecido - 9.053.901 - desde 15 de novembro até há uns dias, quando o “totalmente vacinados” passou a ser maior. Não faria sentido um ser menor que o outro.

Compreendo que neste momento faria sentido adicionar os novos 5-11 aos iniciados pois estaria correcto durante as próximas três semanas, mas a partir daí deixar-se-ia de saber quantos teriam uma ou duas doses.
Alem disso o bot da vacinação da europa (https://blasf1.github.io/VaccinatEU/) ainda está a contar com vacinação a partir dos 12 anos, e não gostaria de ver a nossa percentagem a passar dos 100%.

O ideal seria a DGS ou Ministério da Saúde voltarem a publicar dados concretos (por exemplo o dataset semanal do link acima, que tinha tudo detalhado ao nível de continente / ilhas e por idades).

**Comment by tiago32rodriguez** [comment]
Compreendo e concordo.

Outra solução passa por usar os dados do relatório semanal do ECDC. Esses contam também os dados dos maiores de 11 que foram sendo vacinados durante estas últimas semanas.

Fonte:
https://www.ecdc.europa.eu/en/publications-data/data-covid-19-vaccination-eu-eea

**Comment by davipt** [comment]
Eu usava os dados da ECDC para contabilização das vacinas por marca, o que não estava disponível nos relatórios nacionais. Os dados são bons para contabilizar doses, mas não tão lineares para contabilizar pessoas, pois a dose unica de Janssen é considerado vacinação completa, tal como uma dose única (geralmente Cominarty ou Moderna) para os previamente infetados. Ou seja, os números não são directamente comparáveis.

No entanto os valores da ECDC podem ser um bom proxy para o “pelo menos uma dose” e ajudar a ter esse valor mais correcto que o actual - igual ao totalmente vacinado. Deixa espreitar isso outra vez…

**Comment by tiago32rodriguez** [comment]
Concordo que para os dados de Vacinação completa não são comparáveis com os dados nacionais (por diferentes considerações do que é uma pessoa totalmente vacinada), mas para pessoas com pelo menos uma dose considero q é bastante fiável.

Os dados são até divididos por "zonas" por isso até é possível recolher os dados para Portugal e para Portugal Continental (tendo em conta que para este último temos os dados do relatório diário).

Também são bons para se saber o número de doses de reforço em Portugal inteiro e não apenas em Portugal Continental como são divulgados no relatório diário.

**Comment by davipt** [comment]
```
FirstDose       8597483
SecondDose      6824846
DoseAdditional1 2435412
```

Por mais que olhe para os dados da ECDC, não sei mesmo o que faça com eles.

Dose adicional a 2.435K até parece bater certo com as ilhas, pois hoje eram apenas 2.395K no continente.

Mas quando me dá apenas 8.597.483 primeiras doses, quando cá dizem que são 8.657.229 totalmente vacinados só no continente, e mais de 9.065.414 contando com o ultimo valor conhecido das ilhas, e depois dá 6.824.846 para segunda dose… não consigo reconciliar estes valores.

Por isto nunca integrei os valores da ECDC no cálculo oficial dos vacina*.csv.

Mas aceitam-se sugestões.

**Comment by tiago32rodriguez** [comment]
Isso vem do relatório ou vem da página do ECDC?

Pegando no CSV do site que mandei em cima e somando as primeiras doses de todas as faixas etárias de todas as semanas o número é superior a 9.250.000 .

O valor do site acho que corresponde apenas aos adultos.

**Comment by davipt** [comment]
Tens razão. 🤦‍♂️ A soma das linhas com REGION=ALL e TargetGroup=ALL é que estão erradas - undercounted.

Somando todos os TargetGroup como dizes, ou todas as regiões, dá os mesmos valores:
```
FirstDose       9275313
SecondDose      7333285
DoseAdditional1 2435946
```

Isto permite, com pouco esforço, ter um valor mais correcto para “pelo menos uma dose” e para “reforço”, mesmo que actualize apenas uma vez por semana. 👍

**Comment by tiago32rodriguez** [comment]
Exato, assim fica tudo mais correto.

Eu já tinha reparado nesse erro há algum tempo, mas eles nunca o corrigiram, acho mesmo que esse valor será só o dos +18.

**Comment by davipt** [comment]
https://twitter.com/PlenoDVacinacao/status/1473758562493022210

Espero não me ter enganado nas contas.

Passou a ter `reforço_continente` com os dados diários do continente, e o `reforço` passa a ser ajustado pelos dados da ECDC.

Ajustei também os `inoculados` (pelo menos uma dose) com os dados da ECDC, com o caveat de retirar, por agora, a vacinação dos 5-11, senão as percentagens dos ">12" dariam mais de 100%.

Dá uns dias para ver se os números fazem sentido, que por vezes há enganos e só passado uns dias é que se percebe o que tem de ser corrigido - por exemplo ontem adicionaram percentagem de reforço por idades ao pdf, mas esqueceram-se de incrementar os valores absolutos.

Vou ver o que se pode fazer para incluir os 5-11 nos inoculados sem se rebentar a escala - falar com o Blas por exemplo.

Vê lá o csv e os tweets do bot a ver se faz sentido. 

Obrigado!

**Comment by tiago32rodriguez** [comment]
Parece-me tudo correto, ficando mesmo só essa questão dos 5-11. 

Obrigado eu!

**Comment by davipt** [comment]
https://blasf1.github.io/VaccinatEU/
<img width="1162" alt="Captura de ecrã 2021-12-23, às 11 25 40" src="https://user-images.githubusercontent.com/574281/147233902-b5d2f1bf-4e65-43ec-a79b-2b7f109a2ae9.png">
