### ISSUE TITLE
API Vost pede credenciais de acesso

### ISSUE THREAD

**Issue by lourencoabrunhosa** [dssg-pt/covid19pt-data#1142]
Olá, tenho uma aplicação que se alimenta diariamente dos dados covid através da API vost, e apercebi-me que há cerca de 4 dias esta deixou de funcionar porque não tenho credenciais de acesso que agora a API parece pedir. Não consigo encontrar como aceder as estas credenciais para  voltar a pôr a aplicação a correr.

**Comment by davipt** [comment]
https://covid19-api.vost.pt @JorgeMiguelGomes podes dar aqui uma ajuda em nome da VOST se fazes favor? Obrigado.

**Comment by JorgeMiguelGomes** [comment]
@davipt há um issue aberto sobre esta mudança que deveria ter sido passado para o Read.me / Documentação 
https://github.com/dssg-pt/Docker_COVID_API/issues/12 

@lourencoabrunhosa lê por favor o issue e envia o e-mail com os dados necessários para o endereço que lá consta. 
Obrigado

**Comment by lourencoabrunhosa** [comment]
@JorgeMiguelGomes Obrigado, já enviei o email. Fica assim resolvida a minha questão
