### ISSUE TITLE
Repetição parcial de dados dos concelhos (datas: 25/11/2021, 23/12/2021 e 30/12/2021)

### ISSUE THREAD

**Issue by covid-pt-blogspot-com** [dssg-pt/covid19pt-data#1149]
Há uma repetição dos dados sobre Covid-19 (mais exactamente, nos dados que se recebem da API em https://covid19-api.vost.pt/Requests/get_full_dataset_counties) relativos aos dias 25/11/2021, 23/12/2021 e 30/12/2021. Nessas semanas, os dados dos concelhos aparecem duas vezes mas com algumas diferenças. Por exemplo, há alguns concelhos onde as incidências são diferentes para a mesma data (que aparece 2 vezes). Isso tem efeito em cálculos de variações de uma semana para outra, por exemplo.

**Comment by davipt** [comment]
Got it. Acontece quando a API da DGS é actualizada parcialmente e o nosso script apanha que há alterações mas não percebe se todos os concelhos foram actualizados. Amanhã corrijo manualmente os dados duplicados. Obrigado.

**Comment by davipt** [comment]
Corrigido os três dias com dados duplicados. Se reparares bem, as primeiras linhas (as que foram removidas) têm valores novos para os primeiros valores da lista, e valores iguais à semana anterior para os valores no fim da lista. Sinal que o ficheiro foi actualizado quando a API da DGS ainda estava a meio da actualização.

Obrigado pelo aviso.

**Comment by cptolemy** [comment]
Boa noite,

Espero que todos se encontrem bem.

Gostava de saber, se possível, qual o método - ou script - que usam para
para actualizar a informação do ficheiro *data.csv*, por exemplo, ou se os
dados são manualmente introduzidos a partir do gráfico informativo da DGS.
Ou a API *https://covid19-api.vost.pt <https://covid19-api.vost.pt>* é da
DGS e é daí que os dados são pedidos (assumo que não, porque quando executo
os pedidos os valores não estão actualizados)?

Abraço amigo,

*Rui*


Bruno D. Rodrigues ***@***.***> escreveu no dia segunda,
3/01/2022 à(s) 17:12:

**Comment by davipt** [comment]
Os scripts estão na pasta .github/workflows

O `data.csv` vem da API por trás da dashboard - o URL está neste script [extract_data_arcgis.py](https://github.com/dssg-pt/covid19pt-data/blob/0bbe5bcb5c6b0fdbad5130c94cb97b40e906f6d7/.github/workflows/extract_data_arcgis.py#L37). Esta API tem histórico, mas só utilizamos os dados do último dia.

Os dados de concelhos vêm deste script [extract_dados_concelhos.py](https://github.com/dssg-pt/covid19pt-data/blob/0bbe5bcb5c6b0fdbad5130c94cb97b40e906f6d7/.github/workflows/extract_dados_concelhos.py#L65) e como esta API não tem histórico, guardamos uma cópia da resposta na pasta [extra/concelhos_incidencia/](https://github.com/dssg-pt/covid19pt-data/tree/master/extra/concelhos_incidencia).

A API da VOST expõe os CSV deste repositório e o código está em [dssg-pt/Docker_COVID_API] (https://github.com/dssg-pt/Docker_COVID_API)

Os dados na dashboard (e portanto o `data.csv` e a API) geralmente só estão disponíveis algum tempo após o PDF aparecer no site da DGS e nas redes sociais. A partir do momento em que estão disponiveis na dashboard, são actualizados para aqui no script que corre <strike>todas as horas ao minuto 42</strike> duas vezes por hora aos minutos 12 e 42 [workflow_automation.yml](https://github.com/dssg-pt/covid19pt-data/blob/0bbe5bcb5c6b0fdbad5130c94cb97b40e906f6d7/.github/workflows/workflow_automation.yml#L9)

Hoje, por exemplo, foi actualizado às [16h55](https://github.com/dssg-pt/covid19pt-data/commit/474bc6d297f8362e6fc1404bf15c923b7f5178fd) (o que quer dizer que os "12,42" é só indicativo, e o job corre quando o GitHub tem disponibilidade.

Ajuda?

**Comment by cptolemy** [comment]
Viva,

Ajuda bastante. Muito obrigado. Está de facto muito bem estruturado :)

Abraço amigo,

*Rui*


Bruno D. Rodrigues ***@***.***> escreveu no dia segunda,
3/01/2022 à(s) 20:00:

**Comment by covid-pt-blogspot-com** [comment]
> Corrigido os três dias com dados duplicados. 

OK, obrigado. Continuação de um bom trabalho!
