### ISSUE TITLE
Erros em concelhos nos dados de 28/1/2022

### ISSUE THREAD

**Issue by covid-pt-blogspot-com** [dssg-pt/covid19pt-data#1175]
Esta semana há vários concelhos com erros nos valores (diria a maioria dos que têm uma variação semanal igual a zero nesta imagem: https://blogger.googleusercontent.com/img/a/AVvXsEiIEgfltXx3D6bUGdpJPsAL7cwbV5kZWocV8e7ECxIR_pjZ-LuvoZo9JZgABG46vrvvt06hjQ1X4pMjKZKQp0lmFwH7D_29W5IcU9JSowV3JtYrGhk_RGayLV-wF8Vwnku0afG09HdkkPMlbO60ZMbBnMr205cAluBGTJM_BjT5iSmbpJrKFlbTnmy07g=s2860).

**Comment by davipt** [comment]
https://github.com/dssg-pt/covid19pt-data/commit/34c8935f19ea70db1501065e24f6c4ed996719c2

Refresh aos dados e confirma-me se está tudo ok.

Isto acontece quando estão a actualizar os dados de concelhos na "API" da DGS e o nosso script apanha os dados a meio do update.

**Comment by covid-pt-blogspot-com** [comment]
Sim, parece-me que está resolvido (a nova imagem é a 3ª deste post: https://covid-pt.blogspot.com/2022/01/situacao-covid-19-em-concelhos-e_28.html).

**Comment by davipt** [comment]
Muito bom. Posso sugerir a inversão das cores nos primeiros mapas? Se já estás a usar a temperatura da cor como referência à gravidade - vermelho para subida, azul para descida - porque não o mesmo no mapa de incidência absoluta - pior a vermelho e melhor a branco? Quando vi o mapa fiquei a pensar que a zona do Porto estava melhor que o resto do país, e só depois percebi que piorou valentemente nas últimas semanas. 

Obrigado mais uma vez.

**Comment by covid-pt-blogspot-com** [comment]
> Muito bom. Posso sugerir a inversão das cores nos primeiros mapas? 

Sim, acho que tens razão. O vermelho já está com vários significados (gravidade, Portugal...) naqueles posts porque nem sempre me preocupei o suficiente com a consistência. Como as pessoas já devem estar habituadas a ver daquela forma e porque pode ser que a pandemia não dure muito mais tempo acho que vou manter assim, até ver. Mas obrigado pelo feedback!

**Comment by davipt** [comment]
Sim é verdade. Consistência com os anteriores é mais importante.
