### ISSUE TITLE
Actualização de dados dos boletins 54, 55, 57, 58, 60

### ISSUE THREAD

**Issue by ishouldbedany** [dssg-pt/covid19pt-data#118]
Hoje (7 de Maio), a DGS lançou novas versões dos boletins dos 54, 55, 57, 58 e 60 ([fonte](https://twitter.com/tomahock/status/1258331478389338112)). 

Temos que fazer a actualização retrospectiva destes dados, tanto no `data.csv` como na pasta `dgs-reports-archive`. 

Relatórios disponíveis [aqui](https://covid19.min-saude.pt/relatorio-de-situacao/).

**Comment by EDKLINDEMANN** [comment]
Reparei exclusivamente no dia 28/04/2020:
Total de Casos confirmados, Passa de 24144 para 24141.
Total de Casos Suspeitos, Passa de 238887 para 238884.
ARS Norte Total de Casos confirmados, Passa de 14524 para 14521.

O VOST ainda não verificou o mapa correspondente.

**Comment by ishouldbedany** [comment]
Olá @EDKLINDEMANN, 

Obrigado pela verificação. Estive também a verificar utilizado a ferramenta [Diff Checker](https://www.diffchecker.com/diff) e cheguei à mesma conclusão. 

Adicionalmente, no relatório 60, de 1 de Maio, foram adicionados à tabela com a demografia dos casos confirmados os 10 casos em falta, que já havíamos detectado [aqui](https://github.com/dssg-pt/covid19pt-data/pull/114). 

O _Pull Request_ anexo resolve tudo isto e actualiza os dados e os relatórios.
