### ISSUE TITLE
Ficheiro - data.csv

### ISSUE THREAD

**Issue by hrmartins** [dssg-pt/covid19pt-data#1209]
Olá,

O ficheiro data.csv ainda está a ser atualizado?

Obrigado pelo vosso trabalho.

Hugo

**Comment by davipt** [comment]
Olá.

https://twitter.com/DGSaude/status/1501943389096316933

Dia 10 de Março de 2022 foi o último dia que foi publicado os relatórios PDF díarios de covid e vacinção.

Dia 11 sexta-feira foi publicado um novo relatório PDF semanal comninado. Hoje deverá haver outro. Os dados desse PDF não são suficiente detalhados para serem adicionados aos CSV deste repositório.

Os dados diários disponíveis na API da dashboard original continuaram a ser publicados durante mais uns dias, até dia 13.

Mantêm-se o automatismo para tentar obter esses dados, caso voltem a ser publicados. Idem para os semanais por concelhos. Por exemplo os dados de amostras continuam a ser publicados diáriamente, por isso há sempre uma réstia de esperança.

Ainda assim suspeito que não haverão mais dados detalhados diários.

Obrigado
