### ISSUE TITLE
Scrapper para fazer download de FAQs do ISPUP

### ISSUE THREAD

**Issue by paulomaia20** [dssg-pt/covid19pt-data#13]
O website https://www.covid19portugal.pt/p/1/ tem um conjunto de Perguntas e Respostas atualizadas diariamente.

Tem também um PDF com perguntas e respostas de Mitos, informação sobre a patologia, etc, que são imutáveis, e podem ser transferidos manualmente para um CSV. 

Estes dados podem ser usados eventualmente para projetos de sumarização de notícias/documentos, para criar ferramentas para informar a população (resposta automática a perguntas semelhantes, com fontes científicas validadas - isto é, intent recognition) e para cross-checking de factos.

**Comment by ishouldbedany** [comment]
O próprio site do ministério da Saúde tem um conjunto de FAQs [aqui](https://covid19.min-saude.pt/perguntas-frequentes/)

Acho a iniciativa do ISPUP mais interessnte no sentido em que está aberto a perguntas do público. Pode ser utilizado para chatbots, sites de resposta automática, etc.

**Comment by AnthraxisBR** [comment]
Poderei fazer isso hoje na parte da noite

**Comment by ishouldbedany** [comment]
Este site acabado de lançar pelo Governo pode também ser uma fonte de FAQs: https://covid19estamoson.gov.pt/
