### ISSUE TITLE
Dados incorrectos (data_concelhos.csv) a 16/05/2020 (Santo Tirso/São Brás de Alportel)

### ISSUE THREAD

**Issue by jlbribeiro** [dssg-pt/covid19pt-data#137]
Olá,

Antes de mais dar os parabéns e agradecer pelo excelente trabalho deste repositório!

À semelhança deste projecto, obtenho os meus dados por concelho a partir do dashboard da ESRI Portugal; deparei hoje na minha análise que Santo Tirso passava a reportar 0 casos, enquanto que São Brás de Alportel (que sabia reportar 0 no dia anterior) passou a reportar 378 casos confirmados.

Houve uma "troca" nessas duas linhas, e confirmei que de facto o erro é do dashboard, e não do [relatório de situação de hoje](https://covid19.min-saude.pt/wp-content/uploads/2020/05/75_DGS_boletim_20200516.pdf).

Como sabia que tinham passado recentemente a utilizar a mesma fonte vim confirmar, e de facto [tal se verifica](https://github.com/dssg-pt/covid19pt-data/blob/465c39bd306275d364ead3f1d8e0aa3931766a81/data_concelhos.csv#L55).

Farei um PR de seguida, e muito obrigado mais uma vez! :)

**Comment by paulomaia20** [comment]
Criei um PR agora com a sugestão que deste, de adicionar uma função com fixes manuais para estes pequenos erros. Obrigado pelo report!

**Comment by jlbribeiro** [comment]
@paulomaia20 Já vi o #144, bom trabalho! No entanto há uma incorrecção :disappointed: .
De facto, no dia 16-05-2020 foram reportados 3 casos para São Brás de Alportel, daí ser a primeira vez que foi adicionado ao relatório.

Deveria ser

``` diff
diff --git a/.github/workflows/extract_dados_concelhos.py b/.github/workflows/extract_dados_concelhos.py
index 3a82275..5c6bfc5 100644
--- a/.github/workflows/extract_dados_concelhos.py
+++ b/.github/workflows/extract_dados_concelhos.py
@@ -65,7 +65,7 @@ def patch_concelhos(concelhos):
     
     fix1 = concelhos.data=='16-05-2020'
     concelhos.loc[fix1, 'SANTO TIRSO'] = 378
-    concelhos.loc[fix1, 'SÃO BRÁS DE ALPORTEL'] = np.nan
+    concelhos.loc[fix1, 'SÃO BRÁS DE ALPORTEL'] = 3
 
     return concelhos    
```

**Comment by ishouldbedany** [comment]
@jlbribeiro Aproveitei e fiz a alteração no branch dos dados de hoje, que está agora na fase de CI e deve ser aprovado nos próximos minutos. Obrigado!
