### ISSUE TITLE
Dados de poluição atmosférica

### ISSUE THREAD

**Issue by paulomaia20** [dssg-pt/covid19pt-data#14]
Como um proxy de mobilidade e para perceber isolamento social em dadas regiões, pode ser interessante estudar dados da concentração de poluentes atmosféricos ao longo do dia. 

https://qualar1.apambiente.pt/qualar/index.php

Este site tem dados de 2018 **validados** com a concentração de vários poluentes 

Fazem a medição todos os dias, pelo que podemos tentar contactá-los. 

Em alternativa, diariamente são calculadas algumas features, mas mais agregadas:

https://qualar1.apambiente.pt/qualar/index.php?age=2&day=14&month=3&year=2020&x=8&y=3

**Comment by ishouldbedany** [comment]
É apenas Área Metropolitana de Lisboa, não é?

**Comment by paulomaia20** [comment]
O website tem medições em várias zonas:

https://qualar1.apambiente.pt/qualar/index.php?page=2

O ideal era evitar o trabalho de fazer scraping disto tudo - posso enviar um e-mail a ver se têm uma API.

**Comment by paulomaia20** [comment]
Fechado, por agora. Estamos a trabalhar em outras iniciativas de mini projetos e pode ser que este se enquadre, dependendo das prioridades consideradas pela equipa.
