### ISSUE TITLE
[Mini-projecto] Dados da SICO-eVM (plataforma de vigilância da mortalidade)

### ISSUE THREAD

**Issue by ishouldbedany** [dssg-pt/covid19pt-data#150]
**🤔 Contexto**: 
Os dados de mortalidade têm uma extrema importância para entender o impacto da pandemia do COVID-19 em Portugal. No [Sistema de Informação dos Certificados de Óbito - e-Vigilância de Mortalidade](SICO-eVM - https://evm.min-saude.pt/) são disponibilizados dados sobre a mortalidade em Portugal, mas sem uma estrutura e dicionário de dados associados.

Mais informações disponíveis no issue #48.

**🥅 Objectivo**:
Criar uma pipeline de extração diária de dados do portal SICO-eVM com um dicionário de dados associados.

**👥 Tamanho máximo da equipa**: 3 pessooas

**🎯 Resultado final esperado**: 
Criação de um conjunto de ficheiros `.csv` e dicionários de dados com fontes que os voluntários considerem relevantes para estudos do impacto do COVID-19 na mortalidade em Portugal.

**🧱 Principais etapas**:
- Criar um script para extração de dados para um ficheiro `.csv com dados que considerem relevantes do portal SICO-eVM 
    - Mortalidade Geral, Portugal
    - Mortalidade por região de saúde
    - Óbitos por 100 000 habitantes
    - (...)
-  Criar um dicionário de dados (tabela em Markdown ou ficheiro `.csv`) com o significado de cada variável .
- Criar um script para atualizar diariamente estes dados, com uma lógica semelhante ao que temos feito no repositório (usando o Github Actions).
- Criar um script de teste para testar a validade dos dados e o funcionamento do script, com os testes que considerarem relevantes.
- Incluir os scripts no workflow atual.

--- 

Se estás interessado em pegar neste mini-projecto, diz coisas aqui em baixo ⬇️

**Comment by piresn** [comment]
Olá, gostava de contribuir para este mini-projecto.

**Comment by paulo-jsilva** [comment]
Viva, também gostava de contribuir para este mini-projecto

**Comment by dssgPT** [comment]
Olá @piresn e @paulo-jsilva! Antes de mais, obrigada pelo vosso interesse e disponibilidade! No sentido de agilizar o começo deste mini-projeto, pedimos que nos enviem um e-mail para _hello@dssg.pt_, para ficarmos com o vosso contacto. A partir daí será mais fácil colocar-vos em contacto, esclarecer mais detalhadamente os objetivos do mini-projeto e ajudar-vos com tudo o que seja necessário :) Se eventualmente surgir mais alguém interessado a curto prazo, será integrado na vossa equipa.

**Comment by paulomaia20** [comment]
Divulgamos no Twitter que ainda temos uma vaga para este mini projeto, mas não havendo resposta em breve vamos arrancando (diria para arrancarmos para o início da próxima semana, amanhã envio um e-mail para agilizarmos uma pequena reunião). Já recebemos os vossos contactos :)

**Comment by OldMetalmind** [comment]
Viva, talvez 3 pessoas seja demasiado mas se precisarem de alguém para implementar uma ou outra tasks também posso ajudar. Vou enviar um email então ao hello@dssg.pt

**Comment by paulo-jsilva** [comment]
Viva, 
Concordo com o Filipe. 
Também estou disponível para ajudar noutras tarefas. 
Abraços, 
Paulo 

⁣Get BlueMail for Android ​
