### ISSUE TITLE
[Mini-projecto] Scrapper do link do novo relatório do site da DGS

### ISSUE THREAD

**Issue by ishouldbedany** [dssg-pt/covid19pt-data#151]
**🤔 Contexto**:
De momento, quando sai um novo relatório na página da [DGS] (https://covid19.min-saude.pt/relatorio-de-situacao/), a nossa pipeline de extração de dados funciona da seguinte forma:
-  Criação de um branch com nome `dados_[dia]`.
- Atualização do ficheiro `report_link.txt` com o link do relatório novo.
- Atualização do `README.md` com a última data de atualização.

**🥅 Objectivo**: 
Determinação automática do link do relatório mais recente

**👥 Tamanho máximo da equipa**: 1 pessoa

**🎯 Resultado final esperado**: 
_Script_ que consiga determinar o último relatório publicado pela DGS e atualizar o nosso repositório

**🧱 Principais etapas**:
- Extrair o link do novo relatório **se** for mais recente que os últimos dados que temos no repositório.
- Atualizar o ficheiro `.github/workflows/report_link.txt` com o link do novo relatório.
- Atualizar o ficheiro `README.md` com a data de última atualização.

A criação de um mecanismo automático para tratar disto ficará do nosso lado, pois não é direto termos isto a partir do Github Actions. 

--- 

Se estás interessado em pegar neste mini-projecto, diz coisas aqui em baixo ⬇️

**Comment by guoliveira** [comment]
Bom dia. 
Eu penso que consigo trabalhar neste mini-projecto. 
Até porque já tenho o webscrapper mais ou menos feito.
As minhas questões são as seguintes: 
- Quando vocês dizem isto "Extrair o link do novo relatório se for mais recente que os últimos dados que temos no repositório." estão a dizer que apenas se faz a extração do link se for o link do dia (hoje será o relatório de dia 28/05/2020) e se ainda não foi extraído o link (só se extrai uma vez)? É isso?
- Eu não sei trabalhar bem com o GitHub por isso não sei se consigo salvar no report_link.txt e no README.md.

Cumprimentos

**Comment by ishouldbedany** [comment]
@guoliveira Muito obrigado pela disponibilidade! :tada: 

Alguns esclarecimentos: 

- Sim, a ideia é essa. No nosso ficheiro `data.csv`, na primeira coluna da última linha, temos sempre a data da última actualização. Se o relatório mais recente no site não for mais novo do que essa data, a ideia é não fazer nada. Portanto seria bom o script lidar graciosamente com a inexistência de um relatório mais recente do que aquele que já está no `data.csv`. 

- Acho que não temos necessariamente que trabalhar com ferramentas do GitHub para tal. Eu vejo duas opções: assumindo que o teu scrapper está em Python (que seria o ideal, apesar de sermos flexíveis), obtido o link do novo relatório, pode mexer-se nesses 2 ficheiros directamente a partir do Python; alternativamente, como todo o workflow de actualização dos dados corre numa máquina virtual Linux, creio que também será possível com ferramentas simples do Linux, como o utilitário `sed` (que apesar de parecer confuso é extremamente poderoso e é suportado por muitos recursos online).

Uma nota: idealmente o script estaria, no repositório, em `.github/workflows/` e correria a partir daí. Os scripts Python nessa pasta já têm exemplos de como aceder a ficheiro acima/abaixo na hierarquia de pastas. 

Se estiveres esclarecido e te parecer bem, coloco-te como o responsável deste mini-projecto, pode ser?

**Comment by guoliveira** [comment]
Olá Daniel. 
Sim, escrevi em Python. 
Neste momento a simples função procura o "Relatório de Situação" do corrente dia e devolve um dict com dia e link.

Em relação à analise do ficheiro data.csv seria só acrescentar umas coisas.

Então se há exemplos em Python sobre como aceder aos ficheiro penso que me safo bem :)

Sim posso ficar responsável sim. 
Cumprimentos

**Comment by guoliveira** [comment]
Boa tarde Daniel,
Já tenho  ficheiro .py pronto.

O meu simples script faz:
a) Faz um webscrapping da pagina da DGS e verifica que o "Relatório de Situação" do dia já saiu;
b) Abre o ficheiro data.csv (usei os outros exemplos que mencionaste e penso que funciona bem) e obtém o dia mais recente
c) Se o dia mais recente não for "hoje" e se o relatório de situação de hoje já existir então o script escreve no ficheiro report_link.txt (neste momento ele está em modo "overwrite")

Não percebi bem o que é para escrever no README.md.

Deverei meter o código aqui? Num novo pull request? Ou meto o ficheiro directamento no folder workflow?

**Comment by ishouldbedany** [comment]
Sim, @guoliveira, o ideal é submeter um novo _Pull Request_ com esse script na pasta `.github/workflows`. 

No ficheiro `README.md` seria para actualizar a terceira linha, com a data do momento em que o script estiver a correr. 

Relativamente ao comportamento do _script_, parece-me muito bem, era isso que tínhamos em mente. Muito obrigado! :+1:

**Comment by hbertini-ds** [comment]
Viva, 

 O meu nome é Hugo e agradeço a vossa existência! Não vos conhecia até hoje. Estive a ver os dados que disponibilizam e já estou a preparar um notebook para fazer algumas análises VS as medidas politico-sociais de (des)confinamento para ver que correlações existem.

 Sobre o tópico, por acaso eu iniciei há algum tempo um script em Python para extrair os dados dos pdf da DGS - da situação COVID-19, mas não terminei. 

 O estado do meu script é pouco melhor do que protótipo, mas se acharem útil partilho/demonstro.

Cumprimentos!

**Comment by ishouldbedany** [comment]
Olá @hbertini-ds!

Obrigado pelas palavras simpáticas! Depois de teres as tuas análises prontas, partilha aqui #20, que é onde estamos a aglomerar todas as utilizações do repositório para depois colocarmos no _home_ do repositório e no [nosso website ](http://dssg.pt). 

Sobre o `script`, neste momento também já temos um que faz a extracção e funciona relativamente bem, tendo sido contribuído pela comunidade aqui à volta do repositório. Está [aqui](https://github.com/dssg-pt/covid19pt-data/blob/master/.github/workflows/extract_dataset.py). À vontade para utilizar ou contribuir com melhorias vindas do teu próprio código! 

Este _issue_ aqui refere-se a um outro script, que é para extrair o link do relatório do site (varia todos os dias e o formato não é previsível). Automatiza alguns passos da nossa cadeia diária de actualização. O @guoliveira já contribuiu com uma versão, pelo que neste em específico não será necessária mais ajuda, mas temos mais uns mini-projectos em aberto, [dá uma olhadela](https://github.com/dssg-pt/covid19pt-data/labels/mini-projecto) :eyes:
