### ISSUE TITLE
[Mini-projecto] Dados sobre o impacto no mercado de trabalho

### ISSUE THREAD

**Issue by ishouldbedany** [dssg-pt/covid19pt-data#152]
**🤔 Contexto**:
Um dos maiores impactos do COVID-19 em Portugal tem sido no mercado de trabalho. Como tal, dados relacionados com desemprego, pedidos de _layoff_ ou baixas têm uma extrema importância para melhor entender este impacto, acompanhar e prever a sua evolução. O Ministério do Trabalho, Solidariedade e Segurança Social (MTSSS) disponibiliza estes dados, ao longo do tempo, [num ficheiro .xlsx]( http://www.gep.mtsss.gov.pt/indicadores-covid-19-mtsss).

**🥅 Objectivo**:
Criar uma pipeline de extração diária de dados do ficheiro `.csv` publicado pelo MTSSS com um dicionário de dados associados.

**👥 Tamanho máximo da equipa**: 3 pessoas

**🎯 Resultado final esperado**: 
Criação de um conjunto de ficheiros `.csv` e dicionários de dados com fontes consideradas relevantes para estudos de impacto da COVID-19 no mercado de trabalho em Portugal.

**🧱 Principais etapas**:
- Criar um ficheiro `csv` com dados que considerem relevantes desse ficheiro, tais como:
    - Baixas por isolamento.
    - Pedidos de layoff.
    - Despedimentos.
    - Criar um dicionário de dados (tabela em Markdown ou ficheiro .`csv`) com o significado de cada variável.
- Criar um script para atualizar diariamente estes dados extraindo-os da plataforma, com uma lógica semelhante ao que temos feito no repositório (usando o Github Actions).
- Criar um script de teste para testar a validade dos dados e o funcionamento do script, com os testes considerados relevantes.
- Incluir os scripts no workflow atual.

--- 

Se estás interessado em pegar neste mini-projecto, diz coisas aqui em baixo ⬇️

**Comment by jbricenot** [comment]
Ola, ha pouco terminei um curso de data science. Nao tenho muita experiencia, mas tenho muita vontade de aprender e ajudar o maximo possivel com o projecto.

**Comment by marianabvsg** [comment]
Olá! Penso que tenho competências para este projeto e gostava de ajudar!

**Comment by dssgPT** [comment]
Olá @jbricenot e @marianabvsg :) Antes de mais, obrigada pelo vosso interesse e disponibilidade! No sentido de agilizar o começo deste mini-projeto, pedimos que nos enviem um e-mail para _hello@dssg.pt_, para ficarmos com o vosso contacto. A partir daí será mais fácil colocar-vos em contacto, esclarecer mais detalhadamente os objetivos do mini-projeto e ajudar-vos com tudo o que seja necessário :)

**Comment by japana26** [comment]
Olá! Eu gostaria de ajudar com este projecto. Tirei recentemente um curso de análise de dados com python e já tenho alguma experiência em projectos. :)

**Comment by dssgPT** [comment]
Olá @japana26, obrigada pela disponibilidade! Chegaste na altura certa para completarmos a equipa! Como explicado acima, pedimos que envies um e-mail para _hello@dssg.pt_ para ficarmos com o teu contacto e avançarmos!
