### ISSUE TITLE
[Mini-projecto] Tweet automático com a actualização de dados

### ISSUE THREAD

**Issue by ishouldbedany** [dssg-pt/covid19pt-data#153]
**🤔 Contexto**:
Todos os dias actualizamos os dados e gostamos de informar quem nos segue nas redes sociais acerca disso, para que pessoas que dependem dos dados do repositório possam ficar a par e actualizar as suas análises/scripts/projectos pessoais. O Twitter é uma rede social que concentra muita dessa audiência, pelo que privilegiamos a divulgação aí.

**🥅 Objectivo**:
Enviar automaticamente um tweet após a actualização diária dos dados, informando da mesma e possivelmente incluindo alguns dados estatísticos simples.

**👥 Tamanho máximo da equipa**: 1-2 pessoas

**🎯 Resultado final esperado**: 
Uma GitHub Action que possa ser integrada no nosso repositório e automaticamente executada após a integração dos dados diários no _branch_ principal.

**🧱 Principais etapas**:
- Desenvolver um script (idealmente ecossistema Python):
    - Autentique na nossa conta Twitter (iremos partilhar as credenciais através de um método seguro, como _secrets_ do repositório).
   - Leia o ficheiro `data.csv` e dele extraia os principais indicadores do dados de hoje relativamente ao dia anterior (aumentos absolutos e em percentagem do número de infectados, óbitos, recuperados, internados e internados em UCI).
    - Componha um tweet belo e objectivo com estes dados e o envie.
- Integrar este ficheiro numa _Action_ do GitHub, que corra de forma robusta cada vez que é feito o merge de um _branch_ com nome `dados-` para o branch `master`. 

--- 

Se estás interessado em pegar neste mini-projecto, diz coisas aqui em baixo ⬇️

**Comment by ishouldbedany** [comment]
@hmgfaria

**Comment by hmgfaria** [comment]
Eu ajudo nisto 😉
