### ISSUE TITLE
[Mini-projecto] Análise de sentimento ao longo do período pandémico

### ISSUE THREAD

**Issue by ishouldbedany** [dssg-pt/covid19pt-data#154]
**🤔 Contexto**:
O estado emocional da população tem uma elevada influência na forma como as pessoas reagem às medidas que são impostas e, consequentemente, no sucesso das mesmas. Neste contexto, torna-se relevante avaliar a evolução dos sentimentos mais preponderantes entre a população portuguesa ao longo da pandemia, através da análise de notícias ou de publicações nas redes sociais. 

**🥅 Objectivo**:
Analisar a evolução dos sentimentos mais preponderantes entre a população portuguesa durante o período da pandemia e relacioná-los com a implementação e levantamento de medidas governamentais.

**👥 Tamanho máximo da equipa**: 3 pessoas

**🎯 Resultado final esperado**: 
Criação de uma _timeline_ visual que reflita o estado emocional da população portuguesa ao longo do período pandémico e integre informação das medidas que mais poderão ter contribuído para esse estado.

**🧱 Principais etapas**:
- Seleção de fontes relevantes de dados para análise de sentimentos da população portuguesa (como por exemplo, os dados do nosso repositório das notícias do jornal Observador/Público, ou dados extraídos do Twitter).
- Listagem de implementação e levantamento de medidas governamentais ao longo do tempo.
- Desenvolvimento/utilização de algoritmos pré-existentes (_e.g._ `NLTK`/`spaCy` em Português) para classificação em termos de sentimentos positivos/negativos (ou numa gama entre eles), com base em texto proveniente das fontes escolhidas;
- Apresentação dos resultados através de visualizações pertinentes e explícitas.

--- 

Se estás interessado em pegar neste mini-projecto, diz coisas aqui em baixo ⬇️

**Comment by anafrs** [comment]
Olá, estou interessada em participar neste projeto :) Sou recém graduada da Ironhack (data analytics) e desenvolvi alguns projetos de NLP, usando NLTK (mas em Inglês).  Obrigada

**Comment by ruijpbastos** [comment]
Boas, tenho alguma experiência a trabalhar como Data Scientist, e tenho interesse em participar neste projecto!

**Comment by joaoalmeida225** [comment]
Boa tarde, também tenho alguma experiência em projetos do género e gostaria de contribuir. Obrigado!

**Comment by dssgPT** [comment]
Olá @anafrs @ruijpbastos e @joaoalmeida225 ! Antes de mais, obrigada pelo vosso interesse e disponibilidade! No sentido de agilizar o começo deste mini-projeto, pedimos que nos enviem um e-mail para hello@dssg.pt, para ficarmos com o vosso contacto. A partir daí será mais fácil colocar-vos em contacto, preparar um repositório e ajudar-vos com tudo o que seja necessário :)
