### ISSUE TITLE
missing values - NaN vs Empty values

### ISSUE THREAD

**Issue by chaaaarlie** [dssg-pt/covid19pt-data#16]
any reason to have "NaN" instead of empty values ? 

I think it's simpler to handle the latter on most softwares/packages. would suggest to replace it

**Comment by ishouldbedany** [comment]
Hi @chaaaarlie , thanks for the feedback!

So, Pandas on Python correctly parses those values as a NaN. Do you have experience with other software/package that do not handle this so well? If that's the case, no problem in changing - the only drawback would be some loss of clarity for people doing analyses on Excel or reading the CSV. Empty is sometimes confusing.

**Comment by chaaaarlie** [comment]
reading the CSV would be fine since we have empty values.

the only example I have is with Tableau that read the file but assumed the data type was string for columns with NaN.

**Comment by ishouldbedany** [comment]
@chaaaarlie Makes sense. It probably won't any problems regarding retrocompatibility, as most packages deal equally well with empty data or NaN. Will do it, thanks for the sugestion! :)
