### ISSUE TITLE
Alerta/Webhooks de novos dados disponíveis

### ISSUE THREAD

**Issue by OldMetalmind** [dssg-pt/covid19pt-data#166]
Gostava iniciar uma conversa sobre como seria preferível implementar uma forma de divulgação que existem novos dados disponíveis.

Reparei que este projecto tem _Github Actions_ a serem executados assim que há novos "merges". Seria interessante também, de certos projectos poderem ser notificados de que há novo conteúdo, à semelhança do Mini Projecto de publicar os novos dados no Twitter #153 .

Um caso de uso seria o lançamento da notificação de novos casos da aplicação EstamosOn.

**Comment by ishouldbedany** [comment]
@OldMetalmind Parece-me uma excelente ideia. Efectivamente o do Twitter era o primeiro passo, mas queremos expandir isto. Não tenho experiência com a tecnologia (não sei se alguém aqui da equipa @dssg-pt/lead-team tem): dá para fazer directamente através do GitHub (alerta sempre que acontece um MR dentro de determinados critérios) ou é necessário um outro serviço?

**Comment by tiagoad** [comment]
Para o meu projeto estou a usar o feed de RSS do github no integromat. Uso este link https://github.com/dssg-pt/covid19pt-data/commits/master/data.csv.atom
