### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by hrmartins** [dssg-pt/covid19pt-data#167]
Bom dia,

Os dados não foram atualizados ontem, correto?

Obrigado pelo trabalho realizado.
Hugo

**Comment by ishouldbedany** [comment]
@hrmartins Certíssimo e desde já pedimos desculpa. Ontem houve uma mudança no formato do PDF lançado pela DGS e a nossa equipa só conseguiu actualizar o script de extracção ao fim do dia. 

Entretanto os dados relativos a ontem acabaram agora mesmo de dar entrada no repositório. Obrigado pela atenção!
