### ISSUE TITLE
Clarificar raw data vs medidas calculadas

### ISSUE THREAD

**Issue by henriquetguedes** [dssg-pt/covid19pt-data#17]
no data.csv,  a variável 'transmissao-comunitaria' terá sido calculada com base em outras variáveis. Não havendo clarificação precisa para este termo, não sendo imediata a licitude deste cálculo, e não sendo um dado em bruto fornecido pela DGS, seria interessante alterar o nome da variável de forma a explicitar que é um resultado de duas medidas recolhidas, e que pode não corresponder a uma medida correcta em terminologia de Saúde Pública.

**Comment by ishouldbedany** [comment]
Olá Henrique. Nenhum de nós tem um background clínico, daí poder existir este tipo de incoerências - agradecemos imenso a correcção.

 A linha de pensamento na transmissão comunitária foi `transmissão-comunitària` = `casos-confirmados`-`casos-importados`. Após mais pesquisa, percebemos que existe um outro tipo de transmissão, a local, o que compromete toda a validade desta análise. 

Podes confirmar esta questão, de um ponto de vista de Saúde Pública?

A ser verdade, a solução poderá ser eliminar a coluna de transmissão comunitária ou então renomeá-la para algo como `transmissão-n-importada` (ou algo melhor, caso exista algum termo epidemiológico para tal). 

De qualquer das formas, vamos esclarecer no README.md tudo o que são medidas calculadas.

**Comment by henriquetguedes** [comment]
A transmissão comunitária é quando a transmissão ocorre por fontes não identificadas, sem que haja contactos conhecidos com outras pessoas que já se sabe que estão doentes, ou seja, exclui os não-importados que já são de cadeias de transmissão conhecidas (aquilo que seria a transmissão local).

Como não sabemos quantos indivíduos alberga cada uma das cadeias conhecidas, creio que seria melhor mesmo eliminar a coluna, até porque é calculável facilmente e não apresenta nenhuma informação imediatamente relevante.

Obrigado pela abertura!

**Comment by ishouldbedany** [comment]
@henriquetguedes Já vai ficar corrigido muito brevemente, é só o Pull Request associado ser revisto por alguém da equipa.

Obrigado nós!, que não sendo da área clínica queremos manter o maior rigor possível e contamos com a ajuda da comunidade. Para efeitos de registo, fica aqui o meu entendimento (e corrige-me alguma imprecisão): 

+ **transmissão importada**: como o nome indica, casos importados de cadeias de contágio activas noutros países e que entraram no nosso país. 
+ **transmissão local**: transmissão por contacto com alguém já parte de uma cadeia de transmissão conhecida e bem-caracterizada (cadeia essa que pode ou não ter origem numa transmissão importada).
+ **transmissão comunitária**: transmissão por fontes não-identificadas, em que o paciente não tem contactos aparente com nenhum membro activo das cadeias de transmissão já conhecidas. O _worst case scenario_, diria.

**Comment by henriquetguedes** [comment]
precisamente. há um ponto de sobrecarga em que deixa de ser possível separar ou sequer estabelecer cadeias. 
obrigado pela alteração.
