### ISSUE TITLE
 Internados e UCI para 5 Juno não é consistente para DGS

### ISSUE THREAD

**Issue by rob-kineviz** [dssg-pt/covid19pt-data#172]
Dados para 05/06/2020 - DGS (mostrado 06/06/2020 16h13 https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/):
- Internados: 421
- UCI: 58

Mas aqui:
- Internados: 475
- UCI: 64

Esses números mais importante nest momento - mudaram?

**Comment by ishouldbedany** [comment]
Olá @rob-kineviz, 

Efectivamente houve uma actualização dos dados de ontem após a nossa extracção diária. Já corrigimos e actualizamos o arquivo do boletim. Entrará no repositório após a aprovação da actualização de dados de hoje (#173, que requer apenas aprovação por um segundo membro da nossa equipa antes de ser integrada). 

Obrigado pela atenção! :monocle_face:
