### ISSUE TITLE
README.md: use `*_arsalentejo` not `*_alentejo`

### ISSUE THREAD

**Issue by saghirb** [dssg-pt/covid19pt-data#181]
In the "Dicionário dos dados" section of the README.md file "Nome da colunas" ending in `*_alentejo` should be `*_arsalentejo`. 

If you agree I can issue a pull request (or you can correct it yourself).

Thanks,
Saghir

**Comment by ishouldbedany** [comment]
Hi @saghirb! 

Thanks for your attention to detail. 

As it is such a small change, I have fixed it on 1d21959d91474254211b4edacf2f4bf3bff0c4a7 and I'm therefore closing.
