### ISSUE TITLE
Dados de casos recuperados por região quase vazios

### ISSUE THREAD

**Issue by filipeataide** [dssg-pt/covid19pt-data#182]
Os dados de recuperados por região encontra-se quase todo vazio, nao sendo possivel fazer calculos de casos activos por região. Será que conseguimos resolver?

**Comment by ishouldbedany** [comment]
Olá @filipeataide,

A DGS apenas disponibilizou dados de recuperados com granularidade ao nível da Região de Saúde num período muito limitado no tempo, tendo desde aí só disponibilizado o valor total do país. Desde que foi tomada essa decisão, temos preenchido com "vazio" apenas por questões de formatação. 

Alguns municípios e até Áreas de Saúde, essencialmente nas suas redes sociais, vão disponibilizando estes dados, mas nunca de modo muito regular ou estruturado. 

Creio que é uma daquelas situações em que _"não se fazem omeletes sem ovos"_ :egg:. Espero que o esclarecimento seja útil.

**Comment by filipeataide** [comment]
Obrigado, não tinha ideia e sendo assim está tudo esclarecido. Abraço e continuação de bom trabalho!
