### ISSUE TITLE
Dados errados no ficheiro data_concelhos.csv

### ISSUE THREAD

**Issue by chegancasb** [dssg-pt/covid19pt-data#190]
Bom dia,

o ficheiro data_concelhos.csv apresenta o valor 5.5 para o concelho de Penacova no dia 2 de Abril.

Provavelmente um erro de processamento dos dados desse dia que persiste. É possível corrigi-lo?

Obrigado desde já.

Cumprimentos,
Bruno

**Comment by ishouldbedany** [comment]
@paulomaia20 Podes dar uma olhadela rápida e perceber se houve problema do nosso lado ou se já vinha assim da DGS/ArcGIS?

**Comment by hbertini-ds** [comment]
Viva, reparei também que os dados de Beja, de 12 para 13 de Junho passam de 23 para 22. Vou analisar o ficheiro para ver se este tipo de situação ocorre em mais alguma parte do csv.

Por outro lado, reparei que os dados do Porto e outros concelhos "estagnaram" a partir de dia 6 de Junho. Vou confirmar "humanamente".

Cumprimentos,
Hugo

**Comment by paulomaia20** [comment]
Em princípio será da fonte, não faço assim nenhuma operação complexa que me passe números para não inteiros. O script fundamentalmente aplica uma pivot table aos dados para passar as freguesias para colunas.

Vou também avaliar e corrigir este fim de semana :)  O processo do lado deles é completamente manual, a partir do boletim, pode haver alguma gralha.

**Comment by hbertini-ds** [comment]
Estive a ver e há muitos registos onde isto acontece. 
Então penso recordar que, por vezes os resultados são ajustados retroactivamente, consoante diagnósticos posteriores ao caso ter sido assinalado, quando cada situação já tenha sido alvo de melhor avaliação. 

Coloquei em anexo um ficheiro com o output da minha verificação.
[dados_nao_cumulativos.txt](https://github.com/dssg-pt/covid19pt-data/files/4806645/dados_nao_cumulativos.txt)

**Comment by AlfredoBB** [comment]
That can happen if they report suspected cases and positive cases; and the following day the suspected cases are negative.

**Comment by JBacelarPT** [comment]
Boas, não sei se já repararam, mas os dados de 4, 5 e 6 de julho são exatamente os mesmos.

**Comment by ishouldbedany** [comment]
@JBacelarPT Apesar dos nossos dados de concelhos serem extraídos de uma outra fonte (dashboard no site COVID-19 da DGS), penso que estarão sujeitos aos mesmos condicionamentos que os do boletim, onde a DGS inclui o seguinte aviso: 

![image](https://user-images.githubusercontent.com/6266595/86845078-df303400-c0a0-11ea-8686-5c3b243a67ee.png)

(imagem do boletim de hoje)

Portanto, creio que nos resta... esperar :hourglass: :man_shrugging:

**Comment by JBacelarPT** [comment]
Eu estive afastado por uns dias e não acompanhei a coisa, não me tendo apercebido da nota da DGS. Faz todo o sentido que a dashboard tenha os mesmos constrangimentos.
Obrigado pela resposta!

**Comment by JorgeMiguelGomes** [comment]
As this is issue is not closed, I would ask @ishouldbedany or @paulomaia20 to check the data that is being returned for council "ALVITO. Very abnormal numbers that, in my opinion, belong to "AMADORA". 
<img width="653" alt="Screenshot 2020-10-16 at 12 54 50" src="https://user-images.githubusercontent.com/34355337/96255501-ed022900-0fae-11eb-9c38-8f9203d110f6.png">

**I only noticed this when trying to do a table that shows the evolution of confirmed cases by percentage of estimated population living in the council.**

**Comment by davipt** [comment]
Parece-me haver três situações diferentes neste ticket.

1. dados com floats (5.5). Vou verificar os valores que não sejam inteiros, e mudar o csv para retornar apenas inteiros. Não há meio infetados. Se houver um dia ou outro com um concelho ou outro que faça sentido meter um hack manualmente, para consistência, há um local no código para isso. Para que fique claro, os dados estarão incorrectos na fonte oficial da ERSI e na dashboard, mas se puder-se corrigir neste csv, pode-se tentar.

2. dados em falta quando deixaram de actualizar os dados temporariamente, e depois passaram a actualizar apenas semanalmente. Isto está resolvido.

3. Jorge, por favor verifica o teu código. Os dados de Alvito estão todos a NaN.

Relembro as palavras do Paulo Maia, parafraseando, o dados_concelho.csv é recriado totalmente todas as semanas e poderá ter alterações em dados históricos caso sejam alterados na API da ERSI.

**Comment by davipt** [comment]
https://github.com/dssg-pt/covid19pt-data/pull/353 can close this

**Comment by davipt** [comment]
@chegancasb podes confirmar sff e fechar este ticket se estiver ok? Obrigado

**Comment by chegancasb** [comment]
Oi,
Confirmo que na última listagem já não surgem entradas com valores decimais.

Cumprimentos,
Bruno
