### ISSUE TITLE
Correção dados 2020-06-20 

### ISSUE THREAD

**Issue by davipt** [dssg-pt/covid19pt-data#196]
Saiu documento actualizado https://covid19.min-saude.pt/wp-content/uploads/2020/06/110_DGS_boletim_20200620-1.pdf e o parsing pelo menos dos concelhos foi feito no primeiro documento https://covid19.min-saude.pt/wp-content/uploads/2020/06/110_DGS_boletim_20200620.pdf o que mostra vários concelhos com menos casos que antes, e.g. Loulé com 7 em vez de 76 e Porto com 1363.0 em vez de 1414.0.

Sera possível reprocessar o dia de ontem (20) ao mesmo tempo que se actualiza o dia de hoje (21)? Obrigado.

**Comment by ishouldbedany** [comment]
@davipt A nossa fonte de dados para os concelhos é um _endpoint_ da ArcGIS e vamos buscar sempre todos os dados, pelo que creio que quando estiver corrigido da parte deles também o repositório, numa das suas actualizações, reflectirá essa alteração (estou certo, @paulomaia20?). 

Do que li, a única mudança nos números aconteceu ao nível dos concelhos, e não é do PDF que extraíamos esses dados. Quando ao documento em si, teremos que substituir manualmente. Em princípio na actualização de amanhã garantiremos isso.
