### ISSUE TITLE
Ficheiros PDF com nomes "estranhos"

### ISSUE THREAD

**Issue by davipt** [dssg-pt/covid19pt-data#197]
Ao fazer um git clone limpo em macOS, os ficheiros dos PDF dentro de dgs-reports-archive ficam marcados como "ficheiros novos" pois o encoding dos acentos está no formato por exemplo "letra o combinada com acento agudo" em vez de "ó" 

idavi:covid19pt-data bruno$ echo Relatório | hexdump -C
00000000  52 65 6c 61 74 6f cc 81  72 69 6f 0a              |Relato..rio.|
0000000c

6f cc 81
http://www.fileformat.info/info/unicode/char/0301/index.htm

idavi:covid19pt-data bruno$ echo Relatório | hexdump -C
00000000  52 65 6c 61 74 c3 b3 72  69 6f 0a                 |Relat..rio.|
0000000b

 c3 b3
https://www.fileformat.info/info/unicode/char/00f3/index.htm

Este encoding vem do python process_report que faz rename do ficheiro original para este nome com os códigos unicode "letra combined com acento":

(.venv) idavi:covid19pt-data bruno$ cat .github/workflows/process_report.py | grep Rela | hexdump -C
00000000  20 20 20 20 6e 65 77 5f  6e 61 6d 65 20 3d 20 22  |    new_name = "|
00000010  52 65 6c 61 74 6f cc 81  72 69 6f 2d 64 65 2d 53  |Relato..rio-de-S|
00000020  69 74 75 61 63 cc a7 61  cc 83 6f 2d 7b 3a 30 32  |ituac..a..o-{:02|
00000030  64 7d 5f 7b 3a 30 32 64  7d 5f 7b 3a 30 32 64 7d  |d}_{:02d}_{:02d}|

Posso fazer um PR que faça rename aos ficheiros para UTF8 mais limpo e altere aquela string no python?

**Comment by ishouldbedany** [comment]
@davipt Uma delicadeza bem apanhada, vai umas camadas abaixo da minha técnica de Python (por acaso fui eu que escrevi a versão original desse script e nunca sequer me passou pela cabeça esse detalhe). Claro, é bem-vindo! Podes só garantir que o nome de todos os ficheiros já existente é também alterado?

Obrigado!

**Comment by davipt** [comment]
Não consegui ligar o PR com a issue… https://github.com/dssg-pt/covid19pt-data/pull/198

O merge de ontem do "auto tweet" já tinha feito a correção da maioria dos PDFs (basta fazer add do nome com unicode "normal", e o git percebe que é o mesmo ficheiro e corrige o nome interno), faltando apenas o update de ontem, que está neste PR, assim como a alteração no python, e um caracter (apenas um em muitos) no csv.
