### ISSUE TITLE
Adicionar shapefiles para as regiões

### ISSUE THREAD

**Issue by paulomaia20** [dssg-pt/covid19pt-data#2]
Encontrar ou construir shapefiles para as diferentes regiões do país:

- ARS Norte
- ARS Centro
- ARS Lisboa e Vale do Tejo
- ARS Alentejo
 - ARS Algarve
- Região Autónoma dos Açores
- Região Autónoma da Madeira 

Isto é compatível com a nomenclatura NUTS II das regiões de Portugal:

https://en.wikipedia.org/wiki/NUTS_statistical_regions_of_Portugal

**Comment by joaopalmeiro** [comment]
Olá!

Com base no shapefile dos concelhos, penso que consegui criar um primeiro shapefile para as diferentes regiões/[CCDR](https://pt.wikipedia.org/wiki/Comiss%C3%A3o_de_Coordena%C3%A7%C3%A3o_e_Desenvolvimento_Regional)’s semelhante ao que está a ser utilizado [aqui](https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/) pela DGS (sem os Açores e a Madeira por enquanto). 

O código e o shapefile encontram-se neste [repositório](https://github.com/joaopalmeiro/portugal-maps). Vou verificar novamente se está tudo okay com a geração do shapefile e adicionar alguma documentação.

O que acham?

**Comment by ishouldbedany** [comment]
@joaopalmeiro Muito, muito obrigado! Agradecemos mesmo a ajuda e as contribuições :+1: 

Relativamente aos Açores/Madeira, este [site](http://forest-gis.com/2012/01/portugal-shapefiles-gerais-do-pais.html/), na secção das _Unidades administrativas de Portgual GADM_, tem disponível para download um _shapefile_  das NUTS I, que são basicamente Portugal Continente e as Ilhas. Achas que dará para extrair Açores e Madeira daí?

Se conseguires, poderias fazer um _pull request_ com os shpafiles finais e um exemplo atómico para os carregar e visualizar? Teríamos todo o gosto que esta fosse a nossa primeira contribuição externa :smiley:

**Comment by joaopalmeiro** [comment]
Aproveitei o mesmo shapefile dos [concelhos](https://dados.gov.pt/pt/datasets/concelhos-de-portugal/) e "adicionei" os Açores e Madeira, cada um como uma "região" (cada região/CCDR colorida com uma cor aleatória, quer para o caso de Portugal, quer para o caso de Portugal Continental). O que acham?

![ccdr_azores_madeira](https://user-images.githubusercontent.com/17132927/76899745-0f548c80-6890-11ea-875e-789bb0764d13.png)
![ccdr](https://user-images.githubusercontent.com/17132927/76899748-1085b980-6890-11ea-915b-8646a5b683bd.png)

Btw, @ishouldbedany , qual é a tua ideia para o "exemplo atómico"? Um notebook, em Python, onde carrego o ficheiro e faço uma visualização de exemplo com os dados deste repositório, por exemplo?

**Comment by paulomaia20** [comment]
Muito fixe! Diria que podemos avançar mesmo com essa pequena inconsistência @joaopalmeiro :) Dá para ter noção geral da evolução por região NUTS II. 

Sim, pediamos-te só, antes de fazeres o pull request, para fazeres um exemplo de um notebook para abrir esses shapefiles, e se conseguires, colocar um heatmap em função dos valores das contagens existentes nessas regiões. Alternativamente, podemos tratar nós disso :)

**Comment by joaopalmeiro** [comment]
Em termos de organização, coloco os shapefiles na pasta "extra" e o notebook na pasta "notebooks"?

**Comment by paulomaia20** [comment]
Sim - provavelmente vamos reformular algumas coisas em termos de organização, à medida que isto escalar, mas podes colocar aí :) 

Para já tenho um notebook exemplo na pasta extra/noticias mas estou a pensar movê-lo para a pasta dos notebooks

**Comment by joaopalmeiro** [comment]
Já fiz o PR com o tutorial e os mapas — caso tenham algum feedback, partilhem, por favor! 😄

**Comment by Pacjeco** [comment]
Poderiam partilhar o Shapefile de Portugal Continental e das Regiões Autónomas?
