### ISSUE TITLE
Dados de 3 e 4 Julho

### ISSUE THREAD

**Issue by EDKLINDEMANN** [dssg-pt/covid19pt-data#217]
Ora viva a todos

Estão com algum problema no processamento dos dados para o data.csv?

Abraco

EKL

**Comment by paulomaia20** [comment]
Olá @EDKLINDEMANN,

Efetivamente estamos com problemas, uma vez que a DGS retirou a tabela da página 2, dos casos confirmados estratificados por género e idade. Aguardamos até hoje para ver se voltavam a incluir esses dados, mas aparentemente não (e sem justificação, que tenhamos encontrado).

**Comment by paulomaia20** [comment]
Atualizados

**Comment by EDKLINDEMANN** [comment]
Boas @paulomaia20 

Realmente nem tinha reparado.... Obrigado pela correcão. Good job mate!
