### ISSUE TITLE
Dados dos concelhos de dia 3 de julho em falta

### ISSUE THREAD

**Issue by paulomaia20** [dssg-pt/covid19pt-data#221]
Estão em falta os dados dos concelhos para o dia 3 de Julho, que são extraídos diretamente do dashboard da ESRIportugal.

**Comment by ishouldbedany** [comment]
Hoje, dia 5 de Julho, estes dados continuam a não estar disponíveis.

**Comment by ishouldbedany** [comment]
Os dados para os concelhos relativos a 3 de Julho voltaram hoje e foram integrados na 3fd392322dd62e81e61ef03a1622934ac808ecb1.
