### ISSUE TITLE
Dados em falta

### ISSUE THREAD

**Issue by OldMetalmind** [dssg-pt/covid19pt-data#222]
Não existem dados para os últimos dias para: 
> Número de confirmados por grupo de idades em falta, já nos passados 2 dias
> Número de confirmados_f e confirmados_m

Datas:
> 03-07-2020
> 04-07-2020

Campos em falta:
confirmados_0_9_f	confirmados_0_9_m	confirmados_10_19_f	confirmados_10_19_m	confirmados_20_29_f	confirmados_20_29_m	confirmados_30_39_f	confirmados_30_39_m	confirmados_40_49_f	confirmados_40_49_m	confirmados_50_59_f	confirmados_50_59_m	confirmados_60_69_f	confirmados_60_69_m	confirmados_70_79_f	confirmados_70_79_m	confirmados_80_plus_f	confirmados_80_plus_m
confirmados_f      confirmados_m

Nota:
Também notei valores abnormais de "dados de importação" campo: transmissao_importada

**Comment by davipt** [comment]
No Twitter dizem que estão à procura dos tais 200 casos dos privados e por isso não estão a publicar os confirmados por faixas etárias, e até os dados por concelho (no PDF) parece ser os mesmos valores que ontem. É ver amanhã na conferência o que dirão sobre o assunto.

**Comment by ishouldbedany** [comment]
Sim, neste momento estamos a importar todas as inconsistências e lacunas da DGS no que toca à caracterização demográfica. Estamos à espera que a situação regularize minimamente, mas estas mudanças súbitas quebraram os nossos automatismos e fomos forçados a programar à volta delas.

Os nossos dados dos concelhos não são extraídos do PDF, mas sim da [dashboard ArcGIS disponível aqui](https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/). Notamos que, por exemplo, por alguma razão não existem dados para o dia 3 de Julho. Esperemos que seja regularizado no início da semana. 

Tens razão relativamamente à transmissão importada, @OldMetalmind. Um artefacto resultante de andarmos a martelar para lidar com estas mudanças súbitas. Vou corrigir. Tudo o resto... omeletes sem ovos, receio.

**Comment by ishouldbedany** [comment]
O 82cff150c421c986021b7b82d3b8ef013459682a resolve a questão dos números da transmissão importada nos últimos dias. Vou deixar esta _issue_ aberta para as restantes questões.
