### ISSUE TITLE
Actualizar todos os dados e relatórios desde 30 de Junho (inclusive)

### ISSUE THREAD

**Issue by ishouldbedany** [dssg-pt/covid19pt-data#237]
Conforme a nota no relatório 131 de 30 de Junho: 

![image](https://user-images.githubusercontent.com/6266595/87310178-84ba2c00-c515-11ea-9324-6afda49b68b1.png)

Para além de **alteração nos números em todos os dias desde 30 de Junho**, estamos também perante a **adição das caracterizações demográficas** entre os dias 3 e 10 de Julho, que estavam em falta.

 Falamos portanto de reprocessar todos os últimos 14 dias de dados do `data.csv`, assim como os ficheiros associados.

**Comment by davipt** [comment]
Seria possível também recalcular os dados de concelhos, assumindo que a dashboard da DGS foi actualizada?

**Comment by ishouldbedany** [comment]
> Seria possível também recalcular os dados de concelhos, assumindo que a dashboard da DGS foi actualizada? Obrigado.

@davipt Salvo erro, todos os dias aquando da actualização vamos buscar todos os dados com mudanças (correcto @paulomaia20?) Se a DGS fizer essa alteração na dashboard, ela eventualmente será apanhada pela nossa extracção.

**Comment by davipt** [comment]
Correcto. Estou agora a olhar para o código e confirmo que todos os dados são sacados da API e o ficheiro é recriado.

A API é que não devolve dados novos desde dia 6 de Julho :(

Obrigado
