### ISSUE TITLE
Falta informação sobre Casos Importados

### ISSUE THREAD

**Issue by teresalazar13** [dssg-pt/covid19pt-data#24]
No https://github.com/dssg-pt/covid19pt-data/blob/master/data.csv falta informação sobre casos importados. Pode ser obtida através dos relatórios da DGS presentes em:
https://github.com/dssg-pt/covid19pt-data/blob/master/dgs-reports-archive

Posso ajudar com isto?

**Comment by ishouldbedany** [comment]
Olá @teresalazar13, obrigado pelo _feedback_!

Neste momento estamos apenas a contabilizar o total de casos importados na coluna `transmissao_importada`. Estás a referir-te a adicionar uma coluna por país?

**Comment by teresalazar13** [comment]
Sim, exatamente

**Comment by ishouldbedany** [comment]
Força, @teresalazar13 

A minha única sugestão seria usar algum tipo de norma para identificar os países. Uma pesquisa rápida levou-me à [ISO 3166](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes).

**Comment by teresalazar13** [comment]
Tem algum codigo base de onde retiram a informaçao por onde eu possa começar?

**Comment by teresalazar13** [comment]
Os dados sao extraidos manualmente, ou através de data mining (e automaticamente) a partir dos documentos da DGS?

**Comment by ishouldbedany** [comment]
Neste momento estamos a extrair manualmente, porque verificamos que a volatilidade no formato dos relatórios não compensava o desenvolvimento de ferramentas mais automatizadas de extracção de dados/OCR dos PDFs/dashboards.

**Comment by teresalazar13** [comment]
Muito obrigada pela informação e parabéns pelo excelente trabalho :)

**Comment by teresalazar13** [comment]
Criei um script que extrai dados automaticamente a partir dos relatórios. É válido para relatórios a partir de dia 20 e, se o formato dos relatórios se mantiver constante funcionará para o resto dos dias.

No entanto não tenho push request. Como devo proceder?

**Comment by teresalazar13** [comment]
Penso que também está um valor incorreto na coluna "confirmados_70_79_f" do dia 20. Em vez de 36, deveria ser 35.

**Comment by ishouldbedany** [comment]
@teresalazar13 Obrigado pela correcção nos dados do dia 20 de Março. Efectivamente, seguindo o boletim, o somatório das faixas etárias/género difere do total de casos para esse dia e devemos ter feito uma correcção. É preferível manter o erro, por fiabilidade aos dados lançados pela DGS. Corrigido em fab5280b5913356cd6ee37be3c02bf8732ad2a16.

Relativamente ao script, muito obrigado! Ele só extrai informação da secção dos casos importados ou de todo o boletim? Idealmente, quando o formato do boletim estabilizasse, a nossa ideia seria escrever um script de _parsing_ global que corresse automaticamente (através do GitHub Actions, por exemplo) a uma determinada hora e tratasse da actualização dos dados. 

O teu trabalho é o primeiro passo em direcção a isso. Queremos só esperar mais uns dias para garantir que o formato não continua a mudar radicalmente à medida que a epidemia progride. Será que podes fazer o _Pull Request_ e deixamo-lo pendente até chegarmos a essa fase em que consigamos extrair tudo? Teoricamente conseguirás fazer um PR seguindo o [guia do próprio GitHub](https://help.github.com/pt/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), penso que as permissões do repositório estão de forma a que tal seja possível.

**Comment by teresalazar13** [comment]
Muito obrigada! Extrai informação sobre todo o boletim (mas agora está desatualizado).
Isso era muito bom! Tentei fazer o PR mas estou a ter este erro:
```
remote: Permission to dssg-pt/covid19pt-data.git denied to teresalazar13.
fatal: unable to access 'https://github.com/dssg-pt/covid19pt-data.git/': The requested URL returned error: 403
```

**Comment by ishouldbedany** [comment]
Acho que tens que criar um fork do repositório primeiro, @teresalazar13. Através do botão _Fork_ no canto superior direito na página do repositório. 

E depois fazer um PR dessa tua versão para este repositório :)

**Comment by teresalazar13** [comment]
Ahhh já funcionou, muito obrigada! Já fiz o PR (não funciona agora porque já não está atual). Vou ver entretanto se arranjo uma melhor maneira de aceder aos dados pretendidos. Obrigada pela ajuda
