### ISSUE TITLE
Adicionar Registos Prociv

### ISSUE THREAD

**Issue by tensorfreitas** [dssg-pt/covid19pt-data#25]
Seria interessante adicionar os registos da proteção civil:

http://www.prociv.pt/en-us/SITUACAOOPERACIONAL/Pages/default.aspx

Pode ser uma fonte de dados interessante.

Talvez usando a API do VOST: https://api.vost.pt/documentation/

**Comment by paulomaia20** [comment]
Vou acrescentar ao repositório dados de 2018, 2019 e 2020, entre janeiro e maio, para tentarmos verificar alguma sazonalidade.

A fonte que estou a usar é https://github.com/centraldedados/protecao_civil

**Comment by Goldesel23** [comment]
Excelente @paulomaia20. Será que conseguíamos fazer update diário destes dados via GitHub Actions?

**Comment by ishouldbedany** [comment]
A ideia do @tensorfreitas é muito boa. Os próximos passos são começarmos a automatizar muita desta colecção de dados justamente através do GitHub Actions. 

Uma questão: fará sentido filtrarmos de alguma forma as ocorrências? Todaaaas as sub-categorias terão interesse?

**Comment by paulomaia20** [comment]
Gosto da ideia - vou investigar mas fecho já este issue, enquanto decidimos a melhor maneira de fazer isso
