### ISSUE TITLE
[Mini-projecto] Hello, could you please release new covid-19 data for Jul 24? Thank you so much

### ISSUE THREAD

**Issue by RuijingZ** [dssg-pt/covid19pt-data#252]
**🤔 Contexto**:

**🥅 Objectivo**:

**👥 Tamanho máximo da equipa**:

**🎯 Resultado final esperado**: 

**🧱 Principais etapas**:

--- 

Se estás interessado em pegar neste mini-projecto, diz coisas aqui em baixo ⬇️

**Comment by filipafcastro** [comment]
Hi @RuijingZ, done :) Sorry for the delay!
