### ISSUE TITLE
Formato da Data

### ISSUE THREAD

**Issue by luistelmocosta** [dssg-pt/covid19pt-data#26]
Bom dia, 
Em primeiro lugar, quero agradecer-vos pelo vosso trabalho fantástico, têm sido fantásticos.
Queria só pedir-vos para manterem o formato da data em ISO, sff. Reparei que mudaram o formato de ontem para hoje e para fins de automatização era mais útil se mantivessem sempre o mesmo formato :)

Obrigado,
Luís

**Comment by paulomaia20** [comment]
Olá Luís,

Obrigado pelo comentário! 

Pode ter acontecido alguma coisa em termos de formatação das colunas, pois hoje fui eu que tratei da atualização, e não o Daniel, e ele estava a usar o LibreOffice e eu o Excel.

Visualmente parece-me bem, está me a escapar alguma coisa? Estás a falar das colunas com "21-03-20 | 21-03-20 0:00", certo?

**Comment by luistelmocosta** [comment]
Olá, 
Vocês mudaram de, p.e, 12-03-2020 para 12-03-20. Não é crítico e eu consigo resolver do meu lado, mas se amanhã voltam a mudar os meus scripts estouram :) Se puderem voltar a por em ISO (12-03-2020) que é o formato standard, era impecável.

Obrigado,
Luís

**Comment by paulomaia20** [comment]
Ah, ok - foi mesmo do Excel a ter um comportamento diferente do LibreOffice :) Vou fazer a correção ASAP

**Comment by luistelmocosta** [comment]
Muito agradecido, Paulo!
Continuação de um bom trabalho

Abraço,
Luís

**Comment by paulomaia20** [comment]
Está feita aqui: https://github.com/dssg-pt/covid19pt-data/commit/e70c17d081d44dbcc76d21fa3cb3964d5b8c81b1#diff-b87775cb83cbf0511096cfb67074662a 

O excel converteu para dd-mm-yy e dd-mm-yy h:mm sem eu me aperceber, já corrigi isso :) 

Obrigado novamente pelo aviso e por usares o nosso repositório!

Abraço
