### ISSUE TITLE
[Mini-projecto] Hello, Portugal COVID-19 data have not been updated for consecutive 2 days, could you please update these data? Thank you for your help.

### ISSUE THREAD

**Issue by RuijingZ** [dssg-pt/covid19pt-data#279]
**🤔 Contexto**:

**🥅 Objectivo**:

**👥 Tamanho máximo da equipa**:

**🎯 Resultado final esperado**: 

**🧱 Principais etapas**:

--- 

Se estás interessado em pegar neste mini-projecto, diz coisas aqui em baixo ⬇️

**Comment by ishouldbedany** [comment]
Hi @RuijingZ,

The Portuguese Health authorities have drastically changed the file format of the epidemiological updates and we are still working in updating our automated systems to be compatible and more reliable in the future. Will update you once it's done. Thanks!

**Comment by lightningspirit** [comment]
Hi @ishouldbedany 
Do you need any help with coding skills to update the scrapper?

**Comment by ishouldbedany** [comment]
> Hi @ishouldbedany
> Do you need any help with coding skills to update the scrapper?

Hi @lightningspirit! Thanks for offering your help. 

We are planning changing some of the logic to consume data (the one that's available) directly from the [national dashboard](https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/), as we think it's the more reliable choice down the road. We have some experience in extracting data from these dashboards and will try to get something sorted out until Saturday or Sunday. I will update you if we need an extra pair of hands.

**Comment by ishouldbedany** [comment]
Hi @RuijingZ, @migromao and @lightningspirit. We're back in business and hopefully more reliable henceforth! Thanks for hanging in there :)

**Comment by lightningspirit** [comment]
@ishouldbedany thank you for your hard work, awesomely done! 💪
