### ISSUE TITLE
Colocar número de mortos por região

### ISSUE THREAD

**Issue by tigermarques** [dssg-pt/covid19pt-data#29]
Olá,

Dado que a DGS publica no seu relatório o número de mortos por cada região, seria possível ter esta informação no CSV?

Se acharem útil, posso fazer o trabalho de preencher os dados para trás com um PR.

Obrigado,

**Comment by ishouldbedany** [comment]
Olá @tigermarques, obrigado pelo feedback. 

Se conseguires contribuir com esse PR, agradecemos imenso. Só pedimos que actualizes o dicionário de dados e que mantenhas a retrocompatibilidade (não mudando o nome de nenhuma coluna pré-existente e preferencialmente adicionando novas colunas à direita da última, que neste momento é o `confirmados_m`). 

Qualquer dúvida, à vontade! :)

**Comment by tigermarques** [comment]
Olá @ishouldbedany ,

Vou trabalhar nesse PR e em breve submeto. Vocês conseguem garantir a actualização da coluna quando actualizam o restante do documento?

Quanto ao nome das colunas, eu iria colocar, seguindo o formato do documento, `obitos_arsnorte`, `obitos_arscentro`, `obitos_arslvt`, `obitos_arsalentejo`, `obitos_arsalgarve`, `obitos_acores`, `obitos_madeira` e `obitos_estrangeiro`. A nomenclatura parece-te bem?

Obrigado!

**Comment by tigermarques** [comment]
Já agora, a DGS hoje parece que está a colocar o número de recuperados por região também. Não há dados para trás, mas pode ser uma ideia para a frente, se eles forem manter o formato do relatório.
