### ISSUE TITLE
Clarificar alguns parametros

### ISSUE THREAD

**Issue by tiagorbf** [dssg-pt/covid19pt-data#3]
Boas,
Obrigado por disponibilizarem estes dados. Muito interessantes.
Tenho algumas perguntas relativas ao significado de algumas colunas:

O que é o lab?
Que região é confirmados_arslvt?
Qual a diferença entre suspeitos e vigilancia?
Qual a diferença entre confirmados e n_confirmados?

obrigado

**Comment by tiagorbf** [comment]
Desculpem não vi que explicavam isto no readme :/

**Comment by tiagorbf** [comment]
Ok so fiquei com uma pergunta:

Qual a diferença entre suspeitos e vigilancia?

**Comment by dssgPT** [comment]
Olá Tiago! Sim, optamos por incluir desde logo um dicionário de dados. 

Os termos suspeitos e vigilância seguem a nomenclatura da DGS, que por sua vez seguem a nomenclatura epidemieológica. Um bom recursos para isto é o [Plano de Contingência do COVID-19 pela própria DGS](https://covid19.min-saude.pt/wp-content/uploads/2020/03/Plano-de-Conting%C3%AAncia-Novo-Coronavirus_Covid-19.pdf) (página 65 em diante), que apresenta um glossário bem eslcarecedor: 

**Caso suspeito:** _Pessoa que preenche os critérios de definição de caso suspeito (clínicos, laboratoriais e/ou epidemiológicos), de uma determinada infeção ou doença._

Não há nesse glossário uma definição específica de **caso sob vigilância**, mas no nosso entendimento assemelha-se ao conceito aí definido de **caso sob investigação**: 

![image](https://user-images.githubusercontent.com/49449526/76767137-0f219780-6791-11ea-90b9-eff42d8451f7.png)

Nesta definição enquadram-se, por exemplo, pessoas com contacto próximo com uma infecção confirmada. 

Vamos adicionar um link para este glossário no README.md, obrigado pela chamada de atenção!

**Comment by Goldesel23** [comment]
Olá @tiagorbf , aqui podes encontrar também uma definição de casos sob investigação:

https://www.dgs.pt/directrizes-da-dgs/orientacoes-e-circulares-informativas/orientacao-n-0062020-de-26022020-pdf.aspx

No Ponto 8:

"Considera-se “contacto próximo” um trabalhador que não apresenta sintomas no momento, mas
que teve ou pode ter tido contacto com um caso confirmado de COVID-19. O tipo de exposição
do contacto próximo, determinará o tipo de vigilância"

O Documente tem as especificações mais pormenorizadas, mas acho que isto basta :)

**Comment by tiagorbf** [comment]
Muito obrigado pela resposta :D
