### ISSUE TITLE
Adicionar dados ARS Algarve

### ISSUE THREAD

**Issue by joaopalmeiro** [dssg-pt/covid19pt-data#30]
Olá!

A ARS Algarve, no dia 20 de março, começou a publicar um boletim diário com, por exemplo, a distribuição do número de casos confirmados por concelho. O que acham da adição destes dados ao repositório (talvez num novo ficheiro, dada a granularidade dos dados)?

Link: http://www.arsalgarve.min-saude.pt/noticias/covid-19-relatorio-de-situacao-diario-regiao-do-algarve/.

**Comment by ishouldbedany** [comment]
Já nos tínhamos cruzado com este dataset e discutido se valeria a pena ou não incluir. Seria sempre num ficheiro separado. 

O grande contra que encontramos é o facto de apenas a ARS Algarve estar a disponibilizar estes dados. Seria um dataset _riquíssimo_ se os tivéssemos para as 5 ARS + 2 RA. 

Claramente a DGS está a aprender _on the job_ acerca do que é recolher e disponibilizador dados... :man_shrugging:

**Comment by joaopalmeiro** [comment]
Pois... Acho que, pelo menos por enquanto, só a ARS Algarve é que está a partilhar este tipo de boletim/dados.

De qualquer das formas, caso precisem de ajuda a compilar estes dados, digam! 😄

**Comment by tensorfreitas** [comment]
Penso que a Unidade de Saúde Pública de Cascais também começa a libertar estes dados para a sua região.

**Comment by ishouldbedany** [comment]
Hoje a DGS já começou a adicionar dados mais granulares relativos aos óbitos e casos por concelho, creio já ser um grande avanço. 

Como estes são casos muito isolados e provavelmente nunca conseguiremos ter cobertura total, acho que é preferível agarrarmo-nos ao que a DGS está a divulgar. Portanto vou fechar, na esperança de ter que reabrir porque todas as ARS e RAs subitamente quiseram começar a ser verdadeiramente transparente :smile:
