### ISSUE TITLE
[enhancement] Adicionar coluna óbitos por dia 

### ISSUE THREAD

**Issue by volven** [dssg-pt/covid19pt-data#314]
Na coluna de óbitos já existente, subtrair o valor do dia anterior.
É possível?

Obg,

**Comment by davipt** [comment]
Todos os valores são cumulativos. Isto permite um cálculo fácil da diferença diária (subtrair o valor do dia anterior) ou da média semanal (subtrair o valor de há 7 dias e dividir por 7) ou qualquer valor pretendido, 3 dias para evitar a queda do fim de semana, 30 dias para mensal, etc.

**Comment by ishouldbedany** [comment]
Olá @volven,

Obrigado pela sugestão. A nossa opção tem sido ser um mero retransmissor (com garantias de fiabilidade e qualidade dos dados) dos dados oficiais, sem grandes cálculos (temos algumas colunas que são fruto de cálculos, mas porque vêm das fases iniciais do projecto e que optamos por manter sem questões de retrocompatibilidade). 

Para evitar tomar decisões pelas pessoas, tentamos manter-nos o mais inopinados possível. Como o @davipt disse, dessa forma fica mais fácil cada utilizador tomar decisões relativamente ao que quer ver.  

Assim sendo vou fechar, mas qualquer outra questão é perguntar.

**Comment by volven** [comment]
Obrigado pelo rápido _feedback_.
