### ISSUE TITLE
Dados em falta

### ISSUE THREAD

**Issue by rrp212** [dssg-pt/covid19pt-data#316]
Nas colunas "confirmados_f" e "confirmados_m" existe uma falta de dados entre os dias 17 e 28 de Agosto. No entanto esses dados estão disponíveis na segunda página dos [relatórios](https://covid19.min-saude.pt/relatorio-de-situacao/).
Talvez tenha sido pela mudança no template, mas sugiro que corrijam nem que seja manualmente, não são muitos dias :)

**Comment by rrp212** [comment]
Assim como nos dias 17 e 18 de Agosto faltam os dados da coluna "vigilancia" que estão na primeira página dos mesmos relatórios.

**Comment by davipt** [comment]
Posso ajudar e adicionar os dados em falta directamente no data.csv e mandar PR. Pff confirmem se faz sentido o esforço…
