### ISSUE TITLE
Dados por datas de sintomas

### ISSUE THREAD

**Issue by perone** [dssg-pt/covid19pt-data#323]
Olhar para os dados da pandemia ao longo do tempo pela data de confirmação dos testes acaba perdendo o sentido devido a vários fatores (i.e. misturar PCR com testes rápidos, atrasos de testes->confirmação->notificações, etc). No relatório da DGS eles disponibilizam um gráfico que contém duas séries: por data de sintomas e por data de notificação. 

![image](https://user-images.githubusercontent.com/412328/93892864-e8668f80-fce4-11ea-9597-13ce3de3239d.png)

Neste gráfico dá para ver a discrepância a o efeito de *right-censoring* dos dados ao olharmos pelas datas de sintomas, que são as únicas datas que tem um ponto fixo no tempo, ao contrário da data por notificação. Os dados por datas de sintomas são extremamente importantes para se calcular parâmetros epidemiológicos como por exemplo o R(t), hoje eu calculo ele [para cada região de Portugal pelas datas de notificação](https://perone.github.io/covid19analysis/portugal_r0.html), mas o ideal é utilizar as datas por sintomas e ajustar o right-censoring.

Alternativas para conseguirmos estes dados por data de sintoma:
- Tentar perguntar para a DGS para disponibilizar estes dados estruturados ao invés de imagem, mas a DGS raramente responde qualquer mensagem;
- Fazer scrapping visual da imagem, sabemos quais os valores da outra série, daria para tentar capturar os dados partindo da imagem (imenso trabalho, mas viável);
- Alguém tem alguma outra alternativa ?

Enfim, fica a ideia para discussão e se for interessante para outros também.

**Comment by davipt** [comment]
Os dados de inicio de sintomas estão apenas disponível para analistas que se registem e peçam acesso aos dados.

São usados pelo INSA para o cálculo do Rt oficial http://www.insa.min-saude.pt/category/areas-de-atuacao/epidemiologia/covid-19-curva-epidemica-e-parametros-de-transmissibilidade/ 
Estes valores de Rt estão agora aqui no repositório, no ficheiro `rt.csv`.

Como os valores originais da data de sintomas não aparecem na dashboard, é expectável que não sejam disponibilizados ao público. Se um dia aparecerem, tenta-se obter uma cópia.

Obrigado
