### ISSUE TITLE
Não há dados novos desde quinta-feira!

### ISSUE THREAD

**Issue by jmigueldelgado** [dssg-pt/covid19pt-data#329]
Não há atualizações do csv desde quinta-feira. Os relatórios de situação continuam a sair e ainda não houve atualização nem aqui nem na api. O que se passa?

**Comment by ishouldbedany** [comment]
Não temos ideia. Vamos esperar por amanhã e ver se as coisas regularizam na API, caso contrário começaremos a encetar contactos.

**Comment by jmigueldelgado** [comment]
Nesse sentido seria bom ter no `README.md` uma referência a como, onde e quem é que processa os relatórios de situação da DGS e faz push do csv.

**Comment by davipt** [comment]
Pode-se meter uma referência que os dados diários estão tão actualizados como a própria dashboard da DGS em  https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/ e na sua própria homepage https://covid19.min-saude.pt que tem tido dias que se esquecem de actualizar mas corrigem no dia seguinte, e desta vez não actualizaram sexta nem no fim de semana. Talvez actualizem hoje, com os dados por concelho…

**Comment by ishouldbedany** [comment]
Nós estamos a consumir os dados da mesma fonte que alimenta a dashboard que @davipt mencionou - que não é actualizada desde a passada quinta-feira. Já desde há alguns meses que deixamos de processar os relatórios, por não considerarmos uma fonte estável e fiável o suficiente.

Vamos esperar por novidades hoje (alguém na equipa da DGS fez fim-de-semana prolongado desde quinta?), caso contrário entrar em contacto com as autoridades devidas e esperar que não tenham descontinuado mais uma API de forma abrupta, opaca e sem qualquer plano de retrocompatibilidade.

**Comment by jmigueldelgado** [comment]
Obrigado pelo esclarecimento. Entendi. Do README.md fiquei com a ideia que estavam a atualizar a partir dos relatórios. Agora já percebi que os dados vêm da mesma API usada pelo dashboard (qual?). Obrigado pelo esclarecimento, nesse caso não há nada a fazer senão esperar. Incrível que a DGS não consiga estabilizar a publicação de meia dúzia de números diariamente...

**Comment by ishouldbedany** [comment]
@jmigueldelgado Tens toda a razão, o README.md está desactualizado e dá essa ideia. Vou tratar de corrigir. 

Podes verificar aqui o código para aceder e extrair os dados da API que alimenta a _dashboard_: https://github.com/dssg-pt/covid19pt-data/blob/master/.github/workflows/extract_data_arcgis.py

**Comment by davipt** [comment]
Acho que podemos todos fazer pressão na DGS independentemente desta situação pois podemos simplesmente perguntar porque é que a dashboard do próprio site https://covid19.min-saude.pt não está actualizado. Por isso partilhei o link directo para https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/  pois é na página da dashboard completa que mostra a data da última actualização - dia 24. Pessoalmente, vou esperar pela actualização de hoje, segunda feira, e ver se actualizam os dados diários, e os de concelho (o script ao lado, extract_dados_concelhos.py). Se não houver dados até ao fim do dia… :(

**Comment by davipt** [comment]
Eu sei que isto não faz sentido estar a fazer à mão, mas como o tinha feito no fim de semana para uso pessoal, e adicionar mais um dia não custa muito, se ajudar alguém até que actualizem a dashboard, tenho os dados em falta, que estão no PDF, no meu branch em https://github.com/davipt/covid19pt-data/blob/temp/data.csv 

Aproveito também para partilhar a minha sandbox, caso haja lá alguma coisa que possa ajudar alguém.
https://colab.research.google.com/drive/1SkU8raqpAs2_U8HwHhVobqZr77tpyZa7?usp=sharing

Fará sentido tentar actualizar manualmente quando os dados estão em falta no arcgis, aka posso criar PR para isso se quiserem…

**Comment by ishouldbedany** [comment]
Alguém foi de férias uns dias. Entretanto os dados já foram actualizados. (PR #330) e o repositório também. Obrigado a todos pela diligência!
