### ISSUE TITLE
Dados por concelho desactualizados

### ISSUE THREAD

**Issue by mjamado** [dssg-pt/covid19pt-data#339]
Os dados por concelho não foram ainda actualizados esta semana.

Alguém pode dar aí um pontapé na pipeline? :smirk:

**Comment by ishouldbedany** [comment]
Olá @mjamado,

Estive agora a pontapear a pipeline manualmente (eheh) e aparentemente a fonte de dados está seca relativamente aos dados desta semana :confused:. 

Esperemos mais 1 dia ou 2 e vejamos se alguém se lembra que quebrar/abandonar silenciosamente protocolos e fontes de informação públicas não é aceitável.

**Comment by mjamado** [comment]
@ishouldbedany o Arcgis (é daí que vêm, não é?) já tem - finalmente - os dados novos.

Quase que vinham a tempo de serem duas semanas juntas... :roll_eyes:

**Comment by davipt** [comment]
For reference, se não for feito nada até segunda feira, o processo nesse dia irá actualizar os dados todos e portanto incluir a semana de 5 de outubro em falta.

**Comment by mjamado** [comment]
Já foi feito. Actualizado.
