### ISSUE TITLE
Dados de Confirmados e Óbitos por Género e Idade

### ISSUE THREAD

**Issue by pmoura11** [dssg-pt/covid19pt-data#349]
Olá. Boa tarde.

Antes de mais, gostaria de agradecer a todos quanto contribuem para a geração destes dados.

Não sei se a situação já se tinha verificado antes ou, inclusive, se já tinha sido reportada, mas no dia 03/10/2020 e 05/10/2020 não existem dados de confirmados e óbitos, por género e idade.

Caso seja possível corrigir, creio que o dataset ficaria mais coerente.

Obrigado e Cumprimentos,
Pedro Moura

**Comment by davipt** [comment]
Eu já corrigi esses dois dias no PR ali ao lado, que também actualiza o histórico de activos e enfermaria, mas posso fazer split da actualização desses dois dias num PR em separado. Podes confirmar se o data.csv que está lá está ok? (Estou no móvel… precisas do link?)

**Comment by pmoura11** [comment]
No dia 03/10, parece-me que os dados ficaram corrigidos.
Contudo, os dados de óbitos por género/idade de 05/10 estão todos a zero...

**Comment by davipt** [comment]
Se bem me lembro, esses dados já não estão no boletim pdf (só tem o gráfico) portanto se não houver dados na API… tens sugestão de onde os ir buscar?

**Comment by pmoura11** [comment]
Os campos que eu estou a falar são: 
`obitos_0_9_f | obitos_0_9_m | obitos_10_19_f | obitos_10_19_m | obitos_20_29_f | obitos_20_29_m | obitos_30_39_f | obitos_30_39_m | obitos_40_49_f | obitos_40_49_m | obitos_50_59_f | obitos_50_59_m | obitos_60_69_f | obitos_60_69_m | obitos_70_79_f | obitos_70_79_m | obitos_80_plus_f | obitos_80_plus_m | obitos_f | obitos_m`

Estes dados estão com valores nos dias anteriores e nos dias posteriores ao dia 5 de outubro.

**Comment by pmoura11** [comment]
Quanto aos dados de ativos e enfermaria, embora não os esteja a utilizar diretamente do ficheiro, estou a calculá-los. Pelo menos no dia de hoje (12/10) batem certo com o meu cálculo.

**Comment by davipt** [comment]
Os dados de dia 5 para óbitos não estão disponíveis na DGS / ERSI / arcgis / plataforma que sustenta a dashboard em https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/ 

Os de dia 3 foram disponibilizados após a actualização do csv, e como existem, pode-se corrigir. Mas os de dia 5 não existem.

**Comment by pmoura11** [comment]
Ok. Obrigado.

**Comment by ishouldbedany** [comment]
Sim, confirmando o que o @davipt, os dados de dia 5 estão complemente em falta. Não existem em absolutamente nenhuma fonte de dados oficiais.

**Comment by pmoura11** [comment]
> No dia 03/10, parece-me que os dados ficaram corrigidos.

No ficheiro gerado hoje, esta correção do dia 03/10 ainda não se encontra refletida.
Vai ser aplicada ao master de @dssgPT ?

**Comment by davipt** [comment]
Correto. @paulommaia queres que separe o update dos dados de dia 3 das outras alterações do outro PR, para fechar este ticket mais depressa?

**Comment by davipt** [comment]
@pmoura11 já está em master a actualização de dia 3. Se vires mais algum dia que faltem dados ou que estejam inconsistentes, avisa. Obrigado.

**Comment by pmoura11** [comment]
Ok. Obrigado.
