### ISSUE TITLE
Partilha de informação

### ISSUE THREAD

**Issue by DuarteAndre** [dssg-pt/covid19pt-data#36]
Caros,
Tenho partilhado através da vossa compilação de dados.
Vou colocar espacialmente o número de casos de hoje.

https://github.com/DuarteAndre/Covid-19_visualizacao_dados

**Comment by ishouldbedany** [comment]
Obrigado @DuarteAndre. É a primeira que vejo um mapa com dados por concelho, foi um bom tempo de resposta relativamente ao respectivo lançamento hoje à tarde. 

Estamos a reunir todas as contribuições e análises feitas a partir destes dados aqui #20, adiciona lá!
