### ISSUE TITLE
Obitos a 5/10

### ISSUE THREAD

**Issue by pinanunes** [dssg-pt/covid19pt-data#362]
O número de óbitos cumulativos por classe etária no dia 5/10 aparece a 0
Se foi um dia sem reporte os sem óbitos deveria apresentar o valor do dia anterior.

**Comment by davipt** [comment]
Para o dia 5 de outubro não existe informação oficial sobre o número de óbitos.

Os dados são recolhidos da API da ESRI, os mesmos dados usados pela dashboard em covid19.min-saude.pt. Essa API não tem dados de óbitos para esse dia. 

O relatório em PDF só tem um gráfico, sem valores, sendo impossível tentar obter esses valores manualmente. 

Como diz no README, os dados em falta estarão omissos no CSV. 

Haverá algum local que se possa obter estes dados em falta?

Será melhor ter esses dados vazios em vez de zeros no csv? Fui eu que indiretamente os coloquei a zero quando actualizei o dia 3 que também estava em falta, neste caso apenas por atraso na actualização da API. Posso limpar os zeros se for mais explícito que não existem esses valores… o que acham?

**Comment by ishouldbedany** [comment]
Para mim faz mais sentido a inexistência de valores ser marcada por um vazio do que por um 0. Assim ficam fáceis de identificar e cada pessoa pode aplicar o tratamento que achar mais conveniente (interpolar, utilizar valores anteriores/seguintes, colocar a 0, etc). Acho que é a solução menos opinada, que é um dos objectivos deste repositório.

**Comment by davipt** [comment]
Concordo. Amanhã mando PR com os valores vazios no csv, e alteração no extract_arcgis para prevenir este tipo de situações. 

No dia 3 e no dia 5 não havia valores nenhuns na API na altura que este workflow correu. Faltava mesmo as key-values para o dia, o que gera vazios no csv. 
Quando se correu dias mais tarde, os valores de dia 3 estavam lá, e parecem corretos, mas os de dia 5, estavam explicitamente a zeros na api do arcgis. O código tem de assumir que zero é desconhecido, sem afetar o comportamento no passado (outros valores que eram mesmo zero no início da pandemia)

Obrigado

**Comment by davipt** [comment]
https://github.com/dssg-pt/covid19pt-data/pull/366

**Comment by paulomaia20** [comment]
Fechado, obrigado!
