### ISSUE TITLE
Dados repetidos em 23 e 24

### ISSUE THREAD

**Issue by pmoura11** [dssg-pt/covid19pt-data#368]
Os dados dos días 23 e 24 de Outubro estão iguais.

**Comment by davipt** [comment]
Os dados no arcgis que dizem ser de dia 24 são realmente de dia 23. master está correcto.
Não vejo dados de dia 24 na API, nem com timestamps diferentes. Tendo em conta que até o PDF diz -003, deve ter havido atraso na introdução dos dados, e quando introduziram os dados de dia 23, entrou no sistema como 24.
Suspeito que hoje 25 aparecerá os dados de hoje, e os de 24 não aparecerão na API. Se for o caso pode-se (posso) adicionar o PDF e os dados possíveis à mão para o dia 24 em falta. Vamos esperar até ao fim do dia…

**Comment by filipafcastro** [comment]
Olá @davipt, é exatamente isso. Vamos esperar sim e, caso seja preciso, agradecemos a ajuda :)
