### ISSUE TITLE
Óbitos por faixa étaria

### ISSUE THREAD

**Issue by eSoares** [dssg-pt/covid19pt-data#37]
Viva,
Estava a olhar para os dados e tendo em conta as boas práticas dos outros países, sugeria além da catalogação dos confirmados por faixa etária, o mesmo fosse feito com os óbitos.
Sei que os dados oficiais não têm essa indicação (pelo menos no relatório diário da DGS), mas pelo menos a partir das noticias é possível reconstruir esses dados.

**Comment by ishouldbedany** [comment]
Olá @eSoares 

Obrigado pelo feedback! A DGS lançou hoje um formato de boletim novo em que inclui informação mais granular (casos ao nível do concelho) e a demografia global dos óbitos. Vamos pensar na melhor maneira de organizar esta informação e nos próximos dias espera vê-la surgir!
