### ISSUE TITLE
Resultados laboratoriais

### ISSUE THREAD

**Issue by joni-santos** [dssg-pt/covid19pt-data#378]
Antes de mais obrigado pela construção e partilha desta ferramenta.

O número de casos à espera de resultado laboratorial no ficheiro de dados.csv deixou de ser disponibilizado (pela DGS deduzo). Para isso devem ter adicionado o ficheiro de amostras.csv, no entanto, este não é sempre atualizado.
Porque motivo é que acontece?

Abraço e mais uma vez obrigado

**Comment by davipt** [comment]
Os dados de amostras, tais como os diários e semanais de concelhos vêm todos da mesma API pública que sustenta a dashboard em https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/ entre outras.

Neste moment (27 10:00) essa dashboard mostra dados até dia 22.

Tem sido expectável os dados terem alguns dias de atraso, incluindo correções de valores de dias anteriores.

**Comment by joni-santos** [comment]
Ok, obrigado pela informação.
