### ISSUE TITLE
data_concelhos.csv em formato normalizado

### ISSUE THREAD

**Issue by rgr78** [dssg-pt/covid19pt-data#383]
Bom dia.

Os dados 'data_concelhos.csv' estão em formato tabela pivot, ou seja, cada coluna corresponde a um município. Seria possível ter esta informação também em formato normalizado? Ou seja, com as colunas 'data','municipio','valor'? Para alguns casos de uso e ferramentas este é o formato necessário.

Obrigado.

**Comment by ishouldbedany** [comment]
Olá @rgr78,

Inicialmente quando começamos a aglomerar dados de concelhos tivemos esta discussão e tentamos escolher a representação mais canónica possível, e acabamos por escolher esta representação. Porque é extremamente flexível (pode ser facilmente transformado naquele que mencionas) e porque tem legibilidade quando aberto e simplesmente visualizado - maximizando o alcance. 

Por questões de retrocompatibilidade, temos sempre muito receio em alterar o formato, sob pena de quebrar ferramentas que dependam desse formato. Faz sentido? 

No entanto, não temos qualquer problema em aceitar contribuições em código ou em tutorial (para incluir no `README.md`) sobre como fazer essa alteração. Por curiosidade, em que ferramentas/casos de uso é que esse formato é particularmente útil?

**Comment by rgr78** [comment]
Olá @ishouldbedany.

Concordo que não se deve mudar o formato do ficheiro existente. O que eu sugeria era criar um outro, como os mesmos dados, mas neste formato que refiro. 'data_concelhos_normalized.csv' ou qualquer outro nome.

Percebi a utilidade imediata e a legibilidade de vir logo em fomato tabela pivot. Mas, para fazer joins com outras tabelas, e para extender a informação, o formato que sugiro é o ideal.

Claro, posso sempre fazer um programita para converter. Mas depois tenho de corrê-lo sempre que queira refrescar os dados. Estava a tentar criar uma pipeline completamente online, ainda não sei se consigo. Imaginei que poderia ser simples adicionar à vossa pipeline esta transformação.

Relativamente à ferramenta, estava a carregar os dados para o Tableau para os analisar geograficamente.

**Comment by davipt** [comment]
Recordo que os três ficheiros CSV estão consistentes no formato linha == "data", coluna == "categoria" e que para se fazer para um, ter-se-ia de fazer para os três.

O Tableau tem esta particularidade de estar limitado ao consumo de dados simples no formato "X, Y, serie (opcional)" ☹️

Faz sentido ter os três ficheiros duplicados em formato "data, key, valor" ? Seria talvez mais um passo no pipeline que abre os três ficheiros, faz um .melt(), e grava o novo ficheiro.

No notebook dos concelhos tive de fazer isso para normalizar os dados antes de correlacionar com a população, o que é basicamente a capacidade do Tableau - "x, y, serie", e correlacionar "serie" com outra tabela, mas em modo gráfico 😀

df = df.melt(id_vars=['data'], var_name='Concelho', value_name='Casos')
df = df.merge(population[['Concelho', '2019']], how='left', left_on='Concelho', right_on='Concelho')

https://github.com/dssg-pt/covid19pt-data/blob/master/notebooks/concelhos.ipynb

**Comment by rgr78** [comment]
Lol, acho que o que quero fazer já está feito nesse notebook. Vou dar uma vista de olhos, obrigado.

**Comment by davipt** [comment]
Nesse notebook falta apenas o mapa. O notebook é uma cópia do meu notebook online em https://colab.research.google.com/drive/1PVcW7IwzUb_oGfYf7x-EmH9bAhcpa_cY

O meu notebook foi usado para ajudar o Jorge da VOSTPT no site dele no serviço do Flourish, para confirmar se os valores batiam certo. Depois reduzi para esse notebook para poder ficar uma cópia de exemplo deste repositório, incluindo os dados mais recentes de população. 

Espero que ajude. Se precisares de mais ajuda apita, aqui ou direto (mesmo nick nas outras redes). 

Boas contas!

**Comment by rgr78** [comment]
Giro. Não sabia que a Google tinha a sua versão do Jupyter notebooks. Vou brincar um bocado.

**Comment by davipt** [comment]
Ve lá se era isto que precisas ;) 

https://github.com/dssg-pt/covid19pt-data/pull/388

<img width="563" alt="Captura de ecrã 2020-11-01, às 18 45 37" src="https://user-images.githubusercontent.com/574281/97811443-936a5180-1c72-11eb-9056-ebc0ebb22410.png">

A fórmula do governo é a da ECDC - 240 casos nos ultimos 14 dias por 100k - adicionada de "incluindo concelhos ao lado" (por exemplo Oeiras que tinha 228 no dia 26, e se calhar até já passou os 240 casos desde esse dia, mas não tendo, como está rodeada por Cascais Sintra Amadora Lisboa, é incluída na lista)

Giro agora era extender este notebook para também conhecer as fronteiras entre concelhos e permitir inclui-los no mapa.
Até lá, meti o mapa com categorias - 0 para Nan, para identificar concelhos em falta (há um buraco branco no mapa, e dois concelhos que não estão alinhados…), 1 para 0 (há 15 concelhos sem casos, ou com apenas 1 ou 2, no dia 26), e depois 2 para 1 a 119, 2 para 120 a 239, 3 para 240 e acima. Os 2 serão os concelhos potenciais a terem passado os 240 nesta semana.

Feedback? Vale a pena incluir este PR?

**Comment by rgr78** [comment]
@davipt, ia analisar o número de casos por 100k, mas esse com a fórmula do governo serve perfeitamente!

Diria que vale bem a pena incluir esse PR.

**Comment by davipt** [comment]
Se quiseres o número de casos por 100k é só mudar o `.diff(2)` para `.diff(1)`. Como os dados são semanais, o `diff(2)` calcula a diferença de duas semanas, 14 dias. Se quiseres os valores absolutos é só comentar o código no meio que substitui os valores pelo "racio" da população.

**Comment by pmoura11** [comment]
Olá.
Alerto para o seguinte comentário no relatório de hoje da DGS:
```
**Nota metodológica**
Os dados por concelho serão atualizados durante esta semana, na sequência da reformulação dos indicadores relativos aos novos casos de COVID-19 pela Direção-Geral da Saúde. As medidas de controlo de COVID-19 têm por base a incidência cumulativa a 14 dias, que corresponde ao número de novos casos nos últimos 14 dias por 100 000 habitantes. Pretende-se que esta seja a principal métrica utilizada na avaliação de risco de cada concelho para que os cidadãos possam acompanhar a evolução da pandemia nos concelhos.
```
Julgo que isto pode significar que os dados passem a ser divulgados em novos casos nos últimos 14 dias por 100 000 habitantes. Resta esperar que a API da ArcGIS responda a esta necessidade e garantir a retrocompatibilidade.

**Comment by ishouldbedany** [comment]
Obrigado @pmoura11! Estamos atentos à situação e a monitorizar as novidades para perceber como as integrar. Esperemos que o que venha a ser lançado não seja mais um ficheiro PDF com as aglomerações já feitas. Mas não ponho as mãos no fogo :smile:

**Comment by pmoura11** [comment]
@ishouldbedany ainda bem que não puseste as mãos no fogo!

**Comment by davipt** [comment]
A pandemia já deu muitas voltas e as incidências de concelhos já estão disponíveis há meses. Vou fechar isto ok? Obrigado a todos.
