### ISSUE TITLE
determinação dos casos confirmados_novos

### ISSUE THREAD

**Issue by rpfigueira** [dssg-pt/covid19pt-data#385]
Em __data.csv__, é possível obter uma explicação de como são obtidos os valores da coluna `confirmados_novos`?
Eu calculei a soma de novos ativos com novos recuperados e com novos óbitos:

```calc_confirm_novos = novos_ativos + novos_recuperados + novos_obitos```

em que os valores de `novos_*` são a diferença entre o valor do dia com o dia anterior, para cada um dos parâmetros. Depois comparei os novos valores de `calc_confirm_novos` com o valor fornecido na coluna  `confirmados_novos`, e verifiquei que os valores são iguais (excepto alguns dias em que os valores na coluna `ativos` não corresponde aos do relatório em https://covid19.min-saude.pt/relatorio-de-situacao/). 

Pergunto, por isso, porque são contabilizados os valores de novos recuperados e novos óbitos para o valor diário de confirmados_novos?

**Comment by davipt** [comment]
Há valores que são redundantes (calculáveis através de outros valores) que estão no CSV porque também estão ou no boletim ou na API da dashboard oficial, e mais vale informação a mais que a menos.

Até agora, o "confirmados_novos" é sempre igual ao "confirmados" (total) menos o valor do dia anterior.

O ativos é um valor que começou a ser coletado da API da dashboard há algumas semanas, e depois fez-se um backtrack dos valores anteriores.

Pela mesma razão, embora se possa calcular ativos = confirmados - recuperados - obitos, não se perde nada em ficar com o valor oficial, nem que seja para verificar que algo está incorrecto!

Realmente há 9 valores em que o valor não bate certo.

https://colab.research.google.com/drive/1OckzRES0B6i5bF5BzuX2M0XkX121Fqyx?usp=sharing

	data	diff	confirmados	obitos	recuperados	ativos
5	02-03-2020	2	2	0	0	0.0
19	16-03-2020	328	331	0	3	327.0
21	18-03-2020	638	642	1	3	637.0
24	21-03-2020	1263	1280	12	5	1268.0
25	22-03-2020	1581	1600	14	5	1591.0
123	28-06-2020	13016	41646	1564	27066	12836.0
183	27-08-2020	13505	56671	1809	41357	13507.0
241	24-10-2020	45970	116109	2297	67842	46970.0
246	29-10-2020	54486	132616	2428	75702	51996.0

Vou verificar o que se passa.

**Comment by rpfigueira** [comment]
A minha questão está principalmente relacionada com o conceito de confirmados_novos. O entendimento geral sobre o conceito deste parâmetro é de que corresponde ao _número de novos casos reportados em cada dia_. Se é assim, então não faz sentido que este seja calculado como `confirmados_novos = activos_novos + recuperados_novos + obitos_novos`, pois estas duas últimas parcelas não devem ser incluídas nos novos casos reportados. O problema pode estar relacionado com a formula `activos = confirmados - recuperados - obitos`, cuja transformação `confirmados = activos + recuperados + obitos` é correta para o cálculo de confirmados totais, mas se for para calcular as diferenças diárias, não pode usar a diferença diárias das parcelas de activos, recuperados e óbitos, tal como referido atrás. Mas ao que percebi, é um problema na origem, que deve ser resolvido a esse nível...

**Comment by davipt** [comment]
Há vários dados ligeiramente inconsistentes no passado, não batendo certo nem entre boletins, nem com a API. Temos de viver com isso.

Após verificar os dados na API e os boletins, incluindo dias anteriores e posteriores, está aqui https://github.com/dssg-pt/covid19pt-data/pull/386 a correção de alguns dados de ativos, e um notebook para ajudar a verificar se há mais dados que não estejam corretos.

**Comment by davipt** [comment]
> O entendimento geral sobre o conceito deste parâmetro (confirmados_novos) é de que corresponde ao número de novos casos reportados em cada dia.

Correcto. Tal como o obitos_novos são os lamentáveis óbitos registados nesse dia, e os recuperados_novos são os casos que foram libertados do sistema nesse dia :)

> Se é assim, então não faz sentido que este seja calculado como confirmados_novos = activos_novos + recuperados_novos + obitos_novos, pois estas duas últimas parcelas não devem ser incluídas nos novos casos reportados.

Correto. E não é assim que é calculado, embora matematicamente esteja correcto.

O valor que é estranho é o que existe no boletim, e que não existe na dashboard nem na API, que é o conceito de "ativos_novos".

O valor de ativos é calculado como "confirmados menos recuperados menos obitos", quer em valor absoluto quer em valor diário, e embora esteja matematicamente correcto, na realidade o que é mesmo um "novo caso ativo" se não a variação de casos ativos no sistema de tracing?

tldr novos_ativos é um valor matematicamente correto, mas irrelevante, e dispensável do boletim 😀

**Comment by rpfigueira** [comment]
O cálculo de `confirmados_novos` está errado, pois está a haver duplicação de contagem de casos. Os `recuperados_novos` e `óbitos_novos` de um determinado dia já foram anteriormente contabilizados como `activos_novos`. Na verdade, `activos_novos` deveria ser igual a `confirmados_novos`, se se considerar que esta última variável corresponde ao número de novos casos reportados positivos no último dia. Por isso, acho que há algo a rever por parte de quem está a reportar os dados.

**Comment by davipt** [comment]
O valor de cada valor `confirmados_novos`, `recuperados_novos`, `obitos_novos`, e `activos_novos`, são a diferença do valor correspondente actual em relação ao valor do dia anterior. Isto está incorreto?

**Comment by rpfigueira** [comment]
Sim! Não está errado se cada um dos parâmetros for calculado isoladamente, pela diferença dos dois últimos valores. Mas não se pode calcular `confirmados_novos` com base a fórmula `conf_novos = activos_novos + recup_novos + obitos_novos`, pois as variáveis `activos_novos`, `recup_novos` e `obitos_novos` não são independentes. Isto porque os casos de `activos_novos` de hoje serão os  mesmos casos `recuperados_novos` ou `obitos_novos` alguns dias depois. Por isso, há dupla contabilzação de casos `confirmados_novos`, pois as parcelas de recuperados e obitos já foram anteriormente contabilizadas como novos actvos.

**Comment by davipt** [comment]
O valor de `ativos_novos` é negativo quando há mais `recuperados` e `óbitos` do que novos `confirmados` nesse dia.
Por exemplo no boletim de dia 20 de Outubro que tem `-71`.

Os valores de `confirmados`, `recuperados`, e `óbitos`, são valores acumulados que crescem ao longo do tempo, portanto os correspondentes `*_novos` serão sempre positivos.

O valor de `ativos`, `internamento`, e `uci` são valores absolutos desse dia, e que variam ao longo do tempo, portanto os correspondentes `*_novos` podem ser positivos ou negativos.

Pode dar um exemplo onde os valores estejam incorretos?

**Comment by rpfigueira** [comment]
A minha questão não se relaciona com valores para dias específicos, mas como são determinados os valores de `confirmados_novos`. Não estava à espera que os novos confirmados para cada dia estivessem relacionados com os novos recuperados ou novos óbitos do mesmo dia, caso estes dados resultados fossem reportados a partir dos dados de terreno (pelas ARSs). Mas aparentemente os dados são calculados uns a partir dos outros, não reportando a evolução diária real, mas sim o balanço total.

**Comment by davipt** [comment]
Os valores de `confirmados_novos` `recuperados_novos` e `óbitos_novos` são valores reais diários reportados a partir do terreno, sempre positivos ou zero, que acumulam respectivamente em `confirmados_total` `recuperados_total` e `obitos_total`.

Os valores de `ativos` `internados` e `uci` são balanços diários de quantas pessoas ainda estão ativas total, ou no hospital (o restante está em casa). Desses valores pode-se calcular a variação diária, que será positiva quando o dia correu mal, e negativa quando estamos no bom caminho para chegar a zeros. 

**Esta é a definição dos valores, portanto "por definição" são verdades absolutas não passíveis de ser interpretadas de qualquer outra forma.**

Se tiver 1000 ativos e adicionar 500 confirmados e retirar 200 recuperados, ficarão 1300 ativos.

Todos os valores estão relacionados por matemática simples. É perfeitamente expectável que tendo `c - r - o = a`, se possa transferir os termos para o outro lado e se veja `c = a + r + o`, o que não altera em absolutamente nada a definição de cada valor.

Espero que tenha ajudado a compreender a sua questão e aparente confusão. No entanto este não é o fórum correto para este tipo de dúvida.

Sei que há uma aula para crianças do 5º e 6º ano em Centros de Estudo privados em que explicam isto, incluindo o conceito mais avançado de exponenciais, e têm tido um bom resultado. Talvez seja necessário pedir para darem uma aula no Estudo em Casa para o público em geral.

Obrigado.

**Comment by rpfigueira** [comment]
Obrigado pela informação de que os dados de `confirmados_novos`, `recuperados_novos` e `óbitos_novos` são dados do terreno, e não obtidos por inferência. Essa informação não estava disponível, e resolve a questão da eventual duplicação de contagem de casos confirmados por inclusão de recuperados.
