### ISSUE TITLE
Covid-19 ao Municipio em formato Geopackage

### ISSUE THREAD

**Issue by DuarteAndre** [dssg-pt/covid19pt-data#39]
Geopackage com a informação ao nível do Municipio : https://github.com/DuarteAndre/Covid-19_visualizacao_dados/blob/master/Geopackage_COVID.gpkg

Scritp de visualização de dados: https://github.com/DuarteAndre/Covid-19_visualizacao_dados/blob/master/Covid-19_geopackage.ipynb

Análise gráfica + Regressão OLS: https://github.com/DuarteAndre/Covid-19_visualizacao_dados/blob/master/Meus_testes_COVID.ipynb

**Comment by tensorfreitas** [comment]
Olá @DuarteAndre podes adicionar ao #20 para adicionarmos ao README?
