### ISSUE TITLE
Repetição dados 27 e 28 outubro

### ISSUE THREAD

**Issue by filipafcastro** [dssg-pt/covid19pt-data#392]
Aberto por @flipjribeiro
Em primeiro lugar o meu muito obrigado pela vossa disponibilização de dados. A mim, demógrafo de profissão, torna tudo bastante mais prático.
Tenho todavia, uma questão: nos dados de 28 e 27 de Outubro, a distribuição dos óbitos e dos casos por idade repetem-se. Não consigo atualizar, pois os relatórios diários da DGS já não têm ali os valores e não consigo voltar atrás.
Será que podem ajudar?
P.S.: Sempre que tenha algo a publicar, existirá uma referência ao vosso trabalho, claro.

**Comment by filipafcastro** [comment]
Olá @flipjribeiro. Penso que te referes aos dias 28 e 29 de outubro. Infelizmente, não temos forma de ajudar porque, pelo menos para já, os dados estão assim disponibilizados no [serviço da ESRI de ArcGIS](https://services.arcgis.com/CCZiGSEQbAxxFVh3/arcgis/rest/services/COVID19_ConcelhosDiarios/FeatureServer/0/), que é de onde extraímos os dados todos os dias.

**Comment by flipjribeiro** [comment]
Olá @filipafcastro! Muito obrigado. Sim, refiro-me aos relatórios desses dias, apenas referi os dias a que eles se referem por lapso. Os relatórios diários da DGS também só têm gráficos, o que é muito mau. Estava a contar com essa informação para (contuinuar a) contribuir para aqui https://github.com/timriffe/covid_age e de repente trocam o formato. Procurei solução e o vosso trabalho ajuda imenso, mas aquela "falha" nos dados não... Uma vez mais, obrigado!

**Comment by paulomaia20** [comment]
Olá @flipjribeiro, infelizmente continua a não haver solução.. .Não queremos fazer algo como uma interpolação dos valores pois queremos apenas manter dados originais, sem fazer qualquer tentativa de preencher valores em falta, que podem estar completamente erradas, mas talvez para o teu projeto possas adotar uma solução do género? Com base nos valores dos dias anteriores e dos dias seguintes estimar os valores desses dias, colocando a nota metodológica associada.

**Comment by flipjribeiro** [comment]
Olá @paulomaia20, sinceramente exatamente foi o que eu pensei em fazer. Apesar de não me agradar muito a ideia, talvez tenha que ser assim solucionado. Obrigado pela ajuda!

**Comment by davipt** [comment]
O @JPBraga1 tinha uma cópia dos confirmados e obitos por idades para o dia 29 de outubro, o dia em que a API retorna exactamente os mesmos dados que 28 (ainda hoje mantêm-se assim), e portanto teve-se de inserir os valores à mão, do boletim, mas faltavam os valores por idade, que não estão no boletim (estão apenas encapsulados no gráfico).

Neste issue e respectivo PR foram corrigidos os valores em falta. https://github.com/dssg-pt/covid19pt-data/issues/714
