### ISSUE TITLE
Dados óbitos por idade/sexo no relatório de 5 de outubro

### ISSUE THREAD

**Issue by wisevis** [dssg-pt/covid19pt-data#394]
Olá

Os dados de 5 de Outubro aparecem sem valores para óbitos por sexo e idade.

Como se pode resolver?

Obrigado

Jorge

**Comment by ishouldbedany** [comment]
Olá @wisevis, 

Não sei se entretanto a tua questão já foi respondida (visto que este problema é abordado noutros issues do repositório), mas nesse dia a nossa fonte de dados (dashboard da ESRI Portugal, alimentada para a DGS) também não tem esses dados. Não há propriamente uma solução fácil.

**Comment by wisevis** [comment]
Olá @ishouldbedany. 
Não sei porque não encontrei o issue inicialmente, por isso abri este, mas como encontrei depois, fechei-o imediatamente. É a primeira vez que estou a olhar para os dados mais em detalhe e já percebi que há outros dias com problemas e certamente irão aparecer outros no futuro. Acho que vou ter de ter à mão uma tabela de correcções com os meus valores estimados para substituir os dias problemáticos.

Obrigado e parabéns pelo excelente trabalho!
