### ISSUE TITLE
Tweet condicional em função dos ficheiros atualizados

### ISSUE THREAD

**Issue by paulomaia20** [dssg-pt/covid19pt-data#398]
Segundo recomendação do Filipe Ataíde: https://twitter.com/FilipeAtaide/status/1325409353617313792

O tweet enviado deve ser condicional em função dos dados atualizados serem:

- Apenas dos casos diários (data.csv)
- Dados por concelho (data.csv)
- Testes 

Indicando quais destes três foram modificados.

**Comment by davipt** [comment]
Como disse no twitter, sugeriria:
- melhorar o ultimo tweet para ser mais claro que é apenas um jump-off para o repo com os dados todos. "Mais dados em GitHub". Que "há mais dados" e não "que foram todos actualizados".
- adicionar um tweet caso haja dados de concelho. Esperar para ver se vai haver dados de concelho de todo

Adicional:
- dados de amostras poderá ser arriscado, pois têm sempre 2 ou 3 dias de atraso, e na ultima semana tem sido tudo completamente recalculado, com um update massivo de dados desde abril.
- continua a faltar os dados de ativos, que não cabiam nos dois primeiros tweets, e não se chegou a uma conclusão na altura (há algum canal de chat do grupo?)
- há outros dados interessantes que seria interessante terem sido notado no tweet -  com médias de algumas centenas por dia "em vigilância", há dias houve dois dias com 11 mil!

**Comment by davipt** [comment]
Temos workflow automático desde agosto:
- verifica se há dados novos de casos, amostras, vacinas, rt
- se houver alguma coisa, prepara a imagem (pandas etc)
- se houver mesmo dados novos de casos, faz o tweet dos dados
- se houver mesmo dados novos de vacinas, faz o tweet das vacinas
- amostras (testes) e Rt nunca tiveram tweet e não é agora que serão precisos. (e amostras continua a ser actualizado retroativamente)
- dados semanais ainda não estão automáticos (concelhos/sexta feira e relatório vacinas/terça ou quarta), nem lançam tweets por si só. Concelhos nunca teve, e relatório são mais dois tweets no das vacinas.

Vou fechar isto por agora ok?
