### ISSUE TITLE
data_concelhos.csv sem atualizações

### ISSUE THREAD

**Issue by pgaspar** [dssg-pt/covid19pt-data#401]
Olá! Reparei que os dados do `data_concelhos.csv` já não são atualizados há 2 semanas pela DGS - parece que deixaram de os incluir nos relatórios de segunda-feira.

Alguém tem mais informação sobre isto? Estes dados são ainda mais relevantes agora, tendo em conta que as medidas são ditadas ao nível do concelho com base na evolução dos casos.

Obrigado pelo vosso trabalho!

**Comment by ishouldbedany** [comment]
Olá @pgaspar, 

Tens bastante razão e neste momento a falta destes dados é um grande foco de polémica. Não estão disponíveis absolutamente em lado nenhum. Recomendo o Twitter do [Jorge Gomes](https://twitter.com/jmgvostpt), da VOST Portugal, em que ele explora bastante este assunto. A mais recente _thread_ dele acerca do assunto é [esta](https://twitter.com/jmgvostpt/status/1325832943986733061), por exemplo.

Aguardamos ansiosamente 😬

**Comment by joa-quim** [comment]
Boas,

Com um bocado de trabalho e acreditando nas contas da DGS é possível inverter o número do rácio para obter os dados dos concelhos. Para verificar e porque são só 18 concelhos fiz as contas à mão para o Algarve. O que fiz foi:

```
# Peso relativo da população de cada concelho do Algarve
p = [5154 5594 30374 5077 55483 22762 36226 41528 68697 61015 10416 44405 24530 2159 6237 18749] ./ 438406

# Média pesada do rácio usando os números dos rácios retirados da página da ESRI
sum([466 18 244 0 258 163 163 284 215 349 326 194 245 93 96 288] .* p)
241.6

# Rácio para o Algarve no período 28 Dez - 10 Nov retirado dos dados diários
(3558-2526)/438406 * 100000 
235.4
```
 Como vêm a diferença é pequena e poder-se-á explicar por algumas diferenças de arredondamentos (os números dos rácios são-nos dados em números inteiros) bem como a DGS ter números ligeiramente diferentes. Recordemos que cada vez que eles detectam erros (e já houve vezes em que os acumulados diminuiram) nunca "republicam" as correcções.

**Comment by davipt** [comment]
Já descobri a API com os dados por 100k… deixem-me testar umas coisas e já faço uma proposta.

Recordo que adicionei há uns dias os dados de população do INE de 2019 e um notebook de exemplo para converter os dados acumulados do data_concelhos.csv, em dados de 100k+14dias conforme se têm agora.

Aplicar a formula inversa aos novos dados de incidência irá dar uma aproximação dos confirmados em 14 dias, mas será arriscado adicionar esses valores ao acumulado do data_concelhos.csv, pois iríamos estar a adicionar potencial erro a cada update, e esse dados já tinham um erro de 18% no dia 26 de outubro, depois de meses com apenas 9% de desvio.

Mas ter um ficheiro novo a incidência, confirmados a 14 dias, e mais uma série de informação interessante, incluindo recalcular o histórico actual, pode funcionar…

**Comment by pmoura11** [comment]
@davipt se o método que estás a avaliar é o `IncidenciaCOVIDporConc100k_view`, acho que vamos ter um problema com a data, não?

**Comment by davipt** [comment]
Sim, é verdade. Não vai ser nada agradável.

**Comment by davipt** [comment]
@pgaspar @joa-quim podem dar uma espreitadela e ver se isto faz algum sentido?

Tenho um branch de testes em https://github.com/dssg-pt/covid19pt-data/compare/master...davipt:temp que inclui:

1. https://github.com/davipt/covid19pt-data/blob/temp/data_concelhos.csv
Corrigido valores de CALHETA Madeira vs. Açores devido a abuso de CALHETA sem sufixo quer no boletim quer na API.
Parece-me que os valores históricos são dos Açores, mantendo-se a 4 recentemente, e é a da Madeira que cresceu desde Julho e que está com incidência nos valores novos (até na api nova está com a calheta errada)
Idem para Lagoa Faro (com casos) e Açores (só recente)
Correção de outros 3 valores que estavam vazios na API mas disponíveis no boletim. (erros de introdução devido a acentos tipo Mêda)

2. https://github.com/davipt/covid19pt-data/blob/temp/data_concelhos_new.csv
Criei um novo ficheiro com uma estrutura temporária, normalizada, com data+concelho como key, com os valores de incidência e tudo o resto disponível na API (população, etc.), e o calculo de confirmados_14 dias via incidência/população, e confirmados_1 com "média diária" (14 dias div 14)

3. https://github.com/davipt/covid19pt-data/blob/temp/data_concelhos_14.csv
Este é a conversão do ficheiro de concelhos calculando a diferença para 14 dias, a partir da altura que os dados passaram a ser semanais. São as linhas até 26-10-2020.
Isto depois permite adicionar novas linhas com os dados de incidência (apenas 16-11-2020 neste momento), sendo os valores comparáveis (seriam, se não houvesse erros de introdução na plataforma… 18% a 26-10!)

4. https://github.com/davipt/covid19pt-data/blob/temp/data_concelhos_ecdc.csv
Idem, igual a 3, mas com os valores de incidência por 100k.

Qualquer sugestão e feedback serão bem vindas.

**Comment by davipt** [comment]
@pgaspar @joa-quim os dados de concelho disponíveis já estão a ser actualizados há 11 semanas conforme descrito no README:

`data_concelhos_14dias.csv` e `data_concelhos_incidencia.csv` contém dados de confirmados do acumulado dos 14 dias anteriores à data do reporte, no primeiro ficheiro, e proporcional a 100k habitantes no segundo ficheiro. Inclui os dados calculados do data_concelhos.csv desde que os daddos são semanais, nomeadamente entre 27-07-2020 (correspondendo ao periodo de 13-07-2020 a 26-07-2020) até 26-10-2020, e será actualizado conforme seja disponibilizado pela DGS (semanalmente à segunda-feira).

https://github.com/dssg-pt/covid19pt-data/blob/master/data_concelhos_incidencia.csv
https://github.com/dssg-pt/covid19pt-data/blob/master/data_concelhos_14dias.csv

Podemos fechar este issue? Obrigado.
