### ISSUE TITLE
Erro dia 16/11

### ISSUE THREAD

**Issue by pinanunes** [dssg-pt/covid19pt-data#409]
Há um desfasamento entre o número de confirmados_novos no dia 16/11 e a diferença do número de confirmados cumulativos entre o dia 15 e o dia 16/11.

**Comment by paulomaia20** [comment]
Olá @pinanunes,

O erro parece ser diretamente da fonte, devido à DGS ter atualizado os casos que estavam em atraso totalmente neste dia... Uma das colunas provavelmente corresponde aos casos novos desse dia, e a outra à diferença entre o dia anterior e os desse dia (que inclui os acumulados). Não sei se devemos deixar assim ou fazer alguma correção.

**Comment by davipt** [comment]
Na minha opinião deve-se corrigir manualmente o confirmados_novos de dia 16 para 8371 pois não é relevante se houve 3996 nesse dia e 4375 "algures nos dias anteriores" quando não se sabe em que dias e quantos foram. Os boletins anteriores não foram alterados. Os dados na API não foram alterados. Logo, para consistência com casos anteriores de dumping de valores em falta, para todos os efeitos houve mesmo 8371 confirmados nesse dia, tal como houve mais confirmados que o valor diário real para os valores das ARS. É o que é.

**Comment by davipt** [comment]
@paulomaia20 se não te importares, corrigi o valor no mesmo PR em https://github.com/dssg-pt/covid19pt-data/pull/412 para evitar conflitos no commit.
