### ISSUE TITLE
Adição novamente da coluna dos casos de género desconhecido

### ISSUE THREAD

**Issue by paulomaia20** [dssg-pt/covid19pt-data#411]
A partir do dia 15/11, os relatórios têm uma nova métrica "confirmados_desconhecidos", relativamente ao género dos confirmados.

Temos de criar uma nova coluna (a que temos dos confirmados_desconhecidos_f é relativamente à idade), corrigir manualmente os valores e nos testes unitários somar também os desconhecidos.

A fonte que estamos a usar não parece ter esse valor dos desconhecidos. @davipt, tinhas encontrado outra?

Fonte: https://services.arcgis.com/CCZiGSEQbAxxFVh3/ArcGIS/rest/services/COVID_Concelhos_DadosDiariosARS_VIEW2/FeatureServer/0/query?where=ConfirmadosNovos+%3E+0&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=Data+desc&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=html&token=

**Comment by davipt** [comment]
Nope, não vejo o valor em nenhum campo do arcgis. 

Na minha opinião devia-se desactivar o teste de "confirmados = confirmados_f + confirmados_m" e alterar o extract para calcular o confirmados_desconhecido novo como "confirmados - f - m" e confiar que esteja certo com o boletim. 🤷‍♂️

**Comment by davipt** [comment]
Ve lá se isto ajuda https://github.com/dssg-pt/covid19pt-data/pull/412
