### ISSUE TITLE
Dados incorrectos dia 16/11/2020

### ISSUE THREAD

**Issue by FRosa3560** [dssg-pt/covid19pt-data#424]
Algo está errado com os dados existentes no que diz respeito aos confirmados novos, no dia 16-11-2020 no site [oficial ](https://covid19estamoson.gov.pt/estado-epidemiologico-covid19-portugal/) para esse dia é de **3996** e nos dados do ficheiro  [data.csv](https://github.com/dssg-pt/covid19pt-data/blob/master/data.csv)  **8371**.

**Comment by davipt** [comment]
De acordo com o boletim desse dia https://covid19.min-saude.pt/wp-content/uploads/2020/11/259_DGS_boletim_20201116-004.pdf

> No entanto, os dados cumulativos foram atualizados historicamente, resultando em +4 375 casos confirmados,

3996 + 4375 = 8371

O mesmo se passa para os outros valores ajustados nesse dia, como os confirmados por região, os recuperados e os ativos

ARS Norte no boletim => 2101 + 2063 = 4164
ARS Norte no CSV, diferença de dia 16 para 15 => 114025 - 109861 = 4164

Ou seja, vários valores foram ajustados, mas sem se saber a que dias correspondem esses ajustes (pois foram valores incorrectos durante vários dias), portanto tal como fizeram no boletim e na dashboard da DGS (de onde se obtém os valores) a soma dos valores reais desse dia com os ajustes só podem ser atribuídos ao próprio dia, para que as linhas do CSV continuem a dar conta certa de dia para dia.

**Comment by fbatista72** [comment]
Bom dia
A DGS actualizou apenas a série nacional no dia 16 de novembro no 
https://www.worldometers.info/coronavirus/country/portugal/
Podem ver na informação dos "Updates" da página de Portugal.
