### ISSUE TITLE
[BUG] DATA MISSING in data.csv and Date Format

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [dssg-pt/covid19pt-data#431]
### ISSUE
data.csv file is missing values for 2020/10/26 regarding total confirmed cases by gender and age segment. 
When imported, the "data" field seems to be a mix of plain text and date format. 

### SOLUTION
Manually add values according to the official DGS bulletin:

Grupo etário | Homens | Mulheres | Desconhecido
-- | -- | -- | --
0-9 | 7341 | 6885 | 245
10-19 | 12326 | 12670 | 266
20-29 | 20498 | 23682 | 1495
30-39 | 19486 | 23520 | 989
40-49 | 20537 | 26733 | 752
50-59 | 18006 | 23543 | 501
60-69 | 12949 | 14091 | 294
70-79 | 8148 | 9126 | 174
80+ | 6995 | 14261 | 325
Total | 126286 | 154511 | 5041

Fix "data" field format to either date or plain text.

**Comment by ishouldbedany** [comment]
Olá @JorgeMiguelGomes!

Presumo que te referes ao 2020-11-26, certo? (relatório de ontem) 

Na dashboard não fizeram actualização dos dados segmentados. Ainda não colocámos esses no repositório, estávamos na esperança que hoje fizessem correcções retroactivas (que não fizeram). 

Qual a fonte dos que colocas acima? Parecem-me ser os do boletim de hoje, 27 de Novembro. Os do boletim de 26 de Novembro, na API que utilizámos, estão iguais aos do dia 25.

**Comment by JorgeMiguelGomes** [comment]
Olá, @ishouldbedany !
Estou mesmo a referir-me aos dados de 26 de Outubro.

**Comment by ishouldbedany** [comment]
@JorgeMiguelGomes Mas a 26 de Outubro tínhamos ~120k casos confirmados totais, daí a minha confusão relativamente a esses números.

**Comment by JorgeMiguelGomes** [comment]
> @JorgeMiguelGomes Mas a 26 de Outubro tínhamos ~120k casos confirmados totais, daí a minha confusão relativamente a esses números.

E tens razão @ishouldbedany, erro meu. Falhou qualquer coisa do meu lado, desculpa.

Podes fechar essa parte.

**Comment by ishouldbedany** [comment]
@JorgeMiguelGomes Mas tiveste algum outro problema a importar os dados desse dia? Porque tentei agora e não tive problemas de maior.

**Comment by JorgeMiguelGomes** [comment]
Não, o problema está mesmo num transpose que fiz dos dados para outra folha, para produzir mais uns gráficos.

**Comment by ishouldbedany** [comment]
O clássico entre a cadeira e o ecrão :laughing:  Assim sendo vou fechar.
