### ISSUE TITLE
Atraso de 2 dias nos dados COVID

### ISSUE THREAD

**Issue by JoseGamerPT** [dssg-pt/covid19pt-data#465]
Antes de mais agradeço a disponibilidade da API relativa aos dados covid.
Mas porque é que a latest update da vossa api não retorna os valores mais recentes? Está com um atraso de 2 dias
Obrigado pela atenção

**Comment by davipt** [comment]
Os dados de ontem, 27, só foram publicados hoje, 28, algures nas ultimas horas (são 14h). Estes vão ser actualizados em breve. Os dados de hoje 28 ainda não estão disponíveis.

**Comment by JoseGamerPT** [comment]
Têm razão, pensei que havia um longo atraso, mas foi erro meu.
Obrigado eu!
