### ISSUE TITLE
Plataforma eVM - Vigilância da Mortalidade

### ISSUE THREAD

**Issue by joaopalmeiro** [dssg-pt/covid19pt-data#48]
A DGS e outras entidades mantêm uma plataforma chamada [_eVM - Vigilância da Mortalidade_ ](https://evm.min-saude.pt/) onde disponibilizam dados/informação de mortalidade em Portugal (mais info [aqui](https://evm.min-saude.pt/#shiny-tab-info_eVM)) — talvez seja uma fonte de dados interessante para algumas análises.

Caso já conheçam esta plataforma, ignorem este _issue_, por favor.

**Comment by paulomaia20** [comment]
Viva João,

Estava no nosso backlog mas ainda não criamos um issue. Sabes se há alguma API que permita sacar facilmente os dados daí?

**Comment by joaopalmeiro** [comment]
Pelo que pesquisei, não existe nenhuma API pública para tal...

O pessoal da [Central de Dados](http://centraldedados.pt/obitos/) criou um script para recolher estes dados, mas já tem algum tempo (e a hiperligação aponta para uma página antiga, que atualmente foi substituída pela plataforma eVM).

**Comment by lfsimoes** [comment]
Têm aqui um script com o qual podem fazer scraping dos dados de mortalidade diária do eVM:

https://nbviewer.jupyter.org/gist/lfsimoes/5543f5295350b8df2f8e9bdfbc2ee0dd?flush_cache=true

**Comment by paulomaia20** [comment]
Obrigado @lfsimoes. Vamos avaliar e criar um dicionário de dados com esse dataset :)

**Comment by paulomaia20** [comment]
Vou fechar, reformulamos isto para um mini-projeto, e sugerimos às pessoas começar pelo código que enviaste acima: https://github.com/dssg-pt/covid19pt-data/issues/150

**Comment by lfsimoes** [comment]
O eVM fez entretanto um update ao site, e a tabela da mortalidade geral passou a estar noutro URL. O código que eu tinha partilhado anteriormente deixou então de funcionar. Já o actualizei: https://nbviewer.jupyter.org/gist/lfsimoes/5543f5295350b8df2f8e9bdfbc2ee0dd
