### ISSUE TITLE
Clarificar Dados de 16 Março

### ISSUE THREAD

**Issue by dssgPT** [dssg-pt/covid19pt-data#5]
Valores Totais reportados não são coerentes com os dados por faixa etária e por género (faltam dados de uma pessoa)

**Comment by augustoamerico** [comment]
O mesmo acontece para os valores por zonas geográficas (também falta uma pessoa)

**Comment by dssgPT** [comment]
Sim exacto, penso que deve ter sido um erro ou falta de informação. Não sei se será possível obter esta informação com base no report de hoje. Talvez seja importante informar isto no README.

**Comment by ishouldbedany** [comment]
Fechando por estar fora do nosso controlo, foi erro da DGS. De qualquer das formas, vou colocar a issue como "Pinned" para toda a gente conseguir ter acesso rápido.
