### ISSUE TITLE
Dados de vacinação - 05/02/2021

### ISSUE THREAD

**Issue by alicescfernandes** [dssg-pt/covid19pt-data#539]
Até à data (05/02/2021, 16h), os dados da ESRI continuam a vir desatualizados. Com base [neste link](https://www.sns.gov.pt/monitorizacao-do-sns/vacinas-covid-19/), proponho fazer o bump do com os seguintes:

`{
Data: 1612483200000,
Inoculacao1: 284462,
Inoculacao1_Ac: 284462,
Inoculacao2: 94916,
Inoculacao2_Ac: 94916,
Vacinados: 379378,
Vacinados_Ac: 379378,
FID: 1
}`

**Comment by alicescfernandes** [comment]
Updated

**Comment by davipt** [comment]
Obrigado Alice. 👍
