### ISSUE TITLE
Stability of CSV files

### ISSUE THREAD

**Issue by owahltinez** [dssg-pt/covid19pt-data#55]
Hi, first of all thanks so much for this -- awesome work! I am now using your CSV files to add region-level data to my [Open COVID-19 project](https://github.com/open-covid-19/data).

I am currently pulling your CSV file from [the GitHub Raw cache](https://raw.githubusercontent.com/dssg-pt/covid19pt-data/master/data.csv) and I wanted to understand how stable these files are, whether you are likely to change the name, location, format, etc. In case of any changes, how can I be notified so I can update my scripts appropriately?

**Comment by paulomaia20** [comment]
Hi Oscar,

Thank you for the question.

If we add a new field, it will be appended in the right of the csv file, to enable backwards compability. Filenames and formats will not be changed unless there is an error. We also have Github Actions validating column names and dtypes. 

We have an API for downloading such data, no need to download it from the Github cache:

https://rapidapi.com/gitgrupoift/api/covid-19-dados-abertos 

So if there's any change the API should be updated to reflect it
