### ISSUE TITLE
Vaccination data at regional level

### ISSUE THREAD

**Issue by lucasrodes** [dssg-pt/covid19pt-data#607]
Hi, 
I am helping to gather regional data for as many countries as available in this project: https://github.com/sociepy/covid19-vaccination-subnational and I wondered if you had any visibility on vaccination campaign data availability at concelho's level. I haven't been able to find any so far...

Thanks for your help and time

**Comment by davipt** [comment]
Hello Lucas.

I'm personally not aware of information per municipality / concelho.

The most we have is per ARS (health area) - https://covid19.min-saude.pt/relatorio-de-vacinacao/ (also backed up on this repo inside extra/vacinas, and soon also pre-parsed https://github.com/dssg-pt/covid19pt-data/pull/651 )

Also be aware that typically published data por Portugal is related to mainland only, excluding Madeira and Açores islands, hence why the dataset reports to about 9.8 million people, lacking the 2 times 250K for each set of islands.

There is also information published on the ECDC site, but that is also only per region, not municipality. However, the ECDC dataset does contain regions and ages per vaccine brand. :)

**Comment by davipt** [comment]
Hello agan Lucas.

As stated before, the only information published by the official authorities only includes numbers per region (health regions - north, center, lisbon area, Alentejo, Algarve, then Madeira and Açores islands).
This applies both to the national numbers, published weekly, and available on this repository at `vacinas_detalhe.csv` as well as the same information published into the ECDC site, with the advantage that there the data is also divided by vaccine brand.

Currently the numbers for Açores are still less than the real vaccination numbers, about 60%, but that should be improving on the next weeks.

Thanks for the question.
