### ISSUE TITLE
Dados concelhos desatualizados

### ISSUE THREAD

**Issue by RenatoCarvalho97** [dssg-pt/covid19pt-data#649]
Bom dia.

Hoje, no dia 22/03/2021, os ficheiros 'data_concelhos_incidencia.csv' e 'data_concelhos_14dias.csv', que servem de fonte para os dados retornados pela VOST API, apresentam informação respetiva à sua ultima atualização (dia 10-03-2021). Contudo, no dashboard da DGS podemos verificar que a última atualização para os dados dos concelhos, mais especificamente nas incidências cumulativas, foram atualizados pela última vez no dia 15-03-2021.
Poderá haver um problema com a recolha e atualização destes dados.

Obrigado.

**Comment by davipt** [comment]
Olá Renato.

As datas nos vários ficheiros CSV no repositório correspondem a "dados até á meia noite dessa data", independentemente da data em que os valores são reportados ao público.

O relatório PDF publicado na segunda feira 15 de março indica o seguinte no topo da página:
"CONCELHO / INCIDÊNCIA CUMULATIVA A 14 DIAS (24/02/2021 a 09/03/2021) / GRUPO DE INCIDÊNCIA"

Daqui vem a data de 10/03/2021, pois são dados dos 14 dias anteriores a essa data.

Os dados que serão publicados hoje, segunda 22, poderão ou não manter uma cadência de 7 dias. Têm sido estável recentemente, mas não era o caso no passado.

Temos um README com um apanhado das datas do inicio e final dos 14 dias, e da data to relatório, em:
https://github.com/dssg-pt/covid19pt-data/blob/master/extra/concelhos_incidencia/README.md

Faz sentido?
Obrigado.

**Comment by RenatoCarvalho97** [comment]
Sim, faz todo o sentido.

Obrigado pelo esclarecimento.
