### ISSUE TITLE
impossivel fazer query para 1 dia antes ao dia de hoje

### ISSUE THREAD

**Issue by rubentomas** [dssg-pt/covid19pt-data#693]
Boa tarde,

o problema: Desde hoje que não consigo obter os dados do dia presente.

Por norma o query inicia a “hoje - 1dia”.
desde hoje pela manhã que apenas consigo fzr query “hoje - 2dias”.

será que as regras mudaram?

**Comment by davipt** [comment]
Boas.

Os dados oficiais só estão disponíveis até dia 4 (vide https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/).

Há uns minutos actualizei manualmente os dados de ontem (faltam os confirmados e obitos por idade quando são actualizados manualmente), e daqui a uns minutos actualizo os dados de hoje, manualmente e sem dados por idade novamente, caso não haja actualização dos dados oficiais novamente.

Neste momento já deverá funcionar "hoje-1 dia". Confirmas?

Obrigado.

**Comment by rubentomas** [comment]
Confirmo sim.
Os dados de dia 05 já estão on-line.

(Agora só estou em dúvida como vou lidar com a variação em termos de code 😀)

**Comment by davipt** [comment]
Idealmente não deveria haver falta de dois dias de dados na dashboard oficial da DGS e na base de dados da ESRI.

Geralmente esperamos até ao fim do dia, e se não houver dados, copiamos os dados disponíveis no PDF (como disse, sem os valores por idade de confirmados e óbitos, que o PDF tem o gráfico mas não tem valores) para que o job no GitHub possa tratar de tudo direitinho, incluindo o tweet, mas ontem "life gets in the way" e passou-se a noite e esqueci-me 😔

Actualizei também os dados de hoje, dia 6, manualmente, mas no entretanto já actualizaram os dados oficiais na API para hoje, embora não o tenham feito para ontem.

**Comment by davipt** [comment]
Obrigado!
