### ISSUE TITLE
INSA historical Rt backlog

### ISSUE THREAD

**Issue by rcarmo** [dssg-pt/covid19pt-data#705]
I’m curious as to whether there are any plans to incorporate the backlog from http://www.insa.min-saude.pt/category/areas-de-atuacao/epidemiologia/covid-19-curva-epidemica-e-parametros-de-transmissibilidade/ since it might round out the dataset for Rt rather nicely.

(filing this from a mobile device, so all I can add is that the data seems to be in Excel format, but with mostly matching columns)

**Comment by davipt** [comment]
Sim. Faz sentido consolidar os dados num único permalink, e normalizar o formato.

**Comment by davipt** [comment]
Vê lá se faz sentido

https://github.com/dssg-pt/covid19pt-data/blob/rt-10-04-2021/rt.csv

https://github.com/dssg-pt/covid19pt-data/tree/rt-10-04-2021

https://github.com/dssg-pt/covid19pt-data/pull/708/files

**Comment by rcarmo** [comment]
LGTM 👍

**Comment by davipt** [comment]
Merged. Depois vou ajustando o automatismo, principalmente quando chegar a maio e mudarem outra vez o url. Obrigado!
