### ISSUE TITLE
Dados por grupo etário 29/out/2020

### ISSUE THREAD

**Issue by JPBraga1** [dssg-pt/covid19pt-data#714]
Boa tarde,

Faço acompanhamento ocasional da informação sobre Portugal dos dados COVID, quer através dos dados oficiais do site da DGS, quer da informação diaria do público (que vai também buscar a informação ao site), guardando alguma informação em excel normalmente um dia por semana.

Estava a ver os dados que têm disponíveis no site e verifiquei que tem em falta os dados por grupo etário para o dia 29/out/2020. Por mero acaso, tenho essa informação em excel, dado que calhou ser um dos dias em que recolhi informação.

Deixo aqui a informação que tenho disponível:

2914 | 2579 | 4607 | 4763 | 10689 | 11780 | 9979 | 11434 | 9695 | 12216 | 8386 | 10781 | 6122 | 6687 | 3989 | 4432 | 3795 | 7584

Ao contrário do vosso site, tenho primeiros os homens e depois as mulheres

**Comment by davipt** [comment]
Pois… esse dia é para esquecer.

Na API da dashboard esse dia não existiu - ou melhor, existe, mas têm exactamente os mesmos valores que dia o dia anterior, 28.

Segundo o boletim houve 132 616 confirmados, 60 271 homens e 72 345 mulheres. A soma destes dois dá o total.
A soma dos valores que partilhaste dá 132 432 confirmados, 60 176 homens e 72 256 mulheres.
Faltam pessoas. 🤔

Reparei também que os valores de óbitos estão incorrectos, sendo os de dia 28.
Vou corrigir os obitos_m e _f e ter de apagar os óbitos por idade.

Lembraste de onde obtiveste esses dados por idade?

Obrigado desde já.

**Comment by JPBraga1** [comment]
Relativamente à soma dos dados dos óbitos por idade ser diferente do total, isso é normal. 

Devem existir casos em que não tem a certeza da idade e não distribuem por grupo etário e só colocam no total (e vão ajustando com a passagem dos dias, no caso de receberem informação adicional). Nos dias anteriores e precedentes tem uma diferença muito próxima entre as duas medidas (total e total por soma dos grupos etários) face à diferença que dá no caso dos números que passei, o que é um bom indicador para os números serem os efetivos.

Não tirei distribuição dos óbitos para esse dia (o site do público também tem essa informação e por vezes recolhia, mas mais espaçada).

**Comment by davipt** [comment]
Tens razão.
A soma dos óbitos bate sempre (*) certa entre obitos total, soma obitos_f e _m, soma obitos por região, e obitos por idade.
(*) tenho um obito em falta no dia 19-06-2020 que não vou mexer agora, e os dois dias com dados em falta 05-10 e 29-10

No entanto com as somas de confirmados embora a soma de _f e _m e por região batam certo, as por idade só batem certo quando são combinadas com o _desconhecidos inicial, ou o novo _desconhecido_f e _desconhecido_m mais tarde.

Nessa altura estavam em transição e realmente não vão bater certo pois o _desconhecido_f/_m não estavam ainda actualizados correctamente.

Vou então usar os teus números para dia 29 e aproveitar para corrigir outros valores por perto.
https://github.com/dssg-pt/covid19pt-data/pull/715

Obrigado!

**Comment by JPBraga1** [comment]
Foi ver melhor o meu ficheiro e também tenho os dados dos óbitos para 29/10

0 | 1 | 0 | 0 | 2 | 1 | 2 | 3 | 14 | 11 | 50 | 24 | 148 | 67 | 300 | 179 | 726 | 900
(mais uma vez com masculino/feminino trocado face ao vosso ficheiro)

O do dia 5/10 não tenho (por pouco, dado que tenho o dia 6!)

**Comment by davipt** [comment]
https://github.com/dssg-pt/covid19pt-data/pull/717 muito obrigado!
