### ISSUE TITLE
[Mini-projecto] RT com valores acima de 0 a partir de 21/02/2020. Só existiram casos a 02/03/2020.

### ISSUE THREAD

**Issue by Ines1306** [dssg-pt/covid19pt-data#719]
**🤔 Contexto**:

**🥅 Objectivo**:

**👥 Tamanho máximo da equipa**:

**🎯 Resultado final esperado**: 

**🧱 Principais etapas**:

--- 

Se estás interessado em pegar neste mini-projecto, diz coisas aqui em baixo ⬇️

**Comment by davipt** [comment]
Discussão está em https://github.com/dssg-pt/covid19pt-data/discussions/721
