### ISSUE TITLE
Data value is returning “NULL”

### ISSUE THREAD

**Issue by rubentomas** [dssg-pt/covid19pt-data#754]
Olá, estou a meio de construir um webapp de cálculos covid.
Tenho trabalhado sem problemas. Hoje notei que algumas das “propriedades do objecto” vêm com “null” value.
Caso dos dados micro das mortalidades.
Apenas aparece dados macro (os totais absolutos).
Alguma razão?

estão a deixar de alimentar algumas entries (null) ou é apenas um bug que está-se a resolver?

**Comment by davipt** [comment]
Olá Ruben. Estás a referir aos valores diários no `data.csv` para `confirmados_*` e `obitos_*` por idades?

Isto acontece quando a dashboard da DGS não é actualizada a tempo, de onde obtemos os valores diários.
Quando não há dados, carregamos manualmente os dados disponíveis no boletim PDF, que tem os outros dados todos menos os por idade - estes estão no gráfico, mas não tem valores.

Podes verificar em https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/ que neste momento só há dados de dia 22, faltando os de 23 e 24. Isto começa a ser típico ao fim de semana, e eventualmente os dados aparecem, ou ao fim do dia, ou ao domingo à noite, ou no pior dos casos na segunda à hora de almoço.

No entretanto terás de assumir no teu código que valores vazios são valores desconhecidos, como descrito no README, mas que poderão aparecer mais tarde.

Isto é também a razão pela qual o bot em https://twitter.com/CovidometroPT só faz três tweets em vez de quatro - falta os dados por idade. Se os dados forem publicados ainda hoje, o bot relança os quatro tweets. Senão, só amanha.

**Comment by rubentomas** [comment]
Fico mais descanso. É que eu ontem pensava que o bug era do meu code. Andei a refazer tantas funcs. Ora dava pra não aparecia 😭😭🤣🤣💀
Devo ter refeito 100 linhas de JS.

então assim há pouco que eu possa fazer com o meu código. Vou criar alertas de *estado dos dados* 
Se der null, vou criar uma interface que informa o período de atualização. 

Muito obrigado pela ajuda 🙏🏾 🦠 🙅‍♂️

**Comment by davipt** [comment]
Acabadinhos de sair do forno… da API da dashboard!

https://github.com/dssg-pt/covid19pt-data/pull/755

Ainda assim há um dia em outubro 2020 que nunca conseguimos descobrir os valores em falta. Considera sempre que pode haver algum valor desconhecido nesse dia.

**Comment by davipt** [comment]
Prepara-te para mais dias com os valores de confirmados e óbitos *por idade* em falta, temporariamente, ou quiçá até permanentemente. Faltou mais uma vez os dados de dia 25 e 26 (e 23 e 24 antes), e hoje actualizaram os de ontem 26, mas não os de 25.
