### ISSUE TITLE
amostras.csv

### ISSUE THREAD

**Issue by tiagoad** [dssg-pt/covid19pt-data#759]
Olá a todos,

No dia 23 o ficheiro amostras.csv mostrou 0 novas amostras totais, enquanto que o número de novas amostras PCR e antigénio subiram. Existe agora uma divergência entre a coluna 'amostras' e a soma das colunas 'amostras_pcr' e 'amostras_antigenio'.
Sabem explicar o que se passa aqui? Problema com a qualidade de dados da DGS?
Por agora descartei a coluna 'amostras' e passei a usar a soma das outras duas.

Abraço e continuação de excelente trabalho,
Tiago

**Comment by davipt** [comment]
Adicionei dois testes para que não volte a acontecer.

Sim isto são os dados oficiais de acordo com a [dashboard](https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/) e não é inesperado que haja valores incorrectos, embora não o tenha acontecido há meses. Não é grave pois os valores são actualizados retroativamente e hoje já houve correção dos valores de 21 a 24 inclusive.

Essa actualização estará disponível dentro de minutos, indo junto com os dados diários disponíveis para hoje.  Obrigado.

**Comment by davipt** [comment]
Actualizado em master:
https://github.com/dssg-pt/covid19pt-data/pull/760/files#diff-6c618602ab7e45ccbaed4b126f307e26fc5cf362d13395c3c9d33bb5bf0d085f

Podes confirmar se agora já está correcto?

**Comment by tiagoad** [comment]
Confirmo que está tudo OK! Obrigado :)
