### ISSUE TITLE
Converter cronologia Wikipedia para CSV

### ISSUE THREAD

**Issue by paulommaia** [dssg-pt/covid19pt-data#8]
https://pt.m.wikipedia.org/wiki/Pandemia_de_COVID-19_em_Portugal

**Comment by dssgPT** [comment]
Sugerido por https://twitter.com/tarantulae/status/1239796864309964801?s=20

Transformar lista de medidas do governo para tentar perceber o seu impacto no futuro.

**Comment by perone** [comment]
Obrigado pelo excelente trabalho e por aceitar a sugestão !

**Comment by ishouldbedany** [comment]
Faz sentido incluir todas ou incluímos apenas as mais relevantes? E, se esta última, o que se considera relevante - directivas do Governo (ignorando as iniciativas tomadas por privados, independentemente do seu tamanho e influência no país)? 

Ou usamos um critério de impacto, i.e., medidas que afectem um grande número de pessoas? Por exemplo, o fecho de uma mercearia em Bragança é um evento mínimo quando comparado com o encerramento de todos os Solincas do país.

**Comment by perone** [comment]
Acho que só as mais relevantes faz mais sentido neste momento, as que tem grande impacto (esperançosamente). Algo relacionado: https://coronavirus.skoposlabs.com/

**Comment by Goldesel23** [comment]
Primeira versão adicionada na pasta extra/medidas_governamentais. 

Caso alguém veja alguma coisa em falta adicionem pf.
