### ISSUE TITLE
Testes efetuados em Portugal

### ISSUE THREAD

**Issue by f13arnabe** [dssg-pt/covid19pt-data#81]
Boa tarde,

alguém sabe onde podemos consultar ou até incluir os dados sobre testes efetuados na população portuguesa para criar análises de Total Testes vs Total Confirmados ?

Melhores cumprimentos e continuação de bom trabalho :)

**Comment by tensorfreitas** [comment]
Olá @f13arnabe 

O mais próximo que temos do total de testes é o número de casos suspeitos a aguardar resultados laboratoriais. Se consultares o dicionário dos dados no README, consegues verificar quais as duas colunas de interesse.

**Comment by f13arnabe** [comment]
Olá @tensorfreitas ,
realmente faz todo o sentido.
Nem me lembrei desse "pormenor", de casos suspeitos serem baseados em testes efectuados à espera de resultado.
Obrigado pela rápida resposta 👍

**Comment by ishouldbedany** [comment]
Complementando, a [_dashboard_ da DGS](https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/) tem informação diária do número de amostras processadas (painel do canto inferior direito, 2º separador para a esquerda). 

Só parece existir aqui e não conseguimos descobrir qual a fonte e qual a metodologia utilizada para os recolher, pelo que temos evitado incluí-las. 

Como o @tensorfreitas , o número de pessoas a aguardar resultado laboratorial é um bom _proxy_ para esse valor. Mesmo o número de amostras na _dashboard_ da DGS é dúbio, na medida em que 1 amostra não corresponde necessariamente a 1 paciente, como a DGS já várias vezes explicou em conferência de imprensa.

**Comment by filipafcastro** [comment]
Estou a trabalhar em extrair do [_dashboard_ da DGS](https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/) os dados disponíveis sobre testes, para cada dia:
- número total de amostras;
- número de amostras novas.

Há dois aspetos especialmente relevantes a ter em conta relativamente a estes dados:
- existe um _delay_ de cerca de 1 a 3 dias na atualização dos dados;
- por vezes, os números já divulgados sofrem alterações.

Estes dois motivos obrigam-nos, a cada dia, a atualizar linhas antigas, relativas a dias passados. Como tal, a melhor opção será ter um .csv separado para estes dados. Para além disso, e porque não sabemos que alterações esperar a cada dia, a minha ideia seria, todos os dias, fazer um update de todas as linhas do .csv, conforme os dados disponíveis naquele momento. O objetivo também será integrar este script no _workflow_ automático que temos.

**Comment by f13arnabe** [comment]
Olá @filipafcastro , onde consigo encontrar esses números (total de amostras e amostras novas) ?
Vão adicionar esse csv aqui?

Obrigado :)

**Comment by filipafcastro** [comment]
@f13arnabe o número de amostras novas é um dos gráficos existentes no [_dashboard_ da DGS](https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/):
![image](https://user-images.githubusercontent.com/10077981/79644218-cbfb7f80-81a7-11ea-94ad-8389adedf94d.png)

O número total de amostras aparece no gráfico de _Evolução de Indicadores Gerais_. Sim, vamos adicionar aqui no repositório um novo .csv com esses dados. Conto que fique disponível ainda este fim-de-semana.

**Comment by f13arnabe** [comment]
Olá @filipafcastro , obrigado pela resposta :)

Já agora, sabes qual a diferença entre os casos suspeitos e "Aguarda Resultado Laboratorial" e como se relacionam com os Casos Suspeitos?

A diferença entre o número de casos suspeitos e amostras, suponho seja o total de testes efetuados até hoje dia 18 de Abril e os casos suspeitos sejam são os que aguardam confirmação de resultado, sendo esta diferença, entre 235878 e 162711, a soma dos confirmados com os casos que deram negativo.

**Comment by filipafcastro** [comment]
@f13arnabe [aqui](https://www.dgs.pt/directrizes-da-dgs/orientacoes-e-circulares-informativas/orientacao-n-002a2020-de-25012020-atualizada-a-250220201.aspx) podes encontrar a definição de caso suspeito, estabelecida pela DGS. Os casos que _Aguardam Resultado Laboratorial_ são casos suspeitos que fizeram o teste e cujo resultado ainda não é conhecido. Penso que podemos assumir que os casos que _aguardam resultado laboratorial_ são necessariamente casos suspeitos. No entanto, não sei se podemos assumir que todos os casos suspeitos são sujeitos a teste. Penso que não existe informação clara sobre isso. 

Não consegui perceber completamente a segunda parte da tua mensagem. De qualquer forma, acho que não podemos somar/subtrair, isto é, comparar diretamente amostras e casos porque um caso suspeito/testado pode corresponder a várias amostras. Por exemplo, existem pessoas que fazem dois testes para saber se estão infetadas. No caso de pessoas infetadas, podem vir a fazer ainda mais testes depois, para serem dadas como recuperadas.

**Comment by f13arnabe** [comment]
Olá @filipafcastro , não sendo o número de amostras diretamente proporcional ao número de pessoas suspeitas, fica difícil a análise de testes por habitante porque 3 amostras podem corresponder ao mesmo habitante e deveria apenas contar como um teste. Mas ainda assim ainda é alguma informação, ainda que desfasada, dos testes por habitantes em Portugal.

Obrigado pelo esclarecimento :)

**Comment by fbatista72** [comment]
Boa tarde
Vou começar por vos agradecer o excelente trabalho que estão aqui a realizar.
Estou a usar o vosso ficheiro data.csv para acompanhar o nosso país.
Sobre o tema, como os casos positivos são de novas situações deduzi que os casos negativos serão o outro resultado dos testes, assim eu defino como o numero de testes diários como a soma dos casos positivos + os casos negativos acrescentados diariamente. 
Obrigado

**Comment by filipafcastro** [comment]
@fbatista72 sim, para mim também faria sentido que os novos positivos + novos não confirmados correspondesse ao número de pessoas testadas. No entanto, não há nenhuma informação oficial que confirme isso. E a única informação oficial que existe diz respeito ao número de amostras, que também não nos permite comprovar essa teoria... 

Uma das limitações de assumir o número de novos positivos + número de novos não confirmados  como o número de testes diários é que nunca sabemos a que dia é que esses casos dizem respeito. Ou seja, no dia 18 de abril podemos ter 500 novos casos confirmados, mas 250 podem dizer respeito a testes feitos a 16 de abril e 250 a testes feitos a 12 de abril...

De qualquer forma acho que pode ser interessante perceber se o número de novos confirmados + número de novos não confirmados diário acompanha de forma +- proporcional o número de amostras diárias.

**Comment by marinhei** [comment]
Parabéns aos "carolas" que conceberam e mantêm estes repositórios.
Disponibilizam informação tratável a partir, segundo percebi, do **execrando** dashboard da DGS.
Em 2 de Abril pp perguntei à DGS onde poderia ter acesso aos dados brutos COVID consoante anexos, sem qualquer resposta até ao momento!
[Pedido a DGS acesso dados.pdf](https://github.com/dssg-pt/covid19pt-data/files/4505493/Pedido.a.DGS.acesso.dados.pdf)
[Pedido a DGS acesso dados RAW_signed.pdf](https://github.com/dssg-pt/covid19pt-data/files/4505495/Pedido.a.DGS.acesso.dados.RAW_signed.pdf)
Já trabalhava na indústria quando foi lançado o primeiro PC em Portugal
**Aparentemente o Estado Português, dignamente representado pela DGS, ainda está nesse tempo.**
É inacreditável que única a fonte de dados (?) que os cidadãos tinham fosse o **vergonhoso** dashboard da DGS.

- Muito Obrigado pelo vosso trabalho

**Comment by rtcsantotirso** [comment]
Olá @marinhei, obrigada pelo feedback! Os dados que estamos a disponibilizar são essencialmente extraídos dos relatórios que são diariamente publicados [aqui](https://covid19.min-saude.pt/relatorio-de-situacao/). Em breve esperamos ter também os dados relativos aos testes/amostras, esses sim extraídos do [_dashboard_](https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/). Felizmente temos recebido muitas contribuições e estes dados têm servido de base para muitas aplicações: https://www.dssg.pt/show-cases/. 

Relativamente à DGS, já nos colocamos à disposição para ajudar na estratégia de dados numa carta aberta, que pode consultar [aqui](https://docs.google.com/document/d/1Ce_CTcIZhDB2tzBV4jK8SkZYYpNF6wg3JtqaJlOZ43Q/edit) se tiver interesse :)

**Comment by filipafcastro** [comment]
Olá @marinhei, obrigada pelo feedback! Os dados que estamos a disponibilizar são essencialmente extraídos dos relatórios que são diariamente publicados aqui. Em breve esperamos ter também os dados relativos aos testes/amostras, esses sim extraídos do dashboard. Felizmente temos recebido muitas contribuições e estes dados têm servido de base para muitas aplicações: https://www.dssg.pt/show-cases/.

Relativamente à DGS, já nos colocamos à disposição para ajudar na estratégia de dados numa carta aberta, que pode consultar aqui se tiver interesse :)

**Comment by marianaferreira** [comment]
Olá @filipafcastro, muito obrigada pelo vosso trabalho incrível ao criar este repositório! Tenho interesse em obter os números totais de amostras por dia, tal como aparecem no dashboard da DGS, por exemplo 14 412 para 23/04 (ainda que com alguns dias de atraso). Já estão algures aqui no repositório? Muito obrigada!

**Comment by filipafcastro** [comment]
Olá @marianaferreira :) Obrigada pelo interesse no repositório! Sim, os dados relativos às amostras estão agora disponíveis no ficheiro [amostras.csv](https://github.com/dssg-pt/covid19pt-data/blob/master/amostras.csv). Estes dados vão ser atualizados todos os dias, por volta da hora do almoço, conforme a informação disponível no dashboard :)

**Comment by filipafcastro** [comment]
@f13arnabe @fbatista72 os dados sobre os testes/amostras já estão disponíveis!
