### ISSUE TITLE
Sintomas de febre e tosse trocados

### ISSUE THREAD

**Issue by filipafcastro** [dssg-pt/covid19pt-data#87]
Source: https://twitter.com/pedroramalhoc/status/1252136279388688386

_Nos vossos dados têm vários dias (1,2,6,7,8/Abril pelo menos) em q sintomas de febre e tosse estão trocados. Sugiro rever essas colunas. Tvz por terem ordem das colunas trocada em relação ao rel da DGS)_

**Comment by ishouldbedany** [comment]
Verifiquei manualmente todos os ficheiros. Encontrei mais algumas inconsistências, que creio deverem-se ao facto da DGS ter trocado a ordem febre / tosse na tabela a certa altura (e o nosso método semi-manual na altura deixou-se levar pelo hábito e não verificou isso). 

No PR anexo corrigi todas as que detectei, verifiquei que nos restantes sintomas as coisas faziam mais sentido (tendências coerentes ao longo do tempo) e ainda removi relatórios PDF duplicados, resultado de problemas de _merge_.
