### ISSUE TITLE
Dados Vacinas unidose

### ISSUE THREAD

**Issue by emanuelmarques** [dssg-pt/covid19pt-data#877]
Viva,

Já é possivel saber como são expostos os dados das vacinas de dose única? 

Estas doses entram para qual dos campos? Ou ainda não entram para nenhum?

Há alguma info relativa a este assunto?

Obrigado!

**Comment by davipt** [comment]
Olá Emanuel 

De acordo com o relatório semanal oficial da DGS as vacinas unidose entram directamente para a contagem de "totalmente vacinados", que inicialmente se chamava "doses2".

Há uns dias adicionei colunas adicionais ao `vacinas.csv` e descrição no `readme` para ficar mais claro que `pessoas_vacinadas_completamente` é igual ao `doses2` e `pessoas_vacinadas_parcialmente` é igual a `doses2` menos `doses1`. (PS: o que agora vejo que está errado pois devia retirar também as unidose)

Uma pessoa com as duas doses contará uma unidade para `doses1` e outra para `doses2`. Uma pessoa com Janssen conta apenas para `doses2`. Uma pessoa com a primeira dose conta apenas para `doses1`.

Só sabemos a distribuição por marca de vacina via os dados publicados no ECDC. Estou a processá-los mas não estamos ainda a copiar para este repositório. Podes ver exemplos no notebook temporário em https://github.com/dssg-pt/covid19pt-data/blob/master/notebooks/temp/temp_vacinas_ecdc.ipynb e o resultado no final da página em https://davipt.github.io/pages/

Basicamente, tal como foi feito no bot do Twitter https://twitter.com/PlenoDVacinacao tentamos contabilizar pessoas e não doses de vacinas. O "vacinados" é o "totalmente vacinados" do relatório, o "doses2", quem tem a unidose e quem tem a segunda dose das outras. O "mais xxx com 1ª dose" assim estará ligeiramente inflacionado, mas é apenas uma indicação de quantas pessoas estão a caminho da vacinação total.

 Obrigado

**Comment by JBacelarPT** [comment]
Viva Bruno,
Antes de mais, obrigado pelo vosso excelente trabalho. Gostaria de colocar algumas dúvidas quanto às vacinas.
1. Vi acima que as unidoses estão contabilizadas exclusivamente no **doses2** (corretamente, quanto a mim), mas no ponto explicativo da estrutura, é dito que "as vacinas unidose são contabilizadas como dose1 nos valores diários, embora sejam correctamente contabilizados e documentados como vacinação completa (doses2) no relatório semanal". Há aqui alguma incongruência? Como é que as unidoses estão, efetivamente, a ser contabilizadas?
2. O número de **vacinas** é superior ao de **doses**. Qual é a explicação? Tem a ver com os dados das ilhas?

Obrigado por tudo!

**Comment by davipt** [comment]
Sim, é um bocado confuso, mas tentei simplificar com os novos campos no vacinas.csv.

O doses/doses1/doses2 são os valores diários. Só contabilizam o continente, excluindo as ilhas. O doses são todas as vacinas administradas. O doses1 são todas as primeiras doses, incluindo as unidoses. O doses2 são todas as segundas doses. Uma pessoa com duas doses conta para doses1 e para doses2. 
Portanto pessoas totalmente vacinadas serão o doses2 mais quem levou Janssen e está misturado no doses1. Not good. Por isso o bot no twitter diz explicitamente "com 1 dose" e "com 2 doses", para pelo menos o português estar correcto.

O relatório semanal tem os valores de doses/1/2 para nacional e para continente (para cada ARS+ilhas, portanto a soma de ARS dá o continente, tal como o nacional menos ilhas dá o continente, que é publicado no vacinas_detalhes.csv)
Mas o semanal contabiliza as unidoses no doses2, correctamente.

Se comparar o mesmo dia (por exemplo, 21 ou 14 de junho) entre o vacinas.csv (diario) e o vacinas_detalhe (semanal), a diferença entre doses1 e doses2 bate certo com a quantidade de Janssen reportada na fonte da ECDC. O doses2 semanal é maior que o diário, e correspondente o doses1 semanal é inferior ao diário. Isto permite-me calcular a quantidade de Janssen (sem precisar de ir buscar à ECDC) e ajustar os valores diários.
Depois em cima disto tenho de acrescentar os valores das ilhas aos valores do continente, e destes dois ajustes pode então sair o totalmente vacinados, com pessoas com 2 doses e unidoses, o parcialmente vacinados com pessoas ainda com apenas 1 dose, o inoculados que contabiliza todas as pessoas com pelo menos uma vacina, e o vacinas com todas as doses administradas no país.

Como os dados do relatório são semanais os valores no csv (e no bot) serão mais baixos que a realidade durante seis dias, mas isso já acontece com os dados diários e semanais, pois são todos reajustados historicamente para cima - o relatório de dia 21 tem valores mais altos para dia 14 que o relatório de 14.

No final o que interessa é que os valores crescem rápido, e saber que os erros no processo são atrasos na introdução de dados e que com o tempo tendem para os valores reais.

Portanto, short version, 1. os doses/doses1/doses2 / primeiro tweet corresponde a "pessoas com 1 dose/unidose" e "pessoas com 2 doses" (diferente de "totalmente vacinadas"), e apenas continente, exactamente como reportado na dashboard e nas redes sociais. Os novos campos pessoas/vacinas corresponde ao pais todo, e correctamente a "vacinação completa" e "parcial", embora tenha o delay dos dados serem semanais. Portanto 2 o doses é continente e o vacinas é nacional, portanto com um valor maior, embora possa estar temporariamente deflacionado (esta semana faltam 72 mil doses, mas o relatório da semana que vem irá certamente corrigir isto, como tem feito com os valores anteriores)

**Comment by davipt** [comment]
Simplificando, o `vacinas.csv` (documentado no README) inclui:

* `doses` / `doses1` / `doses2` exactamente conforme reportado diariamente. Estes incluem apenas o continente, e têm as unidoses no doses1. Os dados diários focam-se em "vacinas" e não em "pessoas"

* `pessoas*` / `vacinas*` calculados baseado nos dados diários ajustados com os dados semanais mais recentes (portanto com 6 dias undercounted). Foca-se em pessoas. Acerta as unidoses para os "totalmente vacinados", deixando os "parcialmente" com as pessoas que ainda falta completar a vacinação, portanto um valor que tenderá para zero.
