### ISSUE TITLE
vacinas.csv: as colunas "doses2" e "pessoas_vacinadas_completamente" são iguais

### ISSUE THREAD

**Issue by snovaisg** [dssg-pt/covid19pt-data#879]
isto significa que PT está a administrar todas as doses2 que recebe no mesmo dia? Ou haverá alguma particularidade na forma como os dados são reportados pela DGS?

**Comment by davipt** [comment]
Os primeiros dados oficiais (as imagens nas redes sociais) referem "vacinas", ao qual optamos por usar "doses" para não confundir com "vacinados".

Os dados seguintes, a API da dashboard, fala em "inoculacoes 1 e 2" (doses 1 e 2) e "vacinados" (doses totais), o que é ainda mais confuso.

Posteriormente os dados do relatório semanal falam em "vacinação total" e "vacinação parcial", onde "total" inclui quem tem a 2ª dose e quem tem a unidose da Janssen.

Para deixar isto mais claro, adicionei as colunas redundantes no csv, e dai o "completamente" ser igual ao "doses2", pois ambos incluem quem está completamente vacinado (excluindo a potencial necessidade de reforço para variantes, ou o reforço periódico).

O relatório semanal tem campos para "distribuídas", mas não tem detalhe suficiente para se saber se as doses previstas administrar num dia são iguais às realmente administradas. Só se sabe as que foram realmente administradas, e sinceramente olhando para o relatório semanal e as actualizações retroativas, até serão mais que as reportadas diariamente, o que é bom.

Obrigado.
