### ISSUE TITLE
pessoas_vacinadas_parcialmente_novas valores negativos

### ISSUE THREAD

**Issue by Tekaichi** [dssg-pt/covid19pt-data#882]
Boa tarde,

Reparei que há (pelo menos duas linhas) em que o _valor pessoas_vacinadas_parcialmente_novas_ em _vacinas.csv_ é menor que 0
![image](https://user-images.githubusercontent.com/13667847/121354189-8dce9b80-c926-11eb-8f51-919d96b4a10b.png)

Existe alguma justificação ou está de facto errado ?

Suponho que quando algo é "novo", devia ser sempre > 0 ?

Obrigado!

**Comment by davipt** [comment]
Olá Miguel.

Os valores "XYZ_novas" é um valor redundante calculado e confirmado para a diferença entre o valor "XYZ" de hoje menos o de ontem. Isto aplica-se a todos os ficheiros.

O valor oficial de doses1 (inoculacao1 na api oficial, vacinas 1º dose na imagem oficial nas redes sociais) contabiliza todas as pessoas que já tenham levado a primeira dose *incluindo* quem já levou a segunda dose. No entanto não contabiliza quem levou a unidose da Janssen.

Isto quer dizer que o "parcialmente vacinado" contabiliza quem levou a primeira dose mas ainda não levou a segunda. Daí que quando uma pessoa leva a segunda dose, soma ao "doses2" / "totalmente vacinado", e reduz do "parcialmente vacinado".

Ou seja, quando o novas é negativo, quer dizer que nesse dia houve mais pessoas que levaram a segunda dose, que outras pessoas a levar a primeira. Ou seja, "parcial" == "doses1" menos "doses2".

(Nota: este valor de "parcial" não está correcto pois inclui as unidoses e não devia, mas eventualmente com o tempo este valor tenderá para zero assim que toda a gente tenha a vacinação total, seja as duas doses, seja a unidose)

Estes dois valores são os usados no bot https://twitter.com/PlenoDVacinacao para reportar quantas pessoas totalmente vacinadas (2 doses / unidose) e quantas pessoas adicionais estão a caminho (parcial) de serem vacinadas.

Obrigado
