### ISSUE TITLE
Problema na série

### ISSUE THREAD

**Issue by perone** [dssg-pt/covid19pt-data#9]
A DGS acabou fazendo releases meio **confusos** no início, um desses problemas dá para ver na série nas datas em que há **39 e 41 confirmados**. Desavisados sobre isto podem acabar utilizando estes dados e ter muitas dores de cabeça porque **tanto o 41 quanto o 59 (dia seguinte) incluem dados do mesmo dia 10 de Março**. Esse é o tipo de coisa que acabo corrigindo manualmente nas análises, mas que pode confundir muitas outras análises. Acredito que ou deve-se alterar os dados em https://github.com/dssg-pt/covid19pt-data/blob/master/data.csv, em adicionar um warning claro na página inicial, pois pode acabar influenciando gravemente em análises de pessoas desavisadas.

**Comment by ishouldbedany** [comment]
![image](https://user-images.githubusercontent.com/6266595/76855761-b5c96f00-6849-11ea-9eaf-0112f41d3c55.png)

Acho que o problema está aqui, neste pedaço de informação da DGS. Ainda não consegui perceber bem o que significa "Atualizado a". Referir-se-à meramente à data de produção do PDF?

Podemos tentar adicionar, na coluna `data`, a timestamp horária a que os dados dizem respeito.

**Comment by perone** [comment]
Acho que seria ótimo adicionar estas 2 novas colunas, porque fica muito confuso para quem faz as análises.

**Comment by ishouldbedany** [comment]
A @filipafcastro está a tratar disto. Hoje deveremos ter novidades.

**Comment by ishouldbedany** [comment]
@perone Adiciona a coluna `data_dados` com o dia e hora a que os dados se referem (a `data` manteve-se apenas com o dia em que os dados são publicados), conforme a DGS reporta.

Esperemos que seja útil!

**Comment by perone** [comment]
Obrigado @ishouldbedany ! Certamente vai ajudar e ajudar outras pessoas a não se enganarem no momento da análise.

**Comment by rquintino** [comment]
Vivas! (excelente trabalho antes de mais, muito ob a todos!)

Sobre esta questão das datas, ainda fica um pouco confuso, tecnicamente está correcto acho, ie dados publicados dia 19 pela DGS dizem respeito aos dados até dia 19 às 00:00, o problema é na prática dizem respeito aos dados de dia 18 não?

em boa verdade a DGS menciona até 24:00 de dia 18 :)

![image](https://user-images.githubusercontent.com/10835742/77126030-a9a70280-6a3f-11ea-891c-ec8346d1cdbb.png)

mas aqui temos a mesma data para os dois:
![image](https://user-images.githubusercontent.com/10835742/77126065-c2171d00-6a3f-11ea-9c6f-5008832a9ea4.png)


Prov alterar agora é arriscado mas então ter um aviso bem visivel?

**Comment by ishouldbedany** [comment]
@rquintino Obrigado pelo feedback! 

Efectivamente ao transcrever os dados para aí fiz da maneira que sugeriste e que está nos boletins, mas o meu editor de CSVs fazia a correcção automática para este formato. Por motivos de retrocompatibilidade, acho que vamos manter, mas aquando da actualização de dados de hoje iremos adicionar essa nota ao `README.md`. Acho que é um bom compromisso.
