### ISSUE TITLE
Impacto no mercado de trabalho

### ISSUE THREAD

**Issue by piresn** [dssg-pt/covid19pt-data#91]
O Ministério do Trabalho, Solidariedade e Segurança Social disponibiliza dados referentes ao impacto do covid-19 no mercado de trabalho em http://www.gep.mtsss.gov.pt/indicadores-covid-19-mtsss.

Os dados são actualizadas regularmente e incluem p. ex o número diário de layoffs, despedimentos e desempregados.

As tabelas já estão bastante estruturadas e acessíveis (formato .xlsx), mas seria interessante limpar alguns destes dados mais um pouco e adicionar ao repositório.

**Comment by zemanels** [comment]
Agradeço esta partilha. Com os dados existentes criei algo no https://covid19.crossroads.pt/efeitos-em-portugal/ de forma a se verificar os efeitos desta pandemia. Será uma página a melhorar, com dados de outras vertentes quando conseguir. Novamente agradecer a partilha!

**Comment by tensorfreitas** [comment]
Obrigado pela partilha, vamos tentar implementar o download destes dados em breve.

**Comment by paulomaia20** [comment]
Fechado e reformulado para um mini projeto: https://github.com/dssg-pt/covid19pt-data/issues/152
