### ISSUE TITLE
Dados Incorretos em comparação com os da DGS

### ISSUE THREAD

**Issue by hugodslo** [dssg-pt/covid19pt-data#946]
Dados de dia 29/06/2021 da coluna _confirmados_arsalentejo_ mostram 30993 quando no relatório da [DGS](https://covid19.min-saude.pt/wp-content/uploads/2021/06/484_DGS_boletim_20210629.pdf) são 30933.

**Comment by davipt** [comment]
Correcto.

Como referido no README, os dados são obtidos da API da dashboard da DGS para que o processo seja automático e para se obter os valores de confirmados e óbitos por idade que estão em falta no PDF há vários meses.

O que me parece ter acontecido pela segunda vez nos últimos dias terá sido a ESRI ter recebido números mais actualizados que os da meia noite usados no PDF. Há que ter em conta que a dashboard tipicamente só é actualizada horas mais tarde.

Houve mesmo mais 60 casos no Alentejo, tal como houve mais 4 no Algarve no passado dia 25. No dia seguinte esses casos são reajustados ao aparecem no PDF mas não nos números da dashboard - 2362 novos vs 2302

Os valores dos CSV são comparados automaticamente uns com os outros - somas por idade, por género, por região - para confirmar se estão correctos e fazem sentido. Seria impossível remover manualmente os 60 casos do Alentejo (e 4 do Algarve) pois não sabemos quais as faixas etárias a ajustar. A alternativa seria não ter dados por idade de todo, o que prejudica os cálculos da evolução por idade.

Portanto é verdade que há dias e há valores que divergem entre os dados oficiais dia DGS, entre o PDF gerado com dados da meia noite, e os dados disponíveis na API da dashboard.
Nuns casos há erros na introdução dos dados na API, os quais são detectados pelos testes acima referidos, e corrigidos manualmente quando são óbvios (exemplo dislexia com dígitos trocados, ou valores mais elevados por duplicação de dígitos). Nestes dois casos os valores parecem estar correctos, mas registados em dias diferentes.

Faz sentido? Obrigado pelo aviso.

**Comment by hugodslo** [comment]
Percebido, faz sentido sim senhor! Obrigado pelo esclarecimento.
