### ISSUE TITLE
vacinas.csv - negative values 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [dssg-pt/covid19pt-data#947]
![newplot (6)](https://user-images.githubusercontent.com/34355337/124127912-2bc00c80-da74-11eb-9143-f4b1a928bf74.png)

the column pessoas_vacinadas_parcialmente_novas has negative values, as you can see in the image above. 

Any reason for this or is this an error?

**Comment by JorgeMiguelGomes** [comment]
Suggestion: Have that reflected on the Read.md file as well as columns descriptions, as those are not very clear.

**Comment by davipt** [comment]
Thank you. It's already described on the readme but I hear you that it would help further explaining why there can be negative values on the daily diff.
