### ISSUE TITLE
oscilação de população no ficheiro vacinas_detalhe.csv

### ISSUE THREAD

**Issue by chegancasb** [dssg-pt/covid19pt-data#961]
Noto que no ficheiro vacinas_detalhe.csv, de umas entradas para outras, o valores de população oscila (quer para a coluna referente à população total quer para os grupos etários e por região) de um dia para outro, em torno de um valor mais ou menos constante.

É defeito do processo de agregação dos dados ou a informação de origem está a gerar esta oscilação?

Já agora aproveito para solicitar um esclarecimento que possa ser a origem da oscilação acima descrita.
Na descrição das colunas população - usando como exemplo a informação alusiva às colunas `populacao1` -  surge `População a que se referem os dados (doses1 ÷ doses1_perc), a que deverá corresponder ao respectivo valor de população de acordo com INE/PORDATA 2019`. Percebo daqui que o valor das colunas `populacao[12](_Y)?` é calculado usando a divisão indicada, é isso? 
Se assim é, porquê fazer o cálculo e registá-lo diariamente no ficheiro? Se o valor da população (por região e faixa etária) é fixo (é pelo menos essa a expéctativa), bastaria registá-lo num ficheiro de dados de referência sem o repetir diáriamente.

É uma sugestão de redução da quantidade informação estática, repetida mais de 10 vezes (se o raciocinio for aplicado por região e faixa etária) e que poderá ser fácilmente calculada se desejado.... e atreveria a dizer, sem querer ofender, que de um dia para o outro não acrescenta informação nova. 

Obrigado pela atenção e parabêns por um excelente trabalho e pelo esforço dispendido

Cumprimentos,
BC

**Comment by davipt** [comment]
Olá. Sim os campos de população são redundantes e calculados pelas respectivas doses e percentagem, o que causa pequenas oscilações por arredondamento de floats.

Estão no CSV para se poder rapidamente confirmar "a olhómetro" se realmente correspondem aos dados do INE 2019.

No início com a falta dos valores das ilhas foi confuso perceber qual a população usada em vários locais na Internet.
Por exemplo os dados diários (e primeiros dados semanais) referem-se apenas à população continente INE 2019 (~9.8M), mas outros sites que mostram dados de vários países usam a estimativa de população nacional da ONU (~10.2M), enquanto a população nacional incluindo ilhas, usado nas vacinas e nos concelhos, é de ~10.3M. (Vide [tweet_vacinas](https://github.com/dssg-pt/covid19pt-data/blob/master/.github/workflows/tweet_vacinas.py))

Na prática é mais fácil fazer contas quando os valores estão todos juntos no mesmo ficheiro (a oscilação é mínima e não afecta as contas), do que estar a referenciar outro ficheiro, principalmente quando o outro menciona "NUTS" [População PORDATA](https://github.com/dssg-pt/covid19pt-data/blob/master/extra/populacional/PORDATA_Estimativas-a-31-12.csv)

Storage e conectividade são baratas.
Perceber porque valores diários, semanais, a OWID, o Público, etc. mostravam números e percentagens diferentes, aí o custo humano é grande 🤯
