### ISSUE TITLE
API da VOST não tem os dados atualizados ao dia

### ISSUE THREAD

**Issue by jmaferreira** [dssg-pt/covid19pt-data#965]
Viva,

O dataset completo disponibilizado pela VOST não está atualizado ao dia. 

Ao consultarmos no dia 2021-07-07 o dataset disponibilizado pelo endpoint `https://covid19-api.vost.pt/Requests/get_full_dataset_counties` só obtemos dados até ao dia 2027-07-01.

Isto é uma situação temporária, ou é mesmo assim? De quanto em quanto tempo é que os dados fornecidos por este endpoint são atualizados?

**Comment by ishouldbedany** [comment]
Olá @jmaferreira, 

Os dados da incidência dos concelhos só são actualizados/disponibilizados na fonte oficial com uma periodicidade semanal (geralmente), daí este comportamento. De cabeça não me recordo, mas esse endpoint estará provavelmente a alimentar-se dos ficheiros `data_concelhos_14dias.csv`, `data_concelhos_incidencia.csv` ou `data_concelhos_new.csv`, que seguem essa cadência semanal. 

Tanto quanto sabemos, não há dados de concelhos diários (salvo publicações isoladas por autarcas nas respectivas plataformas de comunicação).

O _endpoint_ dos dados diários globais mostra o mesmo comportamento? Se sim, então algo está definitivamente errado.

**Comment by jmaferreira** [comment]
@ishouldbedany Obrigado. Isso esclarece a questão.
