### ISSUE TITLE
Dados vacinas desatulizados

### ISSUE THREAD

**Issue by matiasfreitasguimaraes** [dssg-pt/covid19pt-data#982]
Provavelmente nao é um problema, mas gostava de entender. Os dados das vacinas nao estao mais sendo atualizados. Algum motivo?

**Comment by davipt** [comment]
É verdade. Só há dados oficiais até quinta feira passada, dia 8.

Acredito que estejam a melhorar o processo para que os números diários contabilizem também as ilhas, e que voltem a ser publicados após o fim de semana.

Vamos esperar por amanhã.


https://www.sns.gov.pt/monitorizacao-do-sns/vacinas-covid-19/ <-- passou a dar 404 not found

https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/ <-- continua com 9625694 de quinta

**Comment by emanuelmarques** [comment]
e já que estão com as maos na massa que incluam tambem os dados das doses unicas :p

**Comment by davipt** [comment]
Estão incluídos. Acho que documentei isso no README. As colunas "doses"/"doses1"/"doses2" são exactamente os valores oficiais diários, independentemente de serem apenas o Continente ou quiçá incluir as ilhas desde há uma semana, e independente de onde contabilizam as unidoses (doses1). Daí o bot no Twitter usar a terminologia "com uma dose" e "com duas doses". 
Já as colunas "pessoas*" e "vacinas" são ajustadas pelos números dos relatórios semanais e incluem as ilhas e as unidoses como "vacinação completa" tal como "inoculado" (o "at least one" no relatório), mas não no "vacinação parcial" ("iniciada" no relatório). Assumindo o relatório semanal como correcto, o que me parece ser pois o histórico é constantemente actualizado, essas colunas de pessoas e vacinas estarão correctos no dia do relatório, e depois seis dias abaixo dos valores reais, pois só sabemos os valores do continente diariamente, e não as ilhas ou onde estão as unidoses. Mas passado uma semana acerta tudo novamente. Isto é também confirmado pelos valores semanais de Janssen administradas em Portugal e reportadas na ECDC. 

Agora é esperar por segunda, e depois por terça à noite para o relatório, para perceber se mudou mais alguma coisa.

**Comment by emanuelmarques** [comment]
sim, eu sei. Mas é como dizes. Para esses casos de pessoas que foram infetadas e de doses unicas, os dados sao de mais dificil compreensão.

Existe algum ponto de contacto do lado da DGS para se perceber o que se está a passar?

**Comment by emanuelmarques** [comment]
also, https://covid19.min-saude.pt/ponto-de-situacao-atual-em-portugal/ 
ja tem dados atualizados

**Comment by trapko91** [comment]
Acho estranha a actualização, parece pouco para 3 dias sem actualizar.

Ainda por cima a taskforce acabou de dizer que deram 1 milhão de doses de dia 5 a 11, no entanto, pelos números oficiais apenas conto ~680 mil. Que confusão..

**Comment by emanuelmarques** [comment]
isto cheira me a assertos. Na TV falam de recordes de 150k por dia, quando nos registos temos dias com 280k

**Comment by davipt** [comment]
Correcto. Mais uma vez, o `vacinas.csv` inclui o `doses` / `doses1` / `doses2` com os valores exactos tal como reportados diariamente (com cópia do resultado da API no `extras/vacinas/diário/*.JSON`).

Como os valores continuam a não fazer sentido, as colunas de `pessoas` continuam vazias até pelo menos amanhã à noite quando sair o próximo relatório semanal.

**Comment by trapko91** [comment]
é capaz, o dia 5 foi logo após esses dias com 280 mil

**Comment by tiago32rodriguez** [comment]
Eu acho q eles tinham adicionado os dados das ilhas até dia 8, mas os dados de hoje voltam a ser apenas de Portugal continental.
A diretora-geral da Saúde disse q até dia 9 de julho Portugal continental tinha administrado 9.504.206, no entanto os dados de dia 8 já eram superiores.
source: https://magg.sapo.pt/atualidade/atualidade-nacional/artigos/tres-milhoes-pessoas-duas-doses-vacina-poucos-infetados

Como o update de hoje foi tao baixo (tendo em conta as noticias e os recordes q se falou) suponho q eles tenham esperado q os dados do continente "alcançassem" os dados q tinham na dashboard, daí ter havido 3 dias sem novos dados

**Comment by davipt** [comment]
Confirma-se que houve integração entre os sistemas das regiões autónomas e a plataforma VACINAS o que inflacionou os valores diários. Todos os valores estão correctos, excepto quando contabilizam coisas diferentes e em dias diferentes.

Os dados diários de dia 12 e 13 voltaram ao normal - apenas continente, e com as unidoses no campo "com uma dose".

Assim sendo mantêm-se os dados doses/doses1/doses2 alinhado com os valores oficiais, quaisquer que tenham sido, mas os calculados de pessoas/vacinas deixam de existir de 30-06 a 04-07 (para não ter os 280 mil/dia) , e a 08-07 (182k/dia).
Os dias 9 a 11 estão vazios pois não foram divulgados dados diários.

Temos todos de adaptar o código para lidar com a falta de dados e não mostrar a diferença diária quando não há dados para o dia anterior, e também ter cuidado com cálculos de médias (7 dias por exemplo) caso calhem em dias em falta.

Obrigado a todos.
