### ISSUE TITLE
Missing row #500

### ISSUE THREAD

**Issue by rcarmo** [dssg-pt/covid19pt-data#992]
Just a call out to say that row # 500 in data.csv (08-07-2021) is partially blank, so maybe check if the API scraper (or whatever) needs a manual run?

**Comment by davipt** [comment]
That is correct. The data for 08-07-2020 was never published by ESRI on DGS's dashboard, so the row only includes data that is available on the PDF, excluding the cases and deaths per age. The same happened back in 25-04-2021.
(and apparently it will probably also happen today, which have cases but does not have deaths per age nor per genre)
 
Those values per age are on the PDF as a chart, impossible to know the concrete values. If they're not published, no-one will know them (and I've tried hard to hunt them down by other means)

**Comment by davipt** [comment]
Olá Rui. A DGS (ESRI) mudou a API da dashboard e só hoje 16 é que me apercebi (se calhar até só mudaram o endpoint hoje, não sei). Alterei o script que faz download dos dados https://github.com/dssg-pt/covid19pt-data/pull/1000 e as boas notícias é que os dados em falta - 8, 14 (óbitos), e os últimos dois dias 15 e 16 - estão disponíveis neste novo endpoint, portanto o data.csv já tem esses dados todos em falta.
Obrigado mais uma vez.

**Comment by rcarmo** [comment]
Obrigado. É o costume, alteram as coisas sem qualquer cuidado... vou re-importar o dataset, thanks!
